global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'

  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8080']
    metrics_path: '/metrics'

  - job_name: 'preprocessor'
    static_configs:
      - targets: ['preprocessor:8080']
    metrics_path: '/metrics'

  - job_name: 'embedding'
    static_configs:
      - targets: ['embedding:8080']
    metrics_path: '/metrics'

  - job_name: 'docstore'
    static_configs:
      - targets: ['docstore:8080']
    metrics_path: '/metrics'

  - job_name: 'reranker'
    static_configs:
      - targets: ['reranker:8080']
    metrics_path: '/metrics'

  - job_name: 'assembler'
    static_configs:
      - targets: ['assembler:8080']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus-standalone:9091']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']