// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/embedding_svc.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	v1 "rag/api/common/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmbeddingVector struct {
	Values               []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmbeddingVector) Reset()         { *m = EmbeddingVector{} }
func (m *EmbeddingVector) String() string { return proto.CompactTextString(m) }
func (*EmbeddingVector) ProtoMessage()    {}
func (*EmbeddingVector) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{0}
}

func (m *EmbeddingVector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddingVector.Unmarshal(m, b)
}
func (m *EmbeddingVector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddingVector.Marshal(b, m, deterministic)
}
func (m *EmbeddingVector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddingVector.Merge(m, src)
}
func (m *EmbeddingVector) XXX_Size() int {
	return xxx_messageInfo_EmbeddingVector.Size(m)
}
func (m *EmbeddingVector) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddingVector.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddingVector proto.InternalMessageInfo

func (m *EmbeddingVector) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type EmbedTextRequest struct {
	Text                 string            `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ModelName            string            `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Options              *EmbeddingOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmbedTextRequest) Reset()         { *m = EmbedTextRequest{} }
func (m *EmbedTextRequest) String() string { return proto.CompactTextString(m) }
func (*EmbedTextRequest) ProtoMessage()    {}
func (*EmbedTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{1}
}

func (m *EmbedTextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedTextRequest.Unmarshal(m, b)
}
func (m *EmbedTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedTextRequest.Marshal(b, m, deterministic)
}
func (m *EmbedTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedTextRequest.Merge(m, src)
}
func (m *EmbedTextRequest) XXX_Size() int {
	return xxx_messageInfo_EmbedTextRequest.Size(m)
}
func (m *EmbedTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedTextRequest proto.InternalMessageInfo

func (m *EmbedTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EmbedTextRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *EmbedTextRequest) GetOptions() *EmbeddingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type EmbeddingOptions struct {
	Normalize            bool              `protobuf:"varint,1,opt,name=normalize,proto3" json:"normalize,omitempty"`
	PoolingStrategy      string            `protobuf:"bytes,2,opt,name=pooling_strategy,json=poolingStrategy,proto3" json:"pooling_strategy,omitempty"`
	MaxLength            int32             `protobuf:"varint,3,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Truncate             bool              `protobuf:"varint,4,opt,name=truncate,proto3" json:"truncate,omitempty"`
	Instruction          string            `protobuf:"bytes,5,opt,name=instruction,proto3" json:"instruction,omitempty"`
	ModelParameters      map[string]string `protobuf:"bytes,6,rep,name=model_parameters,json=modelParameters,proto3" json:"model_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmbeddingOptions) Reset()         { *m = EmbeddingOptions{} }
func (m *EmbeddingOptions) String() string { return proto.CompactTextString(m) }
func (*EmbeddingOptions) ProtoMessage()    {}
func (*EmbeddingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{2}
}

func (m *EmbeddingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddingOptions.Unmarshal(m, b)
}
func (m *EmbeddingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddingOptions.Marshal(b, m, deterministic)
}
func (m *EmbeddingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddingOptions.Merge(m, src)
}
func (m *EmbeddingOptions) XXX_Size() int {
	return xxx_messageInfo_EmbeddingOptions.Size(m)
}
func (m *EmbeddingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddingOptions proto.InternalMessageInfo

func (m *EmbeddingOptions) GetNormalize() bool {
	if m != nil {
		return m.Normalize
	}
	return false
}

func (m *EmbeddingOptions) GetPoolingStrategy() string {
	if m != nil {
		return m.PoolingStrategy
	}
	return ""
}

func (m *EmbeddingOptions) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *EmbeddingOptions) GetTruncate() bool {
	if m != nil {
		return m.Truncate
	}
	return false
}

func (m *EmbeddingOptions) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *EmbeddingOptions) GetModelParameters() map[string]string {
	if m != nil {
		return m.ModelParameters
	}
	return nil
}

type EmbedTextResponse struct {
	Embedding            []float32          `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Dimension            int32              `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	ModelUsed            string             `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	Metadata             *EmbeddingMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EmbedTextResponse) Reset()         { *m = EmbedTextResponse{} }
func (m *EmbedTextResponse) String() string { return proto.CompactTextString(m) }
func (*EmbedTextResponse) ProtoMessage()    {}
func (*EmbedTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{3}
}

func (m *EmbedTextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedTextResponse.Unmarshal(m, b)
}
func (m *EmbedTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedTextResponse.Marshal(b, m, deterministic)
}
func (m *EmbedTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedTextResponse.Merge(m, src)
}
func (m *EmbedTextResponse) XXX_Size() int {
	return xxx_messageInfo_EmbedTextResponse.Size(m)
}
func (m *EmbedTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedTextResponse proto.InternalMessageInfo

func (m *EmbedTextResponse) GetEmbedding() []float32 {
	if m != nil {
		return m.Embedding
	}
	return nil
}

func (m *EmbedTextResponse) GetDimension() int32 {
	if m != nil {
		return m.Dimension
	}
	return 0
}

func (m *EmbedTextResponse) GetModelUsed() string {
	if m != nil {
		return m.ModelUsed
	}
	return ""
}

func (m *EmbedTextResponse) GetMetadata() *EmbeddingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type EmbeddingMetadata struct {
	TokenCount           int32                  `protobuf:"varint,1,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ProcessingTimeMs     int64                  `protobuf:"varint,2,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	WasTruncated         bool                   `protobuf:"varint,3,opt,name=was_truncated,json=wasTruncated,proto3" json:"was_truncated,omitempty"`
	EncodingFormat       string                 `protobuf:"bytes,4,opt,name=encoding_format,json=encodingFormat,proto3" json:"encoding_format,omitempty"`
	ModelMetadata        map[string]string      `protobuf:"bytes,5,rep,name=model_metadata,json=modelMetadata,proto3" json:"model_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EmbeddingMetadata) Reset()         { *m = EmbeddingMetadata{} }
func (m *EmbeddingMetadata) String() string { return proto.CompactTextString(m) }
func (*EmbeddingMetadata) ProtoMessage()    {}
func (*EmbeddingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{4}
}

func (m *EmbeddingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddingMetadata.Unmarshal(m, b)
}
func (m *EmbeddingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddingMetadata.Marshal(b, m, deterministic)
}
func (m *EmbeddingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddingMetadata.Merge(m, src)
}
func (m *EmbeddingMetadata) XXX_Size() int {
	return xxx_messageInfo_EmbeddingMetadata.Size(m)
}
func (m *EmbeddingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddingMetadata proto.InternalMessageInfo

func (m *EmbeddingMetadata) GetTokenCount() int32 {
	if m != nil {
		return m.TokenCount
	}
	return 0
}

func (m *EmbeddingMetadata) GetProcessingTimeMs() int64 {
	if m != nil {
		return m.ProcessingTimeMs
	}
	return 0
}

func (m *EmbeddingMetadata) GetWasTruncated() bool {
	if m != nil {
		return m.WasTruncated
	}
	return false
}

func (m *EmbeddingMetadata) GetEncodingFormat() string {
	if m != nil {
		return m.EncodingFormat
	}
	return ""
}

func (m *EmbeddingMetadata) GetModelMetadata() map[string]string {
	if m != nil {
		return m.ModelMetadata
	}
	return nil
}

func (m *EmbeddingMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type EmbedBatchRequest struct {
	Texts                []string          `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	ModelName            string            `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Options              *EmbeddingOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	BatchId              string            `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmbedBatchRequest) Reset()         { *m = EmbedBatchRequest{} }
func (m *EmbedBatchRequest) String() string { return proto.CompactTextString(m) }
func (*EmbedBatchRequest) ProtoMessage()    {}
func (*EmbedBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{5}
}

func (m *EmbedBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedBatchRequest.Unmarshal(m, b)
}
func (m *EmbedBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedBatchRequest.Marshal(b, m, deterministic)
}
func (m *EmbedBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedBatchRequest.Merge(m, src)
}
func (m *EmbedBatchRequest) XXX_Size() int {
	return xxx_messageInfo_EmbedBatchRequest.Size(m)
}
func (m *EmbedBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedBatchRequest proto.InternalMessageInfo

func (m *EmbedBatchRequest) GetTexts() []string {
	if m != nil {
		return m.Texts
	}
	return nil
}

func (m *EmbedBatchRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *EmbedBatchRequest) GetOptions() *EmbeddingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *EmbedBatchRequest) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

type EmbedBatchResponse struct {
	BatchId              string                  `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Results              []*EmbeddingResult      `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Metadata             *BatchEmbeddingMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EmbedBatchResponse) Reset()         { *m = EmbedBatchResponse{} }
func (m *EmbedBatchResponse) String() string { return proto.CompactTextString(m) }
func (*EmbedBatchResponse) ProtoMessage()    {}
func (*EmbedBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{6}
}

func (m *EmbedBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedBatchResponse.Unmarshal(m, b)
}
func (m *EmbedBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedBatchResponse.Marshal(b, m, deterministic)
}
func (m *EmbedBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedBatchResponse.Merge(m, src)
}
func (m *EmbedBatchResponse) XXX_Size() int {
	return xxx_messageInfo_EmbedBatchResponse.Size(m)
}
func (m *EmbedBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedBatchResponse proto.InternalMessageInfo

func (m *EmbedBatchResponse) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *EmbedBatchResponse) GetResults() []*EmbeddingResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *EmbedBatchResponse) GetMetadata() *BatchEmbeddingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type EmbeddingResult struct {
	Index                int32               `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Embedding            []float32           `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Status               v1.ProcessingStatus `protobuf:"varint,3,opt,name=status,proto3,enum=api.common.v1.ProcessingStatus" json:"status,omitempty"`
	ErrorMessage         string              `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EmbeddingMetadata    *EmbeddingMetadata  `protobuf:"bytes,5,opt,name=embedding_metadata,json=embeddingMetadata,proto3" json:"embedding_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EmbeddingResult) Reset()         { *m = EmbeddingResult{} }
func (m *EmbeddingResult) String() string { return proto.CompactTextString(m) }
func (*EmbeddingResult) ProtoMessage()    {}
func (*EmbeddingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{7}
}

func (m *EmbeddingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbeddingResult.Unmarshal(m, b)
}
func (m *EmbeddingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbeddingResult.Marshal(b, m, deterministic)
}
func (m *EmbeddingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbeddingResult.Merge(m, src)
}
func (m *EmbeddingResult) XXX_Size() int {
	return xxx_messageInfo_EmbeddingResult.Size(m)
}
func (m *EmbeddingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbeddingResult.DiscardUnknown(m)
}

var xxx_messageInfo_EmbeddingResult proto.InternalMessageInfo

func (m *EmbeddingResult) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EmbeddingResult) GetEmbedding() []float32 {
	if m != nil {
		return m.Embedding
	}
	return nil
}

func (m *EmbeddingResult) GetStatus() v1.ProcessingStatus {
	if m != nil {
		return m.Status
	}
	return v1.ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (m *EmbeddingResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *EmbeddingResult) GetEmbeddingMetadata() *EmbeddingMetadata {
	if m != nil {
		return m.EmbeddingMetadata
	}
	return nil
}

type BatchEmbeddingMetadata struct {
	TotalTexts            int32                  `protobuf:"varint,1,opt,name=total_texts,json=totalTexts,proto3" json:"total_texts,omitempty"`
	SuccessfulEmbeddings  int32                  `protobuf:"varint,2,opt,name=successful_embeddings,json=successfulEmbeddings,proto3" json:"successful_embeddings,omitempty"`
	FailedEmbeddings      int32                  `protobuf:"varint,3,opt,name=failed_embeddings,json=failedEmbeddings,proto3" json:"failed_embeddings,omitempty"`
	TotalProcessingTimeMs int64                  `protobuf:"varint,4,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	ModelUsed             string                 `protobuf:"bytes,5,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	StartedAt             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BatchEmbeddingMetadata) Reset()         { *m = BatchEmbeddingMetadata{} }
func (m *BatchEmbeddingMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchEmbeddingMetadata) ProtoMessage()    {}
func (*BatchEmbeddingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{8}
}

func (m *BatchEmbeddingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchEmbeddingMetadata.Unmarshal(m, b)
}
func (m *BatchEmbeddingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchEmbeddingMetadata.Marshal(b, m, deterministic)
}
func (m *BatchEmbeddingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchEmbeddingMetadata.Merge(m, src)
}
func (m *BatchEmbeddingMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchEmbeddingMetadata.Size(m)
}
func (m *BatchEmbeddingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchEmbeddingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchEmbeddingMetadata proto.InternalMessageInfo

func (m *BatchEmbeddingMetadata) GetTotalTexts() int32 {
	if m != nil {
		return m.TotalTexts
	}
	return 0
}

func (m *BatchEmbeddingMetadata) GetSuccessfulEmbeddings() int32 {
	if m != nil {
		return m.SuccessfulEmbeddings
	}
	return 0
}

func (m *BatchEmbeddingMetadata) GetFailedEmbeddings() int32 {
	if m != nil {
		return m.FailedEmbeddings
	}
	return 0
}

func (m *BatchEmbeddingMetadata) GetTotalProcessingTimeMs() int64 {
	if m != nil {
		return m.TotalProcessingTimeMs
	}
	return 0
}

func (m *BatchEmbeddingMetadata) GetModelUsed() string {
	if m != nil {
		return m.ModelUsed
	}
	return ""
}

func (m *BatchEmbeddingMetadata) GetStartedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *BatchEmbeddingMetadata) GetCompletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

type EmbedBatchAsyncRequest struct {
	Texts                []string          `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	ModelName            string            `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Options              *EmbeddingOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	CallbackUrl          string            `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	Priority             int32             `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EmbedBatchAsyncRequest) Reset()         { *m = EmbedBatchAsyncRequest{} }
func (m *EmbedBatchAsyncRequest) String() string { return proto.CompactTextString(m) }
func (*EmbedBatchAsyncRequest) ProtoMessage()    {}
func (*EmbedBatchAsyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{9}
}

func (m *EmbedBatchAsyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedBatchAsyncRequest.Unmarshal(m, b)
}
func (m *EmbedBatchAsyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedBatchAsyncRequest.Marshal(b, m, deterministic)
}
func (m *EmbedBatchAsyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedBatchAsyncRequest.Merge(m, src)
}
func (m *EmbedBatchAsyncRequest) XXX_Size() int {
	return xxx_messageInfo_EmbedBatchAsyncRequest.Size(m)
}
func (m *EmbedBatchAsyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedBatchAsyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedBatchAsyncRequest proto.InternalMessageInfo

func (m *EmbedBatchAsyncRequest) GetTexts() []string {
	if m != nil {
		return m.Texts
	}
	return nil
}

func (m *EmbedBatchAsyncRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *EmbedBatchAsyncRequest) GetOptions() *EmbeddingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *EmbedBatchAsyncRequest) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

func (m *EmbedBatchAsyncRequest) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type EmbedBatchAsyncResponse struct {
	TaskId                         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status                         v1.ProcessingStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=api.common.v1.ProcessingStatus" json:"status,omitempty"`
	EstimatedProcessingTimeSeconds int32                  `protobuf:"varint,3,opt,name=estimated_processing_time_seconds,json=estimatedProcessingTimeSeconds,proto3" json:"estimated_processing_time_seconds,omitempty"`
	CreatedAt                      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}               `json:"-"`
	XXX_unrecognized               []byte                 `json:"-"`
	XXX_sizecache                  int32                  `json:"-"`
}

func (m *EmbedBatchAsyncResponse) Reset()         { *m = EmbedBatchAsyncResponse{} }
func (m *EmbedBatchAsyncResponse) String() string { return proto.CompactTextString(m) }
func (*EmbedBatchAsyncResponse) ProtoMessage()    {}
func (*EmbedBatchAsyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{10}
}

func (m *EmbedBatchAsyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedBatchAsyncResponse.Unmarshal(m, b)
}
func (m *EmbedBatchAsyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedBatchAsyncResponse.Marshal(b, m, deterministic)
}
func (m *EmbedBatchAsyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedBatchAsyncResponse.Merge(m, src)
}
func (m *EmbedBatchAsyncResponse) XXX_Size() int {
	return xxx_messageInfo_EmbedBatchAsyncResponse.Size(m)
}
func (m *EmbedBatchAsyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedBatchAsyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedBatchAsyncResponse proto.InternalMessageInfo

func (m *EmbedBatchAsyncResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *EmbedBatchAsyncResponse) GetStatus() v1.ProcessingStatus {
	if m != nil {
		return m.Status
	}
	return v1.ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (m *EmbedBatchAsyncResponse) GetEstimatedProcessingTimeSeconds() int32 {
	if m != nil {
		return m.EstimatedProcessingTimeSeconds
	}
	return 0
}

func (m *EmbedBatchAsyncResponse) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type GetEmbeddingTaskStatusRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmbeddingTaskStatusRequest) Reset()         { *m = GetEmbeddingTaskStatusRequest{} }
func (m *GetEmbeddingTaskStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmbeddingTaskStatusRequest) ProtoMessage()    {}
func (*GetEmbeddingTaskStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{11}
}

func (m *GetEmbeddingTaskStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmbeddingTaskStatusRequest.Unmarshal(m, b)
}
func (m *GetEmbeddingTaskStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmbeddingTaskStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetEmbeddingTaskStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmbeddingTaskStatusRequest.Merge(m, src)
}
func (m *GetEmbeddingTaskStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmbeddingTaskStatusRequest.Size(m)
}
func (m *GetEmbeddingTaskStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmbeddingTaskStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmbeddingTaskStatusRequest proto.InternalMessageInfo

func (m *GetEmbeddingTaskStatusRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type GetEmbeddingTaskStatusResponse struct {
	TaskId               string              `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskStatus           *v1.TaskStatus      `protobuf:"bytes,2,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	Result               *EmbedBatchResponse `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetEmbeddingTaskStatusResponse) Reset()         { *m = GetEmbeddingTaskStatusResponse{} }
func (m *GetEmbeddingTaskStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmbeddingTaskStatusResponse) ProtoMessage()    {}
func (*GetEmbeddingTaskStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{12}
}

func (m *GetEmbeddingTaskStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmbeddingTaskStatusResponse.Unmarshal(m, b)
}
func (m *GetEmbeddingTaskStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmbeddingTaskStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetEmbeddingTaskStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmbeddingTaskStatusResponse.Merge(m, src)
}
func (m *GetEmbeddingTaskStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmbeddingTaskStatusResponse.Size(m)
}
func (m *GetEmbeddingTaskStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmbeddingTaskStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmbeddingTaskStatusResponse proto.InternalMessageInfo

func (m *GetEmbeddingTaskStatusResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GetEmbeddingTaskStatusResponse) GetTaskStatus() *v1.TaskStatus {
	if m != nil {
		return m.TaskStatus
	}
	return nil
}

func (m *GetEmbeddingTaskStatusResponse) GetResult() *EmbedBatchResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetModelInfoRequest struct {
	ModelName            string   `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelInfoRequest) Reset()         { *m = GetModelInfoRequest{} }
func (m *GetModelInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetModelInfoRequest) ProtoMessage()    {}
func (*GetModelInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{13}
}

func (m *GetModelInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelInfoRequest.Unmarshal(m, b)
}
func (m *GetModelInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetModelInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelInfoRequest.Merge(m, src)
}
func (m *GetModelInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetModelInfoRequest.Size(m)
}
func (m *GetModelInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelInfoRequest proto.InternalMessageInfo

func (m *GetModelInfoRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

type GetModelInfoResponse struct {
	ModelInfo            *ModelInfo `protobuf:"bytes,1,opt,name=model_info,json=modelInfo,proto3" json:"model_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetModelInfoResponse) Reset()         { *m = GetModelInfoResponse{} }
func (m *GetModelInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetModelInfoResponse) ProtoMessage()    {}
func (*GetModelInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{14}
}

func (m *GetModelInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelInfoResponse.Unmarshal(m, b)
}
func (m *GetModelInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetModelInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelInfoResponse.Merge(m, src)
}
func (m *GetModelInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetModelInfoResponse.Size(m)
}
func (m *GetModelInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelInfoResponse proto.InternalMessageInfo

func (m *GetModelInfoResponse) GetModelInfo() *ModelInfo {
	if m != nil {
		return m.ModelInfo
	}
	return nil
}

type ListModelsRequest struct {
	Pagination           *v1.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filters              []*v1.Filter          `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{15}
}

func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

func (m *ListModelsRequest) GetPagination() *v1.PaginationRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *ListModelsRequest) GetFilters() []*v1.Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ListModelsResponse struct {
	Models               []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Pagination           *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListModelsResponse) Reset()         { *m = ListModelsResponse{} }
func (m *ListModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListModelsResponse) ProtoMessage()    {}
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{16}
}

func (m *ListModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsResponse.Unmarshal(m, b)
}
func (m *ListModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsResponse.Merge(m, src)
}
func (m *ListModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListModelsResponse.Size(m)
}
func (m *ListModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsResponse proto.InternalMessageInfo

func (m *ListModelsResponse) GetModels() []*ModelInfo {
	if m != nil {
		return m.Models
	}
	return nil
}

func (m *ListModelsResponse) GetPagination() *v1.PaginationResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type ModelInfo struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version              string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Dimension            int32                  `protobuf:"varint,5,opt,name=dimension,proto3" json:"dimension,omitempty"`
	MaxSequenceLength    int32                  `protobuf:"varint,6,opt,name=max_sequence_length,json=maxSequenceLength,proto3" json:"max_sequence_length,omitempty"`
	SupportedLanguages   []string               `protobuf:"bytes,7,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	Capabilities         *ModelCapabilities     `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Performance          *ModelPerformance      `protobuf:"bytes,9,opt,name=performance,proto3" json:"performance,omitempty"`
	Configuration        *ModelConfiguration    `protobuf:"bytes,10,opt,name=configuration,proto3" json:"configuration,omitempty"`
	IsAvailable          bool                   `protobuf:"varint,11,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ModelInfo) Reset()         { *m = ModelInfo{} }
func (m *ModelInfo) String() string { return proto.CompactTextString(m) }
func (*ModelInfo) ProtoMessage()    {}
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{17}
}

func (m *ModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInfo.Unmarshal(m, b)
}
func (m *ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInfo.Marshal(b, m, deterministic)
}
func (m *ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfo.Merge(m, src)
}
func (m *ModelInfo) XXX_Size() int {
	return xxx_messageInfo_ModelInfo.Size(m)
}
func (m *ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfo proto.InternalMessageInfo

func (m *ModelInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelInfo) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ModelInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ModelInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ModelInfo) GetDimension() int32 {
	if m != nil {
		return m.Dimension
	}
	return 0
}

func (m *ModelInfo) GetMaxSequenceLength() int32 {
	if m != nil {
		return m.MaxSequenceLength
	}
	return 0
}

func (m *ModelInfo) GetSupportedLanguages() []string {
	if m != nil {
		return m.SupportedLanguages
	}
	return nil
}

func (m *ModelInfo) GetCapabilities() *ModelCapabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *ModelInfo) GetPerformance() *ModelPerformance {
	if m != nil {
		return m.Performance
	}
	return nil
}

func (m *ModelInfo) GetConfiguration() *ModelConfiguration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *ModelInfo) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

func (m *ModelInfo) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ModelInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ModelCapabilities struct {
	SupportsInstruction       bool     `protobuf:"varint,1,opt,name=supports_instruction,json=supportsInstruction,proto3" json:"supports_instruction,omitempty"`
	SupportsMultipleLanguages bool     `protobuf:"varint,2,opt,name=supports_multiple_languages,json=supportsMultipleLanguages,proto3" json:"supports_multiple_languages,omitempty"`
	SupportsDomainAdaptation  bool     `protobuf:"varint,3,opt,name=supports_domain_adaptation,json=supportsDomainAdaptation,proto3" json:"supports_domain_adaptation,omitempty"`
	PoolingStrategies         []string `protobuf:"bytes,4,rep,name=pooling_strategies,json=poolingStrategies,proto3" json:"pooling_strategies,omitempty"`
	EncodingFormats           []string `protobuf:"bytes,5,rep,name=encoding_formats,json=encodingFormats,proto3" json:"encoding_formats,omitempty"`
	SupportsBatchProcessing   bool     `protobuf:"varint,6,opt,name=supports_batch_processing,json=supportsBatchProcessing,proto3" json:"supports_batch_processing,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *ModelCapabilities) Reset()         { *m = ModelCapabilities{} }
func (m *ModelCapabilities) String() string { return proto.CompactTextString(m) }
func (*ModelCapabilities) ProtoMessage()    {}
func (*ModelCapabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{18}
}

func (m *ModelCapabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelCapabilities.Unmarshal(m, b)
}
func (m *ModelCapabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelCapabilities.Marshal(b, m, deterministic)
}
func (m *ModelCapabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelCapabilities.Merge(m, src)
}
func (m *ModelCapabilities) XXX_Size() int {
	return xxx_messageInfo_ModelCapabilities.Size(m)
}
func (m *ModelCapabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelCapabilities.DiscardUnknown(m)
}

var xxx_messageInfo_ModelCapabilities proto.InternalMessageInfo

func (m *ModelCapabilities) GetSupportsInstruction() bool {
	if m != nil {
		return m.SupportsInstruction
	}
	return false
}

func (m *ModelCapabilities) GetSupportsMultipleLanguages() bool {
	if m != nil {
		return m.SupportsMultipleLanguages
	}
	return false
}

func (m *ModelCapabilities) GetSupportsDomainAdaptation() bool {
	if m != nil {
		return m.SupportsDomainAdaptation
	}
	return false
}

func (m *ModelCapabilities) GetPoolingStrategies() []string {
	if m != nil {
		return m.PoolingStrategies
	}
	return nil
}

func (m *ModelCapabilities) GetEncodingFormats() []string {
	if m != nil {
		return m.EncodingFormats
	}
	return nil
}

func (m *ModelCapabilities) GetSupportsBatchProcessing() bool {
	if m != nil {
		return m.SupportsBatchProcessing
	}
	return false
}

type ModelPerformance struct {
	AvgProcessingTimeMs    float32            `protobuf:"fixed32,1,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	MaxThroughputPerSecond int32              `protobuf:"varint,2,opt,name=max_throughput_per_second,json=maxThroughputPerSecond,proto3" json:"max_throughput_per_second,omitempty"`
	MemoryUsageMb          int64              `protobuf:"varint,3,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	BenchmarkScores        map[string]float32 `protobuf:"bytes,4,rep,name=benchmark_scores,json=benchmarkScores,proto3" json:"benchmark_scores,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}           `json:"-"`
	XXX_unrecognized       []byte             `json:"-"`
	XXX_sizecache          int32              `json:"-"`
}

func (m *ModelPerformance) Reset()         { *m = ModelPerformance{} }
func (m *ModelPerformance) String() string { return proto.CompactTextString(m) }
func (*ModelPerformance) ProtoMessage()    {}
func (*ModelPerformance) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{19}
}

func (m *ModelPerformance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelPerformance.Unmarshal(m, b)
}
func (m *ModelPerformance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelPerformance.Marshal(b, m, deterministic)
}
func (m *ModelPerformance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelPerformance.Merge(m, src)
}
func (m *ModelPerformance) XXX_Size() int {
	return xxx_messageInfo_ModelPerformance.Size(m)
}
func (m *ModelPerformance) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelPerformance.DiscardUnknown(m)
}

var xxx_messageInfo_ModelPerformance proto.InternalMessageInfo

func (m *ModelPerformance) GetAvgProcessingTimeMs() float32 {
	if m != nil {
		return m.AvgProcessingTimeMs
	}
	return 0
}

func (m *ModelPerformance) GetMaxThroughputPerSecond() int32 {
	if m != nil {
		return m.MaxThroughputPerSecond
	}
	return 0
}

func (m *ModelPerformance) GetMemoryUsageMb() int64 {
	if m != nil {
		return m.MemoryUsageMb
	}
	return 0
}

func (m *ModelPerformance) GetBenchmarkScores() map[string]float32 {
	if m != nil {
		return m.BenchmarkScores
	}
	return nil
}

type ModelConfiguration struct {
	ModelType            string            `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Architecture         string            `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	DefaultParameters    map[string]string `protobuf:"bytes,3,rep,name=default_parameters,json=defaultParameters,proto3" json:"default_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RequiredParameters   []string          `protobuf:"bytes,4,rep,name=required_parameters,json=requiredParameters,proto3" json:"required_parameters,omitempty"`
	OptionalParameters   []string          `protobuf:"bytes,5,rep,name=optional_parameters,json=optionalParameters,proto3" json:"optional_parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModelConfiguration) Reset()         { *m = ModelConfiguration{} }
func (m *ModelConfiguration) String() string { return proto.CompactTextString(m) }
func (*ModelConfiguration) ProtoMessage()    {}
func (*ModelConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{20}
}

func (m *ModelConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelConfiguration.Unmarshal(m, b)
}
func (m *ModelConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelConfiguration.Marshal(b, m, deterministic)
}
func (m *ModelConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelConfiguration.Merge(m, src)
}
func (m *ModelConfiguration) XXX_Size() int {
	return xxx_messageInfo_ModelConfiguration.Size(m)
}
func (m *ModelConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ModelConfiguration proto.InternalMessageInfo

func (m *ModelConfiguration) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

func (m *ModelConfiguration) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *ModelConfiguration) GetDefaultParameters() map[string]string {
	if m != nil {
		return m.DefaultParameters
	}
	return nil
}

func (m *ModelConfiguration) GetRequiredParameters() []string {
	if m != nil {
		return m.RequiredParameters
	}
	return nil
}

func (m *ModelConfiguration) GetOptionalParameters() []string {
	if m != nil {
		return m.OptionalParameters
	}
	return nil
}

type ComputeSimilarityRequest struct {
	// Types that are valid to be assigned to EmbeddingSourceA:
	//
	//	*ComputeSimilarityRequest_TextA
	//	*ComputeSimilarityRequest_EmbeddingA
	EmbeddingSourceA isComputeSimilarityRequest_EmbeddingSourceA `protobuf_oneof:"embedding_source_a"`
	// Types that are valid to be assigned to EmbeddingSourceB:
	//
	//	*ComputeSimilarityRequest_TextB
	//	*ComputeSimilarityRequest_EmbeddingB
	EmbeddingSourceB     isComputeSimilarityRequest_EmbeddingSourceB `protobuf_oneof:"embedding_source_b"`
	SimilarityMetric     string                                      `protobuf:"bytes,5,opt,name=similarity_metric,json=similarityMetric,proto3" json:"similarity_metric,omitempty"`
	ModelName            string                                      `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Options              *EmbeddingOptions                           `protobuf:"bytes,7,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ComputeSimilarityRequest) Reset()         { *m = ComputeSimilarityRequest{} }
func (m *ComputeSimilarityRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeSimilarityRequest) ProtoMessage()    {}
func (*ComputeSimilarityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{21}
}

func (m *ComputeSimilarityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeSimilarityRequest.Unmarshal(m, b)
}
func (m *ComputeSimilarityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeSimilarityRequest.Marshal(b, m, deterministic)
}
func (m *ComputeSimilarityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeSimilarityRequest.Merge(m, src)
}
func (m *ComputeSimilarityRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeSimilarityRequest.Size(m)
}
func (m *ComputeSimilarityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeSimilarityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeSimilarityRequest proto.InternalMessageInfo

type isComputeSimilarityRequest_EmbeddingSourceA interface {
	isComputeSimilarityRequest_EmbeddingSourceA()
}

type ComputeSimilarityRequest_TextA struct {
	TextA string `protobuf:"bytes,1,opt,name=text_a,json=textA,proto3,oneof"`
}

type ComputeSimilarityRequest_EmbeddingA struct {
	EmbeddingA *EmbeddingVector `protobuf:"bytes,2,opt,name=embedding_a,json=embeddingA,proto3,oneof"`
}

func (*ComputeSimilarityRequest_TextA) isComputeSimilarityRequest_EmbeddingSourceA() {}

func (*ComputeSimilarityRequest_EmbeddingA) isComputeSimilarityRequest_EmbeddingSourceA() {}

func (m *ComputeSimilarityRequest) GetEmbeddingSourceA() isComputeSimilarityRequest_EmbeddingSourceA {
	if m != nil {
		return m.EmbeddingSourceA
	}
	return nil
}

func (m *ComputeSimilarityRequest) GetTextA() string {
	if x, ok := m.GetEmbeddingSourceA().(*ComputeSimilarityRequest_TextA); ok {
		return x.TextA
	}
	return ""
}

func (m *ComputeSimilarityRequest) GetEmbeddingA() *EmbeddingVector {
	if x, ok := m.GetEmbeddingSourceA().(*ComputeSimilarityRequest_EmbeddingA); ok {
		return x.EmbeddingA
	}
	return nil
}

type isComputeSimilarityRequest_EmbeddingSourceB interface {
	isComputeSimilarityRequest_EmbeddingSourceB()
}

type ComputeSimilarityRequest_TextB struct {
	TextB string `protobuf:"bytes,3,opt,name=text_b,json=textB,proto3,oneof"`
}

type ComputeSimilarityRequest_EmbeddingB struct {
	EmbeddingB *EmbeddingVector `protobuf:"bytes,4,opt,name=embedding_b,json=embeddingB,proto3,oneof"`
}

func (*ComputeSimilarityRequest_TextB) isComputeSimilarityRequest_EmbeddingSourceB() {}

func (*ComputeSimilarityRequest_EmbeddingB) isComputeSimilarityRequest_EmbeddingSourceB() {}

func (m *ComputeSimilarityRequest) GetEmbeddingSourceB() isComputeSimilarityRequest_EmbeddingSourceB {
	if m != nil {
		return m.EmbeddingSourceB
	}
	return nil
}

func (m *ComputeSimilarityRequest) GetTextB() string {
	if x, ok := m.GetEmbeddingSourceB().(*ComputeSimilarityRequest_TextB); ok {
		return x.TextB
	}
	return ""
}

func (m *ComputeSimilarityRequest) GetEmbeddingB() *EmbeddingVector {
	if x, ok := m.GetEmbeddingSourceB().(*ComputeSimilarityRequest_EmbeddingB); ok {
		return x.EmbeddingB
	}
	return nil
}

func (m *ComputeSimilarityRequest) GetSimilarityMetric() string {
	if m != nil {
		return m.SimilarityMetric
	}
	return ""
}

func (m *ComputeSimilarityRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *ComputeSimilarityRequest) GetOptions() *EmbeddingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ComputeSimilarityRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ComputeSimilarityRequest_TextA)(nil),
		(*ComputeSimilarityRequest_EmbeddingA)(nil),
		(*ComputeSimilarityRequest_TextB)(nil),
		(*ComputeSimilarityRequest_EmbeddingB)(nil),
	}
}

type ComputeSimilarityResponse struct {
	SimilarityScore      float32             `protobuf:"fixed32,1,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	MetricUsed           string              `protobuf:"bytes,2,opt,name=metric_used,json=metricUsed,proto3" json:"metric_used,omitempty"`
	Metadata             *SimilarityMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ComputeSimilarityResponse) Reset()         { *m = ComputeSimilarityResponse{} }
func (m *ComputeSimilarityResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeSimilarityResponse) ProtoMessage()    {}
func (*ComputeSimilarityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{22}
}

func (m *ComputeSimilarityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeSimilarityResponse.Unmarshal(m, b)
}
func (m *ComputeSimilarityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeSimilarityResponse.Marshal(b, m, deterministic)
}
func (m *ComputeSimilarityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeSimilarityResponse.Merge(m, src)
}
func (m *ComputeSimilarityResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeSimilarityResponse.Size(m)
}
func (m *ComputeSimilarityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeSimilarityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeSimilarityResponse proto.InternalMessageInfo

func (m *ComputeSimilarityResponse) GetSimilarityScore() float32 {
	if m != nil {
		return m.SimilarityScore
	}
	return 0
}

func (m *ComputeSimilarityResponse) GetMetricUsed() string {
	if m != nil {
		return m.MetricUsed
	}
	return ""
}

func (m *ComputeSimilarityResponse) GetMetadata() *SimilarityMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SimilarityMetadata struct {
	Dimension            int32             `protobuf:"varint,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	EmbeddingsNormalized bool              `protobuf:"varint,2,opt,name=embeddings_normalized,json=embeddingsNormalized,proto3" json:"embeddings_normalized,omitempty"`
	ComputationTimeMs    int64             `protobuf:"varint,3,opt,name=computation_time_ms,json=computationTimeMs,proto3" json:"computation_time_ms,omitempty"`
	DebugInfo            map[string]string `protobuf:"bytes,4,rep,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimilarityMetadata) Reset()         { *m = SimilarityMetadata{} }
func (m *SimilarityMetadata) String() string { return proto.CompactTextString(m) }
func (*SimilarityMetadata) ProtoMessage()    {}
func (*SimilarityMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{23}
}

func (m *SimilarityMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarityMetadata.Unmarshal(m, b)
}
func (m *SimilarityMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarityMetadata.Marshal(b, m, deterministic)
}
func (m *SimilarityMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarityMetadata.Merge(m, src)
}
func (m *SimilarityMetadata) XXX_Size() int {
	return xxx_messageInfo_SimilarityMetadata.Size(m)
}
func (m *SimilarityMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarityMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarityMetadata proto.InternalMessageInfo

func (m *SimilarityMetadata) GetDimension() int32 {
	if m != nil {
		return m.Dimension
	}
	return 0
}

func (m *SimilarityMetadata) GetEmbeddingsNormalized() bool {
	if m != nil {
		return m.EmbeddingsNormalized
	}
	return false
}

func (m *SimilarityMetadata) GetComputationTimeMs() int64 {
	if m != nil {
		return m.ComputationTimeMs
	}
	return 0
}

func (m *SimilarityMetadata) GetDebugInfo() map[string]string {
	if m != nil {
		return m.DebugInfo
	}
	return nil
}

type ComputeBatchSimilarityRequest struct {
	Pairs                []*SimilarityPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	SimilarityMetric     string            `protobuf:"bytes,2,opt,name=similarity_metric,json=similarityMetric,proto3" json:"similarity_metric,omitempty"`
	ModelName            string            `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Options              *EmbeddingOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ComputeBatchSimilarityRequest) Reset()         { *m = ComputeBatchSimilarityRequest{} }
func (m *ComputeBatchSimilarityRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeBatchSimilarityRequest) ProtoMessage()    {}
func (*ComputeBatchSimilarityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{24}
}

func (m *ComputeBatchSimilarityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeBatchSimilarityRequest.Unmarshal(m, b)
}
func (m *ComputeBatchSimilarityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeBatchSimilarityRequest.Marshal(b, m, deterministic)
}
func (m *ComputeBatchSimilarityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeBatchSimilarityRequest.Merge(m, src)
}
func (m *ComputeBatchSimilarityRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeBatchSimilarityRequest.Size(m)
}
func (m *ComputeBatchSimilarityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeBatchSimilarityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeBatchSimilarityRequest proto.InternalMessageInfo

func (m *ComputeBatchSimilarityRequest) GetPairs() []*SimilarityPair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *ComputeBatchSimilarityRequest) GetSimilarityMetric() string {
	if m != nil {
		return m.SimilarityMetric
	}
	return ""
}

func (m *ComputeBatchSimilarityRequest) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *ComputeBatchSimilarityRequest) GetOptions() *EmbeddingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type SimilarityPair struct {
	// Types that are valid to be assigned to SourceA:
	//
	//	*SimilarityPair_TextA
	//	*SimilarityPair_EmbeddingA
	SourceA isSimilarityPair_SourceA `protobuf_oneof:"source_a"`
	// Types that are valid to be assigned to SourceB:
	//
	//	*SimilarityPair_TextB
	//	*SimilarityPair_EmbeddingB
	SourceB              isSimilarityPair_SourceB `protobuf_oneof:"source_b"`
	PairId               string                   `protobuf:"bytes,5,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SimilarityPair) Reset()         { *m = SimilarityPair{} }
func (m *SimilarityPair) String() string { return proto.CompactTextString(m) }
func (*SimilarityPair) ProtoMessage()    {}
func (*SimilarityPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{25}
}

func (m *SimilarityPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarityPair.Unmarshal(m, b)
}
func (m *SimilarityPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarityPair.Marshal(b, m, deterministic)
}
func (m *SimilarityPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarityPair.Merge(m, src)
}
func (m *SimilarityPair) XXX_Size() int {
	return xxx_messageInfo_SimilarityPair.Size(m)
}
func (m *SimilarityPair) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarityPair.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarityPair proto.InternalMessageInfo

type isSimilarityPair_SourceA interface {
	isSimilarityPair_SourceA()
}

type SimilarityPair_TextA struct {
	TextA string `protobuf:"bytes,1,opt,name=text_a,json=textA,proto3,oneof"`
}

type SimilarityPair_EmbeddingA struct {
	EmbeddingA *EmbeddingVector `protobuf:"bytes,2,opt,name=embedding_a,json=embeddingA,proto3,oneof"`
}

func (*SimilarityPair_TextA) isSimilarityPair_SourceA() {}

func (*SimilarityPair_EmbeddingA) isSimilarityPair_SourceA() {}

func (m *SimilarityPair) GetSourceA() isSimilarityPair_SourceA {
	if m != nil {
		return m.SourceA
	}
	return nil
}

func (m *SimilarityPair) GetTextA() string {
	if x, ok := m.GetSourceA().(*SimilarityPair_TextA); ok {
		return x.TextA
	}
	return ""
}

func (m *SimilarityPair) GetEmbeddingA() *EmbeddingVector {
	if x, ok := m.GetSourceA().(*SimilarityPair_EmbeddingA); ok {
		return x.EmbeddingA
	}
	return nil
}

type isSimilarityPair_SourceB interface {
	isSimilarityPair_SourceB()
}

type SimilarityPair_TextB struct {
	TextB string `protobuf:"bytes,3,opt,name=text_b,json=textB,proto3,oneof"`
}

type SimilarityPair_EmbeddingB struct {
	EmbeddingB *EmbeddingVector `protobuf:"bytes,4,opt,name=embedding_b,json=embeddingB,proto3,oneof"`
}

func (*SimilarityPair_TextB) isSimilarityPair_SourceB() {}

func (*SimilarityPair_EmbeddingB) isSimilarityPair_SourceB() {}

func (m *SimilarityPair) GetSourceB() isSimilarityPair_SourceB {
	if m != nil {
		return m.SourceB
	}
	return nil
}

func (m *SimilarityPair) GetTextB() string {
	if x, ok := m.GetSourceB().(*SimilarityPair_TextB); ok {
		return x.TextB
	}
	return ""
}

func (m *SimilarityPair) GetEmbeddingB() *EmbeddingVector {
	if x, ok := m.GetSourceB().(*SimilarityPair_EmbeddingB); ok {
		return x.EmbeddingB
	}
	return nil
}

func (m *SimilarityPair) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimilarityPair) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimilarityPair_TextA)(nil),
		(*SimilarityPair_EmbeddingA)(nil),
		(*SimilarityPair_TextB)(nil),
		(*SimilarityPair_EmbeddingB)(nil),
	}
}

type ComputeBatchSimilarityResponse struct {
	Results              []*SimilarityResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Metadata             *BatchSimilarityMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ComputeBatchSimilarityResponse) Reset()         { *m = ComputeBatchSimilarityResponse{} }
func (m *ComputeBatchSimilarityResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeBatchSimilarityResponse) ProtoMessage()    {}
func (*ComputeBatchSimilarityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{26}
}

func (m *ComputeBatchSimilarityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeBatchSimilarityResponse.Unmarshal(m, b)
}
func (m *ComputeBatchSimilarityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeBatchSimilarityResponse.Marshal(b, m, deterministic)
}
func (m *ComputeBatchSimilarityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeBatchSimilarityResponse.Merge(m, src)
}
func (m *ComputeBatchSimilarityResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeBatchSimilarityResponse.Size(m)
}
func (m *ComputeBatchSimilarityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeBatchSimilarityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeBatchSimilarityResponse proto.InternalMessageInfo

func (m *ComputeBatchSimilarityResponse) GetResults() []*SimilarityResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ComputeBatchSimilarityResponse) GetMetadata() *BatchSimilarityMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SimilarityResult struct {
	PairId               string              `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	SimilarityScore      float32             `protobuf:"fixed32,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Status               v1.ProcessingStatus `protobuf:"varint,3,opt,name=status,proto3,enum=api.common.v1.ProcessingStatus" json:"status,omitempty"`
	ErrorMessage         string              `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SimilarityResult) Reset()         { *m = SimilarityResult{} }
func (m *SimilarityResult) String() string { return proto.CompactTextString(m) }
func (*SimilarityResult) ProtoMessage()    {}
func (*SimilarityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{27}
}

func (m *SimilarityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarityResult.Unmarshal(m, b)
}
func (m *SimilarityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarityResult.Marshal(b, m, deterministic)
}
func (m *SimilarityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarityResult.Merge(m, src)
}
func (m *SimilarityResult) XXX_Size() int {
	return xxx_messageInfo_SimilarityResult.Size(m)
}
func (m *SimilarityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarityResult.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarityResult proto.InternalMessageInfo

func (m *SimilarityResult) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *SimilarityResult) GetSimilarityScore() float32 {
	if m != nil {
		return m.SimilarityScore
	}
	return 0
}

func (m *SimilarityResult) GetStatus() v1.ProcessingStatus {
	if m != nil {
		return m.Status
	}
	return v1.ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (m *SimilarityResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type BatchSimilarityMetadata struct {
	TotalPairs             int32    `protobuf:"varint,1,opt,name=total_pairs,json=totalPairs,proto3" json:"total_pairs,omitempty"`
	SuccessfulComputations int32    `protobuf:"varint,2,opt,name=successful_computations,json=successfulComputations,proto3" json:"successful_computations,omitempty"`
	FailedComputations     int32    `protobuf:"varint,3,opt,name=failed_computations,json=failedComputations,proto3" json:"failed_computations,omitempty"`
	MetricUsed             string   `protobuf:"bytes,4,opt,name=metric_used,json=metricUsed,proto3" json:"metric_used,omitempty"`
	TotalProcessingTimeMs  int64    `protobuf:"varint,5,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BatchSimilarityMetadata) Reset()         { *m = BatchSimilarityMetadata{} }
func (m *BatchSimilarityMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchSimilarityMetadata) ProtoMessage()    {}
func (*BatchSimilarityMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8af71335b5e9176, []int{28}
}

func (m *BatchSimilarityMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSimilarityMetadata.Unmarshal(m, b)
}
func (m *BatchSimilarityMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSimilarityMetadata.Marshal(b, m, deterministic)
}
func (m *BatchSimilarityMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSimilarityMetadata.Merge(m, src)
}
func (m *BatchSimilarityMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchSimilarityMetadata.Size(m)
}
func (m *BatchSimilarityMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSimilarityMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSimilarityMetadata proto.InternalMessageInfo

func (m *BatchSimilarityMetadata) GetTotalPairs() int32 {
	if m != nil {
		return m.TotalPairs
	}
	return 0
}

func (m *BatchSimilarityMetadata) GetSuccessfulComputations() int32 {
	if m != nil {
		return m.SuccessfulComputations
	}
	return 0
}

func (m *BatchSimilarityMetadata) GetFailedComputations() int32 {
	if m != nil {
		return m.FailedComputations
	}
	return 0
}

func (m *BatchSimilarityMetadata) GetMetricUsed() string {
	if m != nil {
		return m.MetricUsed
	}
	return ""
}

func (m *BatchSimilarityMetadata) GetTotalProcessingTimeMs() int64 {
	if m != nil {
		return m.TotalProcessingTimeMs
	}
	return 0
}

func init() {
	proto.RegisterType((*EmbeddingVector)(nil), "api.embedding.v1.EmbeddingVector")
	proto.RegisterType((*EmbedTextRequest)(nil), "api.embedding.v1.EmbedTextRequest")
	proto.RegisterType((*EmbeddingOptions)(nil), "api.embedding.v1.EmbeddingOptions")
	proto.RegisterMapType((map[string]string)(nil), "api.embedding.v1.EmbeddingOptions.ModelParametersEntry")
	proto.RegisterType((*EmbedTextResponse)(nil), "api.embedding.v1.EmbedTextResponse")
	proto.RegisterType((*EmbeddingMetadata)(nil), "api.embedding.v1.EmbeddingMetadata")
	proto.RegisterMapType((map[string]string)(nil), "api.embedding.v1.EmbeddingMetadata.ModelMetadataEntry")
	proto.RegisterType((*EmbedBatchRequest)(nil), "api.embedding.v1.EmbedBatchRequest")
	proto.RegisterType((*EmbedBatchResponse)(nil), "api.embedding.v1.EmbedBatchResponse")
	proto.RegisterType((*EmbeddingResult)(nil), "api.embedding.v1.EmbeddingResult")
	proto.RegisterType((*BatchEmbeddingMetadata)(nil), "api.embedding.v1.BatchEmbeddingMetadata")
	proto.RegisterType((*EmbedBatchAsyncRequest)(nil), "api.embedding.v1.EmbedBatchAsyncRequest")
	proto.RegisterType((*EmbedBatchAsyncResponse)(nil), "api.embedding.v1.EmbedBatchAsyncResponse")
	proto.RegisterType((*GetEmbeddingTaskStatusRequest)(nil), "api.embedding.v1.GetEmbeddingTaskStatusRequest")
	proto.RegisterType((*GetEmbeddingTaskStatusResponse)(nil), "api.embedding.v1.GetEmbeddingTaskStatusResponse")
	proto.RegisterType((*GetModelInfoRequest)(nil), "api.embedding.v1.GetModelInfoRequest")
	proto.RegisterType((*GetModelInfoResponse)(nil), "api.embedding.v1.GetModelInfoResponse")
	proto.RegisterType((*ListModelsRequest)(nil), "api.embedding.v1.ListModelsRequest")
	proto.RegisterType((*ListModelsResponse)(nil), "api.embedding.v1.ListModelsResponse")
	proto.RegisterType((*ModelInfo)(nil), "api.embedding.v1.ModelInfo")
	proto.RegisterType((*ModelCapabilities)(nil), "api.embedding.v1.ModelCapabilities")
	proto.RegisterType((*ModelPerformance)(nil), "api.embedding.v1.ModelPerformance")
	proto.RegisterMapType((map[string]float32)(nil), "api.embedding.v1.ModelPerformance.BenchmarkScoresEntry")
	proto.RegisterType((*ModelConfiguration)(nil), "api.embedding.v1.ModelConfiguration")
	proto.RegisterMapType((map[string]string)(nil), "api.embedding.v1.ModelConfiguration.DefaultParametersEntry")
	proto.RegisterType((*ComputeSimilarityRequest)(nil), "api.embedding.v1.ComputeSimilarityRequest")
	proto.RegisterType((*ComputeSimilarityResponse)(nil), "api.embedding.v1.ComputeSimilarityResponse")
	proto.RegisterType((*SimilarityMetadata)(nil), "api.embedding.v1.SimilarityMetadata")
	proto.RegisterMapType((map[string]string)(nil), "api.embedding.v1.SimilarityMetadata.DebugInfoEntry")
	proto.RegisterType((*ComputeBatchSimilarityRequest)(nil), "api.embedding.v1.ComputeBatchSimilarityRequest")
	proto.RegisterType((*SimilarityPair)(nil), "api.embedding.v1.SimilarityPair")
	proto.RegisterType((*ComputeBatchSimilarityResponse)(nil), "api.embedding.v1.ComputeBatchSimilarityResponse")
	proto.RegisterType((*SimilarityResult)(nil), "api.embedding.v1.SimilarityResult")
	proto.RegisterType((*BatchSimilarityMetadata)(nil), "api.embedding.v1.BatchSimilarityMetadata")
}

func init() {
	proto.RegisterFile("v1/embedding_svc.proto", fileDescriptor_c8af71335b5e9176)
}

var fileDescriptor_c8af71335b5e9176 = []byte{
	// 2588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0xcd, 0x73, 0x23, 0x47,
	0x15, 0xcf, 0xc8, 0x96, 0x64, 0x3d, 0x79, 0x6d, 0xb9, 0xd7, 0x6b, 0xcb, 0xda, 0x64, 0xd7, 0x3b,
	0x4b, 0x82, 0x9d, 0x10, 0x09, 0xdb, 0x55, 0x2c, 0xd9, 0xdd, 0xc0, 0x5a, 0xeb, 0xcd, 0xae, 0xa9,
	0x75, 0x70, 0x8d, 0xbd, 0x1c, 0xa8, 0x4a, 0xa9, 0x5a, 0x33, 0x6d, 0x79, 0xf0, 0x7c, 0x65, 0xba,
	0x47, 0xb1, 0x49, 0x85, 0xa2, 0x38, 0x00, 0x87, 0x14, 0x07, 0xb8, 0x73, 0xe3, 0x90, 0xe2, 0x40,
	0x15, 0xf0, 0x97, 0xc0, 0x8d, 0x0b, 0x17, 0x6e, 0x81, 0x43, 0x8a, 0x03, 0x55, 0x7b, 0x00, 0xaa,
	0x3f, 0xe6, 0x53, 0xb2, 0x6c, 0x1f, 0x52, 0x05, 0x37, 0xcd, 0xfb, 0xe8, 0x7e, 0xfd, 0xfa, 0xbd,
	0x5f, 0xbf, 0xf7, 0x04, 0x4b, 0xc3, 0x8d, 0x0e, 0x71, 0xfb, 0xc4, 0xb2, 0x6c, 0x6f, 0xd0, 0xa3,
	0x43, 0xb3, 0x1d, 0x84, 0x3e, 0xf3, 0x51, 0x03, 0x07, 0x76, 0x3b, 0x61, 0xb4, 0x87, 0x1b, 0xad,
	0x57, 0x07, 0xbe, 0x3f, 0x70, 0x48, 0x07, 0x07, 0x76, 0x07, 0x7b, 0x9e, 0xcf, 0x30, 0xb3, 0x7d,
	0x8f, 0x4a, 0xf9, 0xd6, 0x4d, 0xc5, 0x15, 0x5f, 0xfd, 0xe8, 0xa8, 0x43, 0xdc, 0x80, 0x9d, 0x29,
	0xe6, 0xed, 0x22, 0x93, 0xd9, 0x2e, 0xa1, 0x0c, 0xbb, 0x81, 0x12, 0x68, 0xf1, 0x45, 0x4d, 0xdf,
	0x75, 0x7d, 0xaf, 0x33, 0xdc, 0x50, 0xbf, 0xc6, 0xf3, 0x48, 0x18, 0xfa, 0x61, 0xbc, 0xeb, 0xf2,
	0x10, 0x3b, 0xb6, 0x85, 0x19, 0xe9, 0xc4, 0x3f, 0x24, 0x43, 0x5f, 0x87, 0xf9, 0x27, 0xb1, 0xf1,
	0xdf, 0x23, 0x26, 0xf3, 0x43, 0xb4, 0x04, 0x95, 0x21, 0x76, 0x22, 0x42, 0x9b, 0xda, 0xea, 0xd4,
	0x5a, 0xc9, 0x50, 0x5f, 0xfa, 0xa7, 0x1a, 0x34, 0x84, 0xec, 0x21, 0x39, 0x65, 0x06, 0xf9, 0x30,
	0x22, 0x94, 0xa1, 0x9b, 0x30, 0xcd, 0xc8, 0x29, 0x6b, 0x6a, 0xab, 0xda, 0x5a, 0xad, 0x5b, 0x7d,
	0xd9, 0x9d, 0x0e, 0x4b, 0x0d, 0xcd, 0x10, 0x44, 0xf4, 0x1a, 0x80, 0xeb, 0x5b, 0xc4, 0xe9, 0x79,
	0xd8, 0x25, 0xcd, 0x12, 0x17, 0x31, 0x6a, 0x82, 0xf2, 0x3e, 0x76, 0x09, 0x7a, 0x08, 0x55, 0x3f,
	0x10, 0xbe, 0x69, 0x4e, 0xad, 0x6a, 0x6b, 0xf5, 0x4d, 0xbd, 0x5d, 0x74, 0x66, 0x3b, 0x31, 0xee,
	0xbb, 0x52, 0xd2, 0x88, 0x55, 0xf4, 0xbf, 0x97, 0x94, 0x39, 0x19, 0x2e, 0x7a, 0x15, 0x6a, 0x9e,
	0x1f, 0xba, 0xd8, 0xb1, 0x7f, 0x48, 0x84, 0x4d, 0x33, 0x46, 0x4a, 0x40, 0xeb, 0xd0, 0x08, 0x7c,
	0xdf, 0x11, 0x17, 0xc8, 0x42, 0xcc, 0xc8, 0xe0, 0x4c, 0x59, 0x35, 0xaf, 0xe8, 0x07, 0x8a, 0x8c,
	0xd6, 0x01, 0x5c, 0x7c, 0xda, 0x73, 0x88, 0x37, 0x60, 0xc7, 0xc2, 0xbc, 0x72, 0x17, 0x5e, 0x76,
	0xab, 0xad, 0x72, 0xf3, 0xc7, 0x8f, 0xd6, 0x34, 0xa3, 0xe6, 0xe2, 0xd3, 0xe7, 0x82, 0x89, 0x5a,
	0x30, 0xc3, 0xc2, 0xc8, 0x33, 0x31, 0x23, 0xcd, 0x69, 0xb1, 0x65, 0xf2, 0x8d, 0x56, 0xa1, 0x6e,
	0x7b, 0x94, 0x85, 0x91, 0xc9, 0xed, 0x6b, 0x96, 0xc5, 0x66, 0x59, 0x12, 0xea, 0x43, 0x43, 0xfa,
	0x28, 0xc0, 0x21, 0x76, 0x09, 0x23, 0x21, 0x6d, 0x56, 0x56, 0xa7, 0xd6, 0xea, 0x9b, 0xf7, 0x2e,
	0xf6, 0x46, 0x7b, 0x8f, 0xab, 0xee, 0x27, 0x9a, 0x4f, 0x3c, 0x16, 0x9e, 0x19, 0xf3, 0x6e, 0x9e,
	0xda, 0xea, 0xc2, 0xe2, 0x38, 0x41, 0xd4, 0x80, 0xa9, 0x13, 0x72, 0x26, 0xef, 0xce, 0xe0, 0x3f,
	0xd1, 0x22, 0x94, 0xc5, 0x6d, 0x2b, 0xb7, 0xc8, 0x8f, 0xfb, 0xa5, 0x6f, 0x6a, 0xfa, 0xef, 0x34,
	0x58, 0xc8, 0xdc, 0x3e, 0x0d, 0x7c, 0x8f, 0x12, 0xee, 0xef, 0xc4, 0x40, 0x15, 0x2e, 0x29, 0x81,
	0x73, 0x2d, 0xdb, 0x25, 0x1e, 0xe5, 0x67, 0xe7, 0x2b, 0x96, 0x8d, 0x94, 0x90, 0x46, 0x47, 0x44,
	0x89, 0x25, 0x5c, 0x1c, 0x47, 0xc7, 0x0b, 0x4a, 0x2c, 0xf4, 0x6d, 0x98, 0x71, 0x09, 0xc3, 0x16,
	0x66, 0x58, 0xb8, 0xb5, 0xbe, 0x79, 0x77, 0x82, 0x43, 0xf6, 0x94, 0xa8, 0x91, 0x28, 0xe9, 0x9f,
	0x4e, 0x29, 0x8b, 0xb3, 0x7c, 0x74, 0x1b, 0xea, 0xcc, 0x3f, 0x21, 0x5e, 0xcf, 0xf4, 0x23, 0x4f,
	0xc6, 0x6d, 0xd9, 0x00, 0x41, 0x7a, 0xcc, 0x29, 0xe8, 0x6b, 0x80, 0x82, 0xd0, 0x37, 0x09, 0xa5,
	0x3c, 0x4e, 0x78, 0x02, 0xf6, 0x5c, 0x2a, 0xac, 0x9f, 0x32, 0x1a, 0x29, 0xe7, 0xd0, 0x76, 0xc9,
	0x1e, 0x45, 0x77, 0xe1, 0xda, 0x47, 0x98, 0xf6, 0xe2, 0x0b, 0x97, 0xe7, 0x98, 0x31, 0x66, 0x3f,
	0xc2, 0xf4, 0x30, 0xa6, 0xa1, 0xaf, 0xc2, 0x3c, 0xf1, 0x4c, 0x5f, 0x20, 0xc7, 0x11, 0x8f, 0x46,
	0x26, 0x4e, 0x54, 0x33, 0xe6, 0x62, 0xf2, 0x7b, 0x82, 0x8a, 0x3e, 0x80, 0x39, 0xe9, 0x92, 0xe4,
	0xe4, 0x65, 0x11, 0x0a, 0xdf, 0xb8, 0xc4, 0xc9, 0x65, 0x2c, 0xc4, 0x5f, 0x32, 0x12, 0xae, 0xb9,
	0x59, 0x1a, 0x7a, 0x07, 0xc0, 0x0c, 0x09, 0x37, 0xa9, 0x87, 0x59, 0xb3, 0x22, 0x9c, 0xda, 0x6a,
	0x4b, 0xcc, 0x69, 0xc7, 0x98, 0xd3, 0x3e, 0x8c, 0x31, 0xc7, 0xa8, 0x29, 0xe9, 0x6d, 0xd6, 0x7a,
	0x04, 0x68, 0x74, 0xfd, 0x2b, 0x05, 0xd0, 0x6f, 0xe3, 0x00, 0xea, 0x62, 0x66, 0x1e, 0xc7, 0xf8,
	0x71, 0x0b, 0xca, 0x1c, 0x2a, 0x24, 0xd6, 0xd4, 0xba, 0x33, 0x2f, 0xbb, 0xe5, 0x5f, 0x6a, 0xa5,
	0x19, 0xcd, 0x90, 0xe4, 0x2f, 0x15, 0x42, 0xd0, 0x0a, 0xcc, 0xf4, 0xb9, 0x31, 0x3d, 0xdb, 0x52,
	0x17, 0x52, 0x15, 0xdf, 0xbb, 0x96, 0xfe, 0x7b, 0x0d, 0x50, 0xd6, 0x5a, 0x15, 0xef, 0x59, 0x0d,
	0x2d, 0xa7, 0x81, 0x1e, 0x40, 0x35, 0x24, 0x34, 0x72, 0x18, 0x0f, 0x16, 0x7e, 0x69, 0x77, 0x26,
	0x98, 0x62, 0x08, 0x49, 0x23, 0xd6, 0x40, 0x3b, 0x99, 0x60, 0x97, 0x07, 0x59, 0x1b, 0xd5, 0x16,
	0xa6, 0x4c, 0x8a, 0xf8, 0x7f, 0x69, 0x19, 0x34, 0x97, 0x5b, 0xf0, 0x0b, 0xb1, 0x3d, 0x8b, 0x9c,
	0xaa, 0x48, 0x97, 0x1f, 0xf9, 0xbc, 0x2d, 0x15, 0xf3, 0xf6, 0x1e, 0x54, 0x28, 0xc3, 0x2c, 0x92,
	0x4e, 0x9d, 0xdb, 0xbc, 0x2d, 0x6c, 0x51, 0x8f, 0xcd, 0x70, 0xa3, 0xbd, 0x9f, 0x64, 0xc1, 0x81,
	0x10, 0x33, 0x94, 0x38, 0xcf, 0x06, 0xf1, 0xec, 0xf4, 0x5c, 0x42, 0x29, 0x1e, 0x10, 0xe5, 0xd5,
	0x59, 0x41, 0xdc, 0x93, 0x34, 0x64, 0x00, 0x4a, 0x1f, 0xd2, 0x4c, 0xa0, 0x5f, 0x3a, 0xc5, 0x17,
	0x48, 0x91, 0xa4, 0xff, 0xa3, 0x04, 0x4b, 0xe3, 0xdd, 0x23, 0x13, 0x9e, 0x61, 0xa7, 0x17, 0xc7,
	0x99, 0x4a, 0x78, 0x86, 0x9d, 0x43, 0x11, 0x62, 0x5b, 0x70, 0x83, 0x46, 0x26, 0x3f, 0xd0, 0x51,
	0xe4, 0xf4, 0x92, 0xb5, 0xa9, 0x42, 0xac, 0xc5, 0x94, 0x99, 0x2c, 0x4e, 0xd1, 0x5b, 0xb0, 0x70,
	0x84, 0x6d, 0x87, 0x58, 0x59, 0x05, 0xf1, 0x4c, 0x18, 0x0d, 0xc9, 0xc8, 0x08, 0xdf, 0x83, 0xa6,
	0x34, 0x61, 0x0c, 0xb0, 0x4c, 0x0b, 0x60, 0xb9, 0x21, 0xf8, 0xfb, 0x45, 0x74, 0xc9, 0x43, 0x64,
	0xb9, 0x08, 0x91, 0xef, 0x00, 0x50, 0x86, 0xc3, 0xcb, 0xe7, 0xb3, 0x92, 0xde, 0x66, 0xe8, 0x5d,
	0x98, 0x35, 0x7d, 0x37, 0x70, 0x88, 0x52, 0xae, 0x5e, 0xa8, 0x5c, 0x4f, 0xe4, 0xb7, 0x99, 0xfe,
	0x57, 0x0d, 0x96, 0xd2, 0xf4, 0xd8, 0xa6, 0x67, 0x9e, 0xf9, 0x3f, 0x91, 0xd1, 0x77, 0x60, 0xd6,
	0xc4, 0x8e, 0xd3, 0xc7, 0xe6, 0x49, 0x2f, 0x0a, 0x1d, 0x15, 0x7f, 0xf5, 0x98, 0xf6, 0x22, 0x74,
	0xd0, 0xeb, 0x30, 0x13, 0x84, 0xb6, 0x1f, 0xda, 0xec, 0x4c, 0x78, 0xb4, 0xdc, 0xad, 0xbd, 0xec,
	0x56, 0x5a, 0xd3, 0x4d, 0x58, 0xd3, 0x8c, 0x84, 0xa5, 0x7f, 0xa1, 0xc1, 0xf2, 0xc8, 0x09, 0x15,
	0x0a, 0x2c, 0x43, 0x95, 0x61, 0x7a, 0x92, 0x82, 0x40, 0x85, 0x7f, 0xee, 0x5a, 0x99, 0xc4, 0x29,
	0x5d, 0x2d, 0x71, 0x76, 0xe1, 0x0e, 0xa1, 0xcc, 0x76, 0x05, 0x36, 0x17, 0xa3, 0x84, 0x12, 0xd3,
	0xf7, 0xac, 0x38, 0xbc, 0x6e, 0x25, 0x82, 0xf9, 0x70, 0x39, 0x90, 0x52, 0x05, 0x90, 0x9f, 0xbe,
	0x02, 0xc8, 0xeb, 0xdb, 0xf0, 0xda, 0x53, 0xc2, 0x12, 0xef, 0x1e, 0x62, 0x7a, 0xa2, 0xec, 0x54,
	0x77, 0xbb, 0x5a, 0x38, 0x78, 0x5a, 0xf0, 0x29, 0x0f, 0xe8, 0x7f, 0xd0, 0xe0, 0xd6, 0x79, 0x6b,
	0x5c, 0xe4, 0xbd, 0xfb, 0x50, 0x17, 0x8c, 0x8c, 0x0b, 0xeb, 0x9b, 0x2b, 0x05, 0x17, 0x66, 0x16,
	0x04, 0x96, 0xfc, 0x46, 0x0f, 0xa1, 0x22, 0xb1, 0x54, 0x45, 0xcd, 0x57, 0xce, 0x89, 0x9a, 0x1c,
	0x9c, 0x1b, 0x4a, 0x47, 0x7f, 0x17, 0xae, 0x3f, 0x25, 0x4c, 0x3c, 0x70, 0xbb, 0xde, 0x91, 0x1f,
	0x1f, 0xf7, 0x8d, 0x5c, 0xa8, 0x16, 0x4e, 0x9c, 0xc6, 0xac, 0x6e, 0xc0, 0x62, 0x5e, 0x5d, 0x9d,
	0xf4, 0x7e, 0xac, 0x6f, 0x7b, 0x47, 0xbe, 0xd0, 0xaf, 0x6f, 0xde, 0x1c, 0x35, 0x2c, 0x55, 0x94,
	0x6b, 0xf2, 0x9f, 0xfa, 0x4f, 0x35, 0x58, 0x78, 0x6e, 0x53, 0xb9, 0x6a, 0x72, 0x01, 0x8f, 0x00,
	0x02, 0x3c, 0xb0, 0x3d, 0xd1, 0x52, 0xa8, 0x15, 0x57, 0x8b, 0x41, 0x96, 0x08, 0x28, 0x2d, 0x23,
	0xa3, 0x83, 0x3a, 0x50, 0x3d, 0xb2, 0x1d, 0x51, 0x66, 0xca, 0x67, 0xea, 0x46, 0x41, 0xfd, 0x3d,
	0xc1, 0x35, 0x62, 0x29, 0x5e, 0xf6, 0xa3, 0xac, 0x21, 0xea, 0x6c, 0x5b, 0x50, 0x11, 0xc6, 0xca,
	0x3c, 0xbf, 0xe0, 0x5c, 0x4a, 0x14, 0x6d, 0xe7, 0xcc, 0x97, 0x17, 0x7c, 0x67, 0x82, 0xf9, 0xea,
	0x9a, 0x32, 0x4a, 0xfa, 0x17, 0xd3, 0x50, 0x4b, 0x16, 0x46, 0x08, 0xa6, 0xd3, 0xbb, 0x31, 0xc4,
	0x6f, 0x8e, 0x01, 0x96, 0x4d, 0x03, 0x07, 0x9f, 0x65, 0x21, 0xa6, 0xae, 0x68, 0x02, 0x64, 0x56,
	0xa1, 0x6e, 0x11, 0x6a, 0x86, 0xb6, 0x80, 0x0d, 0x55, 0x7b, 0x66, 0x49, 0xa8, 0x09, 0xd5, 0x21,
	0x09, 0x45, 0xe1, 0xaa, 0x2a, 0x03, 0xf5, 0x99, 0x2f, 0x6a, 0xcb, 0xc5, 0xa2, 0xb6, 0x0d, 0xd7,
	0x79, 0xdf, 0x40, 0xb9, 0xe7, 0x3d, 0x93, 0xc4, 0x0d, 0x44, 0x45, 0xc8, 0x2d, 0xb8, 0xf8, 0xf4,
	0x40, 0x71, 0x54, 0xf3, 0xd0, 0x81, 0xeb, 0x34, 0x0a, 0x02, 0x5f, 0x80, 0xb8, 0x83, 0xbd, 0x41,
	0x84, 0x07, 0x84, 0x36, 0xab, 0x1c, 0x3b, 0x0d, 0x94, 0xb0, 0x9e, 0xc7, 0x1c, 0xf4, 0x94, 0x23,
	0x5c, 0x80, 0xfb, 0xb6, 0x63, 0x33, 0x9b, 0xd0, 0xe6, 0xcc, 0x79, 0xef, 0xa6, 0x70, 0xd2, 0xe3,
	0x8c, 0xa8, 0x91, 0x53, 0x44, 0x3b, 0x50, 0x0f, 0x48, 0x28, 0xca, 0x51, 0xcf, 0x24, 0xcd, 0xda,
	0x79, 0x60, 0x2b, 0x3b, 0x87, 0x54, 0xd2, 0xc8, 0xaa, 0xa1, 0xef, 0xc0, 0x35, 0xd3, 0xf7, 0x8e,
	0xec, 0x41, 0x14, 0xca, 0x4b, 0x85, 0xf3, 0xd2, 0x4f, 0xda, 0x93, 0x95, 0x35, 0xf2, 0xaa, 0xfc,
	0xe2, 0x6c, 0xda, 0xc3, 0x43, 0x6c, 0x3b, 0xb8, 0xef, 0x90, 0x66, 0x5d, 0x94, 0xd2, 0x75, 0x9b,
	0x6e, 0xc7, 0xa4, 0x02, 0xb8, 0xcd, 0x5e, 0x01, 0xdc, 0xb8, 0x6a, 0x14, 0x58, 0xb1, 0xea, 0xb5,
	0x8b, 0x55, 0x95, 0xf4, 0x36, 0xd3, 0xff, 0x52, 0x82, 0x85, 0x11, 0x77, 0xa2, 0x0d, 0x58, 0x54,
	0xf7, 0x43, 0x7b, 0xd9, 0x26, 0x4f, 0xb6, 0x9d, 0xf1, 0xb5, 0xd2, 0xdd, 0x4c, 0xb3, 0xf7, 0x2d,
	0xb8, 0x99, 0xa8, 0xb8, 0x91, 0xc3, 0xec, 0xc0, 0x21, 0x99, 0x5b, 0x2f, 0x09, 0xcd, 0x95, 0x58,
	0x64, 0x4f, 0x49, 0xa4, 0x97, 0xff, 0x10, 0x5a, 0x89, 0xbe, 0xe5, 0xbb, 0xd8, 0xf6, 0x7a, 0xd8,
	0xc2, 0x81, 0x9c, 0x30, 0xa8, 0xd6, 0xa3, 0x19, 0x4b, 0xec, 0x08, 0x81, 0xed, 0x84, 0x8f, 0xde,
	0x06, 0x54, 0x68, 0x7f, 0x79, 0x00, 0x4d, 0x8b, 0x50, 0x5b, 0xc8, 0x37, 0xc0, 0xfc, 0x7c, 0xeb,
	0xd0, 0x28, 0x74, 0x2d, 0x54, 0xb4, 0x23, 0x35, 0x63, 0x3e, 0xdf, 0xb6, 0x50, 0x74, 0x1f, 0x12,
	0xa3, 0x7b, 0xb2, 0x3e, 0x4e, 0xdf, 0x30, 0x11, 0xfb, 0x33, 0xc6, 0x72, 0x2c, 0x20, 0x10, 0x38,
	0x7d, 0xba, 0xf4, 0x3f, 0x95, 0xa0, 0x51, 0x8c, 0x31, 0xb4, 0x05, 0x4b, 0x78, 0x38, 0x18, 0x57,
	0x2f, 0x71, 0xef, 0x96, 0x8c, 0xeb, 0x78, 0x38, 0x18, 0xa9, 0x96, 0xde, 0x81, 0x15, 0x9e, 0x7b,
	0xec, 0x38, 0xf4, 0xa3, 0xc1, 0x71, 0x10, 0xb1, 0x5e, 0x40, 0x42, 0xf5, 0x7a, 0xaa, 0x62, 0x6e,
	0xc9, 0xc5, 0xa7, 0x87, 0x09, 0x7f, 0x9f, 0x84, 0xf2, 0xd5, 0x44, 0x6f, 0xc0, 0xbc, 0x4b, 0x5c,
	0x3f, 0x3c, 0xeb, 0x45, 0xbc, 0x46, 0xed, 0xb9, 0x7d, 0xe1, 0xcd, 0x29, 0xe3, 0x9a, 0x24, 0xbf,
	0xe0, 0xd4, 0xbd, 0x3e, 0xef, 0xd6, 0xfb, 0xc4, 0x33, 0x8f, 0x5d, 0x1c, 0x9e, 0xf4, 0xa8, 0xe9,
	0x87, 0xca, 0x81, 0x63, 0xbb, 0xf5, 0xe2, 0xa9, 0xda, 0xdd, 0x58, 0xf5, 0x40, 0x68, 0xaa, 0x6e,
	0xbd, 0x9f, 0xa7, 0xf2, 0x6e, 0x7d, 0x9c, 0xe0, 0x45, 0xcd, 0x56, 0x29, 0xdb, 0x6c, 0x7d, 0x5e,
	0x52, 0xfd, 0x5a, 0x2e, 0xe1, 0xd2, 0xda, 0x8b, 0x9d, 0x05, 0x31, 0x68, 0xca, 0x37, 0xe7, 0xf0,
	0x2c, 0x20, 0x48, 0x87, 0x59, 0x1c, 0x9a, 0xc7, 0x36, 0x23, 0x26, 0x8b, 0xc2, 0x18, 0x39, 0x73,
	0x34, 0xf4, 0x03, 0x40, 0x16, 0x39, 0xc2, 0x91, 0xc3, 0xb2, 0x13, 0x8b, 0x29, 0xe1, 0x83, 0x07,
	0x97, 0xc9, 0xfa, 0xf6, 0x8e, 0x54, 0x2f, 0x4e, 0x2d, 0x16, 0xac, 0x22, 0x9d, 0x83, 0x63, 0x48,
	0x3e, 0x8c, 0xec, 0x90, 0x17, 0x45, 0xe9, 0x66, 0x32, 0x62, 0x51, 0xcc, 0xca, 0x2b, 0xc8, 0x4a,
	0x10, 0xe7, 0xe6, 0x29, 0x32, 0x6a, 0x51, 0xcc, 0xca, 0x4c, 0x46, 0x76, 0x60, 0x69, 0xbc, 0x39,
	0x57, 0x6a, 0x6d, 0x7f, 0x31, 0x05, 0xcd, 0xc7, 0xbe, 0x1b, 0x44, 0x8c, 0x1c, 0xd8, 0xae, 0xed,
	0x60, 0x5e, 0x41, 0xc6, 0x4f, 0xf6, 0x32, 0x54, 0x78, 0xe1, 0xdb, 0xc3, 0x72, 0xad, 0x67, 0xaf,
	0xc8, 0x42, 0x78, 0x9b, 0x03, 0x70, 0xda, 0x07, 0xe1, 0xdc, 0x6b, 0x38, 0xbe, 0xda, 0x95, 0xf3,
	0xb9, 0x67, 0xaf, 0x18, 0x90, 0xf0, 0xb7, 0x93, 0xe5, 0x65, 0xc0, 0xd6, 0x9e, 0xa9, 0x3a, 0xbb,
	0x9b, 0x5f, 0xbe, 0xaf, 0x0a, 0xc1, 0x4b, 0x2c, 0xaf, 0x65, 0x96, 0xef, 0xf2, 0x3e, 0x87, 0x26,
	0x47, 0xe2, 0xdd, 0x5a, 0x68, 0x9b, 0xaa, 0x11, 0x69, 0xa4, 0x8c, 0x3d, 0x41, 0x2f, 0x94, 0xf6,
	0x95, 0x09, 0xa5, 0x7d, 0xf5, 0xca, 0xa5, 0x7d, 0x77, 0x31, 0xdb, 0x36, 0x52, 0x3f, 0x0a, 0x4d,
	0xd2, 0xc3, 0x63, 0xa9, 0x7d, 0xfd, 0x33, 0x0d, 0x56, 0xc6, 0x5c, 0x88, 0x2a, 0x5d, 0xd6, 0x21,
	0x63, 0xba, 0xcc, 0x62, 0x05, 0x2b, 0xf3, 0x29, 0x5d, 0x64, 0x1e, 0x6f, 0x1e, 0xe5, 0x99, 0x65,
	0x07, 0x26, 0x6f, 0x1e, 0x24, 0x49, 0xb4, 0x60, 0x8f, 0x46, 0x1a, 0xf7, 0x31, 0x4f, 0xdf, 0x41,
	0xd6, 0x51, 0xc5, 0xa6, 0xfd, 0xb3, 0x12, 0xa0, 0x51, 0x81, 0x7c, 0x99, 0xa1, 0x15, 0xcb, 0x8c,
	0x2d, 0xb8, 0x91, 0xf6, 0x9d, 0xbd, 0x64, 0xc2, 0x69, 0xa9, 0x27, 0x64, 0x31, 0x65, 0xbe, 0x9f,
	0xf0, 0x78, 0x6d, 0x62, 0x0a, 0xa7, 0x88, 0x3c, 0x4c, 0x10, 0x55, 0x02, 0xdd, 0x42, 0x86, 0xa5,
	0xf0, 0xd4, 0x00, 0xb0, 0x48, 0x3f, 0x1a, 0xc8, 0xf2, 0x55, 0xc2, 0xdc, 0xd6, 0x65, 0x4e, 0xd7,
	0xde, 0xe1, 0x6a, 0xbc, 0x40, 0x93, 0xa9, 0x5d, 0xb3, 0xe2, 0xef, 0xd6, 0x43, 0x98, 0xcb, 0x33,
	0xaf, 0x94, 0x68, 0x9f, 0x6b, 0xf0, 0x9a, 0xba, 0x57, 0xf1, 0x8c, 0x8c, 0x66, 0xdb, 0x23, 0x28,
	0x07, 0xd8, 0x0e, 0xe3, 0xaa, 0x74, 0x75, 0x92, 0xb9, 0xfb, 0xd8, 0x0e, 0xb3, 0xfd, 0xa9, 0x50,
	0x1c, 0x1f, 0xf1, 0xa5, 0x4b, 0x45, 0xfc, 0xd4, 0x84, 0x88, 0x9f, 0xbe, 0xfa, 0x84, 0xfb, 0x3f,
	0x1a, 0xcc, 0xe5, 0xad, 0xfd, 0x3f, 0x07, 0x93, 0x65, 0xa8, 0x72, 0x1f, 0xf3, 0xce, 0x4f, 0x42,
	0x48, 0x85, 0x7f, 0xee, 0x5a, 0x5d, 0x80, 0x99, 0x24, 0xa3, 0xd3, 0xdf, 0x7d, 0xfd, 0x37, 0x1a,
	0xdc, 0x3a, 0xef, 0xbe, 0x55, 0x32, 0x3f, 0x4c, 0xc7, 0x6e, 0xf2, 0xca, 0xf5, 0x49, 0x57, 0x5e,
	0x9c, 0xbb, 0x3d, 0xc9, 0xa4, 0xaf, 0xf4, 0xd9, 0xfa, 0x39, 0x73, 0xb7, 0x89, 0x39, 0xfc, 0x47,
	0x0d, 0x1a, 0xc5, 0x4d, 0xb2, 0xa7, 0xd5, 0xb2, 0xa7, 0x1d, 0x8b, 0x3f, 0xa5, 0xf1, 0xf8, 0xf3,
	0xa5, 0x4e, 0xe2, 0xf4, 0x7f, 0x6b, 0xb0, 0x7c, 0xce, 0xe1, 0xd2, 0xb1, 0x59, 0x9c, 0x4e, 0xe9,
	0xd8, 0x6c, 0x5f, 0xe4, 0xc9, 0x3d, 0x58, 0xce, 0x8c, 0xcd, 0x32, 0xe8, 0x11, 0x0f, 0xce, 0x96,
	0x52, 0xf6, 0xe3, 0x0c, 0x97, 0x3f, 0xd2, 0x6a, 0x74, 0x96, 0x53, 0x92, 0xd3, 0x0d, 0x24, 0x59,
	0x39, 0x85, 0x02, 0x08, 0x4f, 0x8f, 0x80, 0xf0, 0xa4, 0xf9, 0x5a, 0x79, 0xc2, 0x7c, 0x6d, 0xf3,
	0x9f, 0x55, 0xa8, 0x25, 0x21, 0x8b, 0x7c, 0xf5, 0x71, 0x48, 0x4e, 0x19, 0x3a, 0x2f, 0x53, 0x33,
	0x7f, 0x7e, 0xb5, 0xee, 0x4e, 0x94, 0x91, 0x01, 0xaa, 0xaf, 0xfc, 0xe4, 0xcf, 0x7f, 0xfb, 0x55,
	0xe9, 0xba, 0x3e, 0xd7, 0x89, 0xff, 0x41, 0xec, 0xf0, 0x9c, 0xba, 0xaf, 0xbd, 0x89, 0x28, 0x40,
	0x3a, 0x94, 0x40, 0x77, 0x27, 0x8f, 0x2c, 0xe4, 0x96, 0x97, 0x9a, 0x6b, 0xe8, 0x2d, 0xb1, 0xe7,
	0xa2, 0x3e, 0x9f, 0xee, 0x29, 0xca, 0x72, 0xbe, 0xe9, 0xcf, 0xe3, 0x21, 0x71, 0x3a, 0xd8, 0x42,
	0x6b, 0x93, 0x56, 0xcd, 0x4e, 0xf7, 0x5a, 0xeb, 0x97, 0x90, 0x54, 0x46, 0xac, 0x0a, 0x23, 0x5a,
	0xfa, 0x8d, 0x82, 0x11, 0x6f, 0x63, 0x2e, 0xc6, 0x4d, 0xf9, 0xb5, 0x06, 0x4b, 0xe3, 0x87, 0x45,
	0xa8, 0x33, 0xba, 0xcf, 0xc4, 0xd1, 0x54, 0xeb, 0xeb, 0x97, 0x57, 0x50, 0xf6, 0xdd, 0x11, 0xf6,
	0xdd, 0x44, 0x2b, 0x99, 0x8b, 0xc1, 0xf4, 0x84, 0x76, 0x3e, 0x56, 0xe3, 0xa9, 0x4f, 0xd0, 0x8f,
	0x60, 0x36, 0x3b, 0xd8, 0x41, 0xaf, 0x8f, 0xdd, 0xa4, 0x38, 0x37, 0x6a, 0xbd, 0x71, 0x91, 0x98,
	0xb2, 0xe0, 0xb6, 0xb0, 0x60, 0x05, 0x2d, 0x73, 0x0b, 0xe4, 0x88, 0xa4, 0xf3, 0x71, 0xfa, 0x9e,
	0x7c, 0x82, 0x4e, 0x00, 0xd2, 0xd1, 0xcb, 0xb8, 0x00, 0x19, 0x99, 0x10, 0x8d, 0x0b, 0x90, 0xd1,
	0xe9, 0x8d, 0x8e, 0xc4, 0xce, 0xb3, 0x08, 0xd2, 0x9d, 0xd1, 0xcf, 0x34, 0x58, 0x18, 0x29, 0x9a,
	0xd0, 0x9b, 0xa3, 0xeb, 0x9d, 0x57, 0xea, 0xb6, 0xde, 0xba, 0x94, 0xec, 0xb8, 0xbc, 0x48, 0x71,
	0x8f, 0xc7, 0xc5, 0x07, 0x50, 0x7f, 0x46, 0xb0, 0xc3, 0x8e, 0x1f, 0x1f, 0x13, 0xf3, 0x04, 0x2d,
	0x8d, 0x74, 0xe9, 0x4f, 0xdc, 0x80, 0x9d, 0xb5, 0xf4, 0x02, 0x18, 0x66, 0x74, 0xc6, 0x1f, 0xf4,
	0x58, 0x08, 0x74, 0xdf, 0x86, 0x91, 0x3f, 0xed, 0xf7, 0xb5, 0xef, 0x2f, 0x87, 0x78, 0x20, 0xfe,
	0xb3, 0x4f, 0xe8, 0x9d, 0xe1, 0xc6, 0x83, 0xe1, 0x46, 0xbf, 0x22, 0xb6, 0xdd, 0xfa, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x18, 0x7b, 0x3e, 0x4e, 0x02, 0x20, 0x00, 0x00,
}
