// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/conf/conf.proto

package conf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bootstrap struct {
	Server               *Server  `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bootstrap) Reset()         { *m = Bootstrap{} }
func (m *Bootstrap) String() string { return proto.CompactTextString(m) }
func (*Bootstrap) ProtoMessage()    {}
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{0}
}

func (m *Bootstrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bootstrap.Unmarshal(m, b)
}
func (m *Bootstrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bootstrap.Marshal(b, m, deterministic)
}
func (m *Bootstrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bootstrap.Merge(m, src)
}
func (m *Bootstrap) XXX_Size() int {
	return xxx_messageInfo_Bootstrap.Size(m)
}
func (m *Bootstrap) XXX_DiscardUnknown() {
	xxx_messageInfo_Bootstrap.DiscardUnknown(m)
}

var xxx_messageInfo_Bootstrap proto.InternalMessageInfo

func (m *Bootstrap) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *Bootstrap) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Server struct {
	Http                 *Server_HTTP `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc                 *Server_GRPC `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{1}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetHttp() *Server_HTTP {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *Server) GetGrpc() *Server_GRPC {
	if m != nil {
		return m.Grpc
	}
	return nil
}

type Server_HTTP struct {
	Network              string               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout              *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Server_HTTP) Reset()         { *m = Server_HTTP{} }
func (m *Server_HTTP) String() string { return proto.CompactTextString(m) }
func (*Server_HTTP) ProtoMessage()    {}
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{1, 0}
}

func (m *Server_HTTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_HTTP.Unmarshal(m, b)
}
func (m *Server_HTTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_HTTP.Marshal(b, m, deterministic)
}
func (m *Server_HTTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_HTTP.Merge(m, src)
}
func (m *Server_HTTP) XXX_Size() int {
	return xxx_messageInfo_Server_HTTP.Size(m)
}
func (m *Server_HTTP) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_HTTP.DiscardUnknown(m)
}

var xxx_messageInfo_Server_HTTP proto.InternalMessageInfo

func (m *Server_HTTP) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Server_HTTP) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Server_HTTP) GetTimeout() *durationpb.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type Server_GRPC struct {
	Network              string               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout              *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Server_GRPC) Reset()         { *m = Server_GRPC{} }
func (m *Server_GRPC) String() string { return proto.CompactTextString(m) }
func (*Server_GRPC) ProtoMessage()    {}
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{1, 1}
}

func (m *Server_GRPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server_GRPC.Unmarshal(m, b)
}
func (m *Server_GRPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server_GRPC.Marshal(b, m, deterministic)
}
func (m *Server_GRPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server_GRPC.Merge(m, src)
}
func (m *Server_GRPC) XXX_Size() int {
	return xxx_messageInfo_Server_GRPC.Size(m)
}
func (m *Server_GRPC) XXX_DiscardUnknown() {
	xxx_messageInfo_Server_GRPC.DiscardUnknown(m)
}

var xxx_messageInfo_Server_GRPC proto.InternalMessageInfo

func (m *Server_GRPC) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Server_GRPC) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Server_GRPC) GetTimeout() *durationpb.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type Data struct {
	Database             *Data_Database `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis                *Data_Redis    `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetDatabase() *Data_Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *Data) GetRedis() *Data_Redis {
	if m != nil {
		return m.Redis
	}
	return nil
}

type Data_Database struct {
	Driver               string   `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data_Database) Reset()         { *m = Data_Database{} }
func (m *Data_Database) String() string { return proto.CompactTextString(m) }
func (*Data_Database) ProtoMessage()    {}
func (*Data_Database) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{2, 0}
}

func (m *Data_Database) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data_Database.Unmarshal(m, b)
}
func (m *Data_Database) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data_Database.Marshal(b, m, deterministic)
}
func (m *Data_Database) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data_Database.Merge(m, src)
}
func (m *Data_Database) XXX_Size() int {
	return xxx_messageInfo_Data_Database.Size(m)
}
func (m *Data_Database) XXX_DiscardUnknown() {
	xxx_messageInfo_Data_Database.DiscardUnknown(m)
}

var xxx_messageInfo_Data_Database proto.InternalMessageInfo

func (m *Data_Database) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Data_Database) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Data_Redis struct {
	Network              string               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout          *durationpb.Duration `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout         *durationpb.Duration `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Data_Redis) Reset()         { *m = Data_Redis{} }
func (m *Data_Redis) String() string { return proto.CompactTextString(m) }
func (*Data_Redis) ProtoMessage()    {}
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c69a7f648509b54, []int{2, 1}
}

func (m *Data_Redis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data_Redis.Unmarshal(m, b)
}
func (m *Data_Redis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data_Redis.Marshal(b, m, deterministic)
}
func (m *Data_Redis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data_Redis.Merge(m, src)
}
func (m *Data_Redis) XXX_Size() int {
	return xxx_messageInfo_Data_Redis.Size(m)
}
func (m *Data_Redis) XXX_DiscardUnknown() {
	xxx_messageInfo_Data_Redis.DiscardUnknown(m)
}

var xxx_messageInfo_Data_Redis proto.InternalMessageInfo

func (m *Data_Redis) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Data_Redis) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if m != nil {
		return m.ReadTimeout
	}
	return nil
}

func (m *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if m != nil {
		return m.WriteTimeout
	}
	return nil
}

func init() {
	proto.RegisterType((*Bootstrap)(nil), "kratos.api.Bootstrap")
	proto.RegisterType((*Server)(nil), "kratos.api.Server")
	proto.RegisterType((*Server_HTTP)(nil), "kratos.api.Server.HTTP")
	proto.RegisterType((*Server_GRPC)(nil), "kratos.api.Server.GRPC")
	proto.RegisterType((*Data)(nil), "kratos.api.Data")
	proto.RegisterType((*Data_Database)(nil), "kratos.api.Data.Database")
	proto.RegisterType((*Data_Redis)(nil), "kratos.api.Data.Redis")
}

func init() {
	proto.RegisterFile("internal/conf/conf.proto", fileDescriptor_9c69a7f648509b54)
}

var fileDescriptor_9c69a7f648509b54 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0xb1, 0x2b, 0xcb, 0xd6, 0xd8, 0x85, 0xb2, 0x07, 0x57, 0xd6, 0xa1, 0x14, 0xb7, 0x85,
	0xd2, 0x96, 0x15, 0xd4, 0xf4, 0xd2, 0x84, 0x1c, 0x1c, 0x43, 0x72, 0x34, 0x1b, 0x9f, 0x02, 0x21,
	0xac, 0xad, 0xb5, 0xb2, 0xd8, 0xd1, 0x8a, 0xd1, 0x2a, 0xfe, 0x60, 0xb9, 0xe4, 0xcb, 0xe4, 0xbb,
	0x84, 0x5d, 0xad, 0x9c, 0x3f, 0x0e, 0x24, 0xb9, 0xe4, 0x32, 0x78, 0x3c, 0xbf, 0xf7, 0x1e, 0x7a,
	0x48, 0x10, 0xca, 0x4c, 0x0b, 0xcc, 0xf8, 0x3a, 0x5e, 0xa8, 0x6c, 0x69, 0x07, 0xcd, 0x51, 0x69,
	0x45, 0x60, 0x85, 0x5c, 0xab, 0x82, 0xf2, 0x5c, 0x46, 0x5f, 0x52, 0xa5, 0xd2, 0xb5, 0x88, 0xed,
	0x65, 0x5e, 0x2e, 0xe3, 0xa4, 0x44, 0xae, 0xa5, 0xca, 0x2a, 0x76, 0x78, 0x06, 0xc1, 0x58, 0x29,
	0x5d, 0x68, 0xe4, 0x39, 0xf9, 0x05, 0x7e, 0x21, 0xf0, 0x4a, 0x60, 0xd8, 0xf8, 0xda, 0xf8, 0xd9,
	0xfd, 0x4b, 0xe8, 0xbd, 0x13, 0x3d, 0xb1, 0x17, 0xe6, 0x08, 0xf2, 0x1d, 0xbc, 0x84, 0x6b, 0x1e,
	0x36, 0x2d, 0xf9, 0xe9, 0x21, 0x39, 0xe1, 0x9a, 0x33, 0x7b, 0x1d, 0xde, 0x34, 0xc1, 0xaf, 0x84,
	0xe4, 0x37, 0x78, 0x17, 0x5a, 0xe7, 0xce, 0xfa, 0xf3, 0xae, 0x35, 0x3d, 0x9e, 0xcd, 0xa6, 0xcc,
	0x42, 0x06, 0x4e, 0x31, 0x5f, 0x38, 0xf7, 0xe7, 0xe0, 0x23, 0x36, 0x3d, 0x64, 0x16, 0x8a, 0x24,
	0x78, 0x46, 0x4a, 0x42, 0x68, 0x67, 0x42, 0x6f, 0x14, 0xae, 0x6c, 0x48, 0xc0, 0xea, 0x95, 0x10,
	0xf0, 0x78, 0x92, 0xa0, 0xb5, 0x0b, 0x98, 0xfd, 0x4d, 0x46, 0xd0, 0xd6, 0xf2, 0x52, 0xa8, 0x52,
	0x87, 0x1f, 0x6c, 0xca, 0x80, 0x56, 0x5d, 0xd1, 0xba, 0x2b, 0x3a, 0x71, 0x5d, 0xb1, 0x9a, 0x34,
	0x51, 0x26, 0xf8, 0x1d, 0xa2, 0x86, 0xb7, 0x4d, 0xf0, 0x4c, 0x93, 0xe4, 0x1f, 0x74, 0x4c, 0x97,
	0x73, 0x5e, 0x08, 0x57, 0xde, 0xe0, 0x69, 0xdb, 0x76, 0x18, 0x80, 0x6d, 0x51, 0xf2, 0x07, 0x5a,
	0x28, 0x12, 0x59, 0xb8, 0x0e, 0xfb, 0x3b, 0x1a, 0x66, 0xae, 0xac, 0x82, 0xa2, 0xff, 0xd0, 0xa9,
	0x3d, 0x48, 0x1f, 0xfc, 0x04, 0x65, 0xfd, 0x1a, 0x04, 0xcc, 0x6d, 0xe6, 0xff, 0x42, 0x95, 0xb8,
	0x10, 0xee, 0xe1, 0xdc, 0x16, 0x5d, 0x37, 0xa0, 0x65, 0xcd, 0xde, 0x58, 0xcb, 0x3e, 0xf4, 0x50,
	0xf0, 0xe4, 0xfc, 0xd5, 0xdd, 0x74, 0x0d, 0x3e, 0xab, 0x68, 0x72, 0x00, 0x1f, 0x37, 0x28, 0xb5,
	0xd8, 0xca, 0xbd, 0x97, 0xe4, 0x3d, 0xcb, 0x3b, 0xfd, 0xf8, 0xc7, 0xe9, 0x37, 0xe4, 0x69, 0xcc,
	0xf3, 0x3c, 0x46, 0x81, 0x3c, 0x5b, 0x09, 0x8c, 0x1f, 0x7d, 0x52, 0x7b, 0x66, 0xcc, 0x7d, 0xeb,
	0x33, 0xba, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x50, 0x4d, 0xa4, 0xee, 0x6f, 0x03, 0x00, 0x00,
}
