// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/preprocessor/v1/preprocessor.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePreprocessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePreprocessorRequest) Reset()         { *m = CreatePreprocessorRequest{} }
func (m *CreatePreprocessorRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePreprocessorRequest) ProtoMessage()    {}
func (*CreatePreprocessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{0}
}

func (m *CreatePreprocessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePreprocessorRequest.Unmarshal(m, b)
}
func (m *CreatePreprocessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePreprocessorRequest.Marshal(b, m, deterministic)
}
func (m *CreatePreprocessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePreprocessorRequest.Merge(m, src)
}
func (m *CreatePreprocessorRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePreprocessorRequest.Size(m)
}
func (m *CreatePreprocessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePreprocessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePreprocessorRequest proto.InternalMessageInfo

type CreatePreprocessorReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePreprocessorReply) Reset()         { *m = CreatePreprocessorReply{} }
func (m *CreatePreprocessorReply) String() string { return proto.CompactTextString(m) }
func (*CreatePreprocessorReply) ProtoMessage()    {}
func (*CreatePreprocessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{1}
}

func (m *CreatePreprocessorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePreprocessorReply.Unmarshal(m, b)
}
func (m *CreatePreprocessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePreprocessorReply.Marshal(b, m, deterministic)
}
func (m *CreatePreprocessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePreprocessorReply.Merge(m, src)
}
func (m *CreatePreprocessorReply) XXX_Size() int {
	return xxx_messageInfo_CreatePreprocessorReply.Size(m)
}
func (m *CreatePreprocessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePreprocessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePreprocessorReply proto.InternalMessageInfo

type UpdatePreprocessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePreprocessorRequest) Reset()         { *m = UpdatePreprocessorRequest{} }
func (m *UpdatePreprocessorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePreprocessorRequest) ProtoMessage()    {}
func (*UpdatePreprocessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{2}
}

func (m *UpdatePreprocessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePreprocessorRequest.Unmarshal(m, b)
}
func (m *UpdatePreprocessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePreprocessorRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePreprocessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePreprocessorRequest.Merge(m, src)
}
func (m *UpdatePreprocessorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePreprocessorRequest.Size(m)
}
func (m *UpdatePreprocessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePreprocessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePreprocessorRequest proto.InternalMessageInfo

type UpdatePreprocessorReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePreprocessorReply) Reset()         { *m = UpdatePreprocessorReply{} }
func (m *UpdatePreprocessorReply) String() string { return proto.CompactTextString(m) }
func (*UpdatePreprocessorReply) ProtoMessage()    {}
func (*UpdatePreprocessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{3}
}

func (m *UpdatePreprocessorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePreprocessorReply.Unmarshal(m, b)
}
func (m *UpdatePreprocessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePreprocessorReply.Marshal(b, m, deterministic)
}
func (m *UpdatePreprocessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePreprocessorReply.Merge(m, src)
}
func (m *UpdatePreprocessorReply) XXX_Size() int {
	return xxx_messageInfo_UpdatePreprocessorReply.Size(m)
}
func (m *UpdatePreprocessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePreprocessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePreprocessorReply proto.InternalMessageInfo

type DeletePreprocessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePreprocessorRequest) Reset()         { *m = DeletePreprocessorRequest{} }
func (m *DeletePreprocessorRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePreprocessorRequest) ProtoMessage()    {}
func (*DeletePreprocessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{4}
}

func (m *DeletePreprocessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePreprocessorRequest.Unmarshal(m, b)
}
func (m *DeletePreprocessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePreprocessorRequest.Marshal(b, m, deterministic)
}
func (m *DeletePreprocessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePreprocessorRequest.Merge(m, src)
}
func (m *DeletePreprocessorRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePreprocessorRequest.Size(m)
}
func (m *DeletePreprocessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePreprocessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePreprocessorRequest proto.InternalMessageInfo

type DeletePreprocessorReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePreprocessorReply) Reset()         { *m = DeletePreprocessorReply{} }
func (m *DeletePreprocessorReply) String() string { return proto.CompactTextString(m) }
func (*DeletePreprocessorReply) ProtoMessage()    {}
func (*DeletePreprocessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{5}
}

func (m *DeletePreprocessorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePreprocessorReply.Unmarshal(m, b)
}
func (m *DeletePreprocessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePreprocessorReply.Marshal(b, m, deterministic)
}
func (m *DeletePreprocessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePreprocessorReply.Merge(m, src)
}
func (m *DeletePreprocessorReply) XXX_Size() int {
	return xxx_messageInfo_DeletePreprocessorReply.Size(m)
}
func (m *DeletePreprocessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePreprocessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePreprocessorReply proto.InternalMessageInfo

type GetPreprocessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPreprocessorRequest) Reset()         { *m = GetPreprocessorRequest{} }
func (m *GetPreprocessorRequest) String() string { return proto.CompactTextString(m) }
func (*GetPreprocessorRequest) ProtoMessage()    {}
func (*GetPreprocessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{6}
}

func (m *GetPreprocessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPreprocessorRequest.Unmarshal(m, b)
}
func (m *GetPreprocessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPreprocessorRequest.Marshal(b, m, deterministic)
}
func (m *GetPreprocessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPreprocessorRequest.Merge(m, src)
}
func (m *GetPreprocessorRequest) XXX_Size() int {
	return xxx_messageInfo_GetPreprocessorRequest.Size(m)
}
func (m *GetPreprocessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPreprocessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPreprocessorRequest proto.InternalMessageInfo

type GetPreprocessorReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPreprocessorReply) Reset()         { *m = GetPreprocessorReply{} }
func (m *GetPreprocessorReply) String() string { return proto.CompactTextString(m) }
func (*GetPreprocessorReply) ProtoMessage()    {}
func (*GetPreprocessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{7}
}

func (m *GetPreprocessorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPreprocessorReply.Unmarshal(m, b)
}
func (m *GetPreprocessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPreprocessorReply.Marshal(b, m, deterministic)
}
func (m *GetPreprocessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPreprocessorReply.Merge(m, src)
}
func (m *GetPreprocessorReply) XXX_Size() int {
	return xxx_messageInfo_GetPreprocessorReply.Size(m)
}
func (m *GetPreprocessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPreprocessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPreprocessorReply proto.InternalMessageInfo

type ListPreprocessorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPreprocessorRequest) Reset()         { *m = ListPreprocessorRequest{} }
func (m *ListPreprocessorRequest) String() string { return proto.CompactTextString(m) }
func (*ListPreprocessorRequest) ProtoMessage()    {}
func (*ListPreprocessorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{8}
}

func (m *ListPreprocessorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPreprocessorRequest.Unmarshal(m, b)
}
func (m *ListPreprocessorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPreprocessorRequest.Marshal(b, m, deterministic)
}
func (m *ListPreprocessorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPreprocessorRequest.Merge(m, src)
}
func (m *ListPreprocessorRequest) XXX_Size() int {
	return xxx_messageInfo_ListPreprocessorRequest.Size(m)
}
func (m *ListPreprocessorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPreprocessorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPreprocessorRequest proto.InternalMessageInfo

type ListPreprocessorReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPreprocessorReply) Reset()         { *m = ListPreprocessorReply{} }
func (m *ListPreprocessorReply) String() string { return proto.CompactTextString(m) }
func (*ListPreprocessorReply) ProtoMessage()    {}
func (*ListPreprocessorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3006ec4bba9fa7e6, []int{9}
}

func (m *ListPreprocessorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPreprocessorReply.Unmarshal(m, b)
}
func (m *ListPreprocessorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPreprocessorReply.Marshal(b, m, deterministic)
}
func (m *ListPreprocessorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPreprocessorReply.Merge(m, src)
}
func (m *ListPreprocessorReply) XXX_Size() int {
	return xxx_messageInfo_ListPreprocessorReply.Size(m)
}
func (m *ListPreprocessorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPreprocessorReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListPreprocessorReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreatePreprocessorRequest)(nil), "api.preprocessor.v1.CreatePreprocessorRequest")
	proto.RegisterType((*CreatePreprocessorReply)(nil), "api.preprocessor.v1.CreatePreprocessorReply")
	proto.RegisterType((*UpdatePreprocessorRequest)(nil), "api.preprocessor.v1.UpdatePreprocessorRequest")
	proto.RegisterType((*UpdatePreprocessorReply)(nil), "api.preprocessor.v1.UpdatePreprocessorReply")
	proto.RegisterType((*DeletePreprocessorRequest)(nil), "api.preprocessor.v1.DeletePreprocessorRequest")
	proto.RegisterType((*DeletePreprocessorReply)(nil), "api.preprocessor.v1.DeletePreprocessorReply")
	proto.RegisterType((*GetPreprocessorRequest)(nil), "api.preprocessor.v1.GetPreprocessorRequest")
	proto.RegisterType((*GetPreprocessorReply)(nil), "api.preprocessor.v1.GetPreprocessorReply")
	proto.RegisterType((*ListPreprocessorRequest)(nil), "api.preprocessor.v1.ListPreprocessorRequest")
	proto.RegisterType((*ListPreprocessorReply)(nil), "api.preprocessor.v1.ListPreprocessorReply")
}

func init() {
	proto.RegisterFile("api/preprocessor/v1/preprocessor.proto", fileDescriptor_3006ec4bba9fa7e6)
}

var fileDescriptor_3006ec4bba9fa7e6 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x11, 0xc4, 0xc3, 0x20, 0x28, 0x51, 0xb7, 0xb6, 0xde, 0xf6, 0x20, 0xf8, 0x87, 0x94,
	0xba, 0x47, 0x6f, 0x2a, 0x78, 0xf1, 0xb0, 0x08, 0x5e, 0xbc, 0x45, 0x1d, 0x24, 0x10, 0xc8, 0x98,
	0xc4, 0x42, 0x3e, 0x9f, 0x5f, 0x4c, 0x22, 0x1e, 0x76, 0x9b, 0x19, 0xe8, 0xb1, 0xf3, 0xe6, 0xd7,
	0x57, 0xde, 0xeb, 0xc0, 0xb9, 0x21, 0xdb, 0x53, 0x40, 0x0a, 0xfe, 0x1d, 0x63, 0xf4, 0xa1, 0x1f,
	0x87, 0xad, 0x67, 0x4d, 0xc1, 0x27, 0xaf, 0x8e, 0x0c, 0x59, 0xbd, 0x35, 0x1f, 0x87, 0xe5, 0x19,
	0xb4, 0xf7, 0x01, 0x4d, 0xc2, 0xf5, 0x86, 0xf0, 0x8c, 0x5f, 0xdf, 0x18, 0xd3, 0xb2, 0x85, 0x86,
	0x13, 0xc9, 0xe5, 0xc2, 0xbd, 0xd0, 0x87, 0xcc, 0x71, 0xe2, 0x3f, 0xf7, 0x80, 0x0e, 0x45, 0x8e,
	0x13, 0x0b, 0x77, 0x0a, 0x8b, 0x47, 0x4c, 0x1c, 0xb4, 0x80, 0xe3, 0x4a, 0x29, 0x44, 0x0b, 0xcd,
	0x93, 0x8d, 0x2c, 0xd2, 0xc0, 0x49, 0x2d, 0x91, 0xcb, 0x37, 0x3f, 0xbb, 0xb0, 0xbf, 0x39, 0x55,
	0x01, 0x54, 0x9d, 0x80, 0xd2, 0x9a, 0x89, 0x52, 0x8b, 0x39, 0x76, 0xd7, 0xb3, 0xf7, 0xc9, 0xe5,
	0xe2, 0x59, 0xa7, 0x27, 0x78, 0x8a, 0x1d, 0x08, 0x9e, 0x42, 0x2d, 0xc5, 0xb3, 0x4e, 0x5e, 0xf0,
	0x14, 0xfb, 0x13, 0x3c, 0x85, 0x4a, 0x95, 0x85, 0x83, 0x49, 0x71, 0xea, 0x8a, 0x7d, 0x01, 0x5f,
	0x7c, 0x77, 0x31, 0x6f, 0xb9, 0x58, 0x39, 0x38, 0x9c, 0x16, 0xae, 0xf8, 0x8f, 0x15, 0x7e, 0x99,
	0xee, 0x72, 0xe6, 0x36, 0xb9, 0x7c, 0xb7, 0x02, 0xee, 0xd4, 0xd6, 0x3b, 0xaf, 0x5d, 0x30, 0x9f,
	0x3d, 0x73, 0xad, 0xb7, 0xe3, 0xf0, 0xb6, 0xf7, 0x77, 0xa4, 0xab, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x20, 0x74, 0x39, 0x57, 0xce, 0x03, 0x00, 0x00,
}
