// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/preprocessor_svc.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
	v1 "rag/api/common/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProcessQueryRequest struct {
	Query                string             `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Options              *ProcessingOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Context              *v1.QueryContext   `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProcessQueryRequest) Reset()         { *m = ProcessQueryRequest{} }
func (m *ProcessQueryRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessQueryRequest) ProtoMessage()    {}
func (*ProcessQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{0}
}

func (m *ProcessQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessQueryRequest.Unmarshal(m, b)
}
func (m *ProcessQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessQueryRequest.Marshal(b, m, deterministic)
}
func (m *ProcessQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessQueryRequest.Merge(m, src)
}
func (m *ProcessQueryRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessQueryRequest.Size(m)
}
func (m *ProcessQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessQueryRequest proto.InternalMessageInfo

func (m *ProcessQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ProcessQueryRequest) GetOptions() *ProcessingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ProcessQueryRequest) GetContext() *v1.QueryContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type ProcessingOptions struct {
	EnableCleaning          bool              `protobuf:"varint,1,opt,name=enable_cleaning,json=enableCleaning,proto3" json:"enable_cleaning,omitempty"`
	EnableRewriting         bool              `protobuf:"varint,2,opt,name=enable_rewriting,json=enableRewriting,proto3" json:"enable_rewriting,omitempty"`
	EnableSynonymExpansion  bool              `protobuf:"varint,3,opt,name=enable_synonym_expansion,json=enableSynonymExpansion,proto3" json:"enable_synonym_expansion,omitempty"`
	EnableSpellCorrection   bool              `protobuf:"varint,4,opt,name=enable_spell_correction,json=enableSpellCorrection,proto3" json:"enable_spell_correction,omitempty"`
	EnableLanguageDetection bool              `protobuf:"varint,5,opt,name=enable_language_detection,json=enableLanguageDetection,proto3" json:"enable_language_detection,omitempty"`
	TargetLanguage          string            `protobuf:"bytes,6,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	CleaningOptions         *CleaningOptions  `protobuf:"bytes,7,opt,name=cleaning_options,json=cleaningOptions,proto3" json:"cleaning_options,omitempty"`
	RewritingOptions        *RewritingOptions `protobuf:"bytes,8,opt,name=rewriting_options,json=rewritingOptions,proto3" json:"rewriting_options,omitempty"`
	SynonymOptions          *SynonymOptions   `protobuf:"bytes,9,opt,name=synonym_options,json=synonymOptions,proto3" json:"synonym_options,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}          `json:"-"`
	XXX_unrecognized        []byte            `json:"-"`
	XXX_sizecache           int32             `json:"-"`
}

func (m *ProcessingOptions) Reset()         { *m = ProcessingOptions{} }
func (m *ProcessingOptions) String() string { return proto.CompactTextString(m) }
func (*ProcessingOptions) ProtoMessage()    {}
func (*ProcessingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{1}
}

func (m *ProcessingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingOptions.Unmarshal(m, b)
}
func (m *ProcessingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingOptions.Marshal(b, m, deterministic)
}
func (m *ProcessingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingOptions.Merge(m, src)
}
func (m *ProcessingOptions) XXX_Size() int {
	return xxx_messageInfo_ProcessingOptions.Size(m)
}
func (m *ProcessingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingOptions proto.InternalMessageInfo

func (m *ProcessingOptions) GetEnableCleaning() bool {
	if m != nil {
		return m.EnableCleaning
	}
	return false
}

func (m *ProcessingOptions) GetEnableRewriting() bool {
	if m != nil {
		return m.EnableRewriting
	}
	return false
}

func (m *ProcessingOptions) GetEnableSynonymExpansion() bool {
	if m != nil {
		return m.EnableSynonymExpansion
	}
	return false
}

func (m *ProcessingOptions) GetEnableSpellCorrection() bool {
	if m != nil {
		return m.EnableSpellCorrection
	}
	return false
}

func (m *ProcessingOptions) GetEnableLanguageDetection() bool {
	if m != nil {
		return m.EnableLanguageDetection
	}
	return false
}

func (m *ProcessingOptions) GetTargetLanguage() string {
	if m != nil {
		return m.TargetLanguage
	}
	return ""
}

func (m *ProcessingOptions) GetCleaningOptions() *CleaningOptions {
	if m != nil {
		return m.CleaningOptions
	}
	return nil
}

func (m *ProcessingOptions) GetRewritingOptions() *RewritingOptions {
	if m != nil {
		return m.RewritingOptions
	}
	return nil
}

func (m *ProcessingOptions) GetSynonymOptions() *SynonymOptions {
	if m != nil {
		return m.SynonymOptions
	}
	return nil
}

type CleaningOptions struct {
	RemoveSpecialChars   bool     `protobuf:"varint,1,opt,name=remove_special_chars,json=removeSpecialChars,proto3" json:"remove_special_chars,omitempty"`
	NormalizeWhitespace  bool     `protobuf:"varint,2,opt,name=normalize_whitespace,json=normalizeWhitespace,proto3" json:"normalize_whitespace,omitempty"`
	FixEncoding          bool     `protobuf:"varint,3,opt,name=fix_encoding,json=fixEncoding,proto3" json:"fix_encoding,omitempty"`
	RemoveDuplicates     bool     `protobuf:"varint,4,opt,name=remove_duplicates,json=removeDuplicates,proto3" json:"remove_duplicates,omitempty"`
	StopWords            []string `protobuf:"bytes,5,rep,name=stop_words,json=stopWords,proto3" json:"stop_words,omitempty"`
	NormalizationForm    string   `protobuf:"bytes,6,opt,name=normalization_form,json=normalizationForm,proto3" json:"normalization_form,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleaningOptions) Reset()         { *m = CleaningOptions{} }
func (m *CleaningOptions) String() string { return proto.CompactTextString(m) }
func (*CleaningOptions) ProtoMessage()    {}
func (*CleaningOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{2}
}

func (m *CleaningOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleaningOptions.Unmarshal(m, b)
}
func (m *CleaningOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleaningOptions.Marshal(b, m, deterministic)
}
func (m *CleaningOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleaningOptions.Merge(m, src)
}
func (m *CleaningOptions) XXX_Size() int {
	return xxx_messageInfo_CleaningOptions.Size(m)
}
func (m *CleaningOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CleaningOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CleaningOptions proto.InternalMessageInfo

func (m *CleaningOptions) GetRemoveSpecialChars() bool {
	if m != nil {
		return m.RemoveSpecialChars
	}
	return false
}

func (m *CleaningOptions) GetNormalizeWhitespace() bool {
	if m != nil {
		return m.NormalizeWhitespace
	}
	return false
}

func (m *CleaningOptions) GetFixEncoding() bool {
	if m != nil {
		return m.FixEncoding
	}
	return false
}

func (m *CleaningOptions) GetRemoveDuplicates() bool {
	if m != nil {
		return m.RemoveDuplicates
	}
	return false
}

func (m *CleaningOptions) GetStopWords() []string {
	if m != nil {
		return m.StopWords
	}
	return nil
}

func (m *CleaningOptions) GetNormalizationForm() string {
	if m != nil {
		return m.NormalizationForm
	}
	return ""
}

type RewritingOptions struct {
	RewriteStrategy      string   `protobuf:"bytes,1,opt,name=rewrite_strategy,json=rewriteStrategy,proto3" json:"rewrite_strategy,omitempty"`
	ConfidenceThreshold  float32  `protobuf:"fixed32,2,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	MaxAlternatives      int32    `protobuf:"varint,3,opt,name=max_alternatives,json=maxAlternatives,proto3" json:"max_alternatives,omitempty"`
	PreserveIntent       bool     `protobuf:"varint,4,opt,name=preserve_intent,json=preserveIntent,proto3" json:"preserve_intent,omitempty"`
	DomainKeywords       []string `protobuf:"bytes,5,rep,name=domain_keywords,json=domainKeywords,proto3" json:"domain_keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewritingOptions) Reset()         { *m = RewritingOptions{} }
func (m *RewritingOptions) String() string { return proto.CompactTextString(m) }
func (*RewritingOptions) ProtoMessage()    {}
func (*RewritingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{3}
}

func (m *RewritingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewritingOptions.Unmarshal(m, b)
}
func (m *RewritingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewritingOptions.Marshal(b, m, deterministic)
}
func (m *RewritingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewritingOptions.Merge(m, src)
}
func (m *RewritingOptions) XXX_Size() int {
	return xxx_messageInfo_RewritingOptions.Size(m)
}
func (m *RewritingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RewritingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RewritingOptions proto.InternalMessageInfo

func (m *RewritingOptions) GetRewriteStrategy() string {
	if m != nil {
		return m.RewriteStrategy
	}
	return ""
}

func (m *RewritingOptions) GetConfidenceThreshold() float32 {
	if m != nil {
		return m.ConfidenceThreshold
	}
	return 0
}

func (m *RewritingOptions) GetMaxAlternatives() int32 {
	if m != nil {
		return m.MaxAlternatives
	}
	return 0
}

func (m *RewritingOptions) GetPreserveIntent() bool {
	if m != nil {
		return m.PreserveIntent
	}
	return false
}

func (m *RewritingOptions) GetDomainKeywords() []string {
	if m != nil {
		return m.DomainKeywords
	}
	return nil
}

type SynonymOptions struct {
	SynonymSources       []string `protobuf:"bytes,1,rep,name=synonym_sources,json=synonymSources,proto3" json:"synonym_sources,omitempty"`
	SimilarityThreshold  float32  `protobuf:"fixed32,2,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	MaxSynonymsPerWord   int32    `protobuf:"varint,3,opt,name=max_synonyms_per_word,json=maxSynonymsPerWord,proto3" json:"max_synonyms_per_word,omitempty"`
	IncludeHyponyms      bool     `protobuf:"varint,4,opt,name=include_hyponyms,json=includeHyponyms,proto3" json:"include_hyponyms,omitempty"`
	IncludeHypernyms     bool     `protobuf:"varint,5,opt,name=include_hypernyms,json=includeHypernyms,proto3" json:"include_hypernyms,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SynonymOptions) Reset()         { *m = SynonymOptions{} }
func (m *SynonymOptions) String() string { return proto.CompactTextString(m) }
func (*SynonymOptions) ProtoMessage()    {}
func (*SynonymOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{4}
}

func (m *SynonymOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynonymOptions.Unmarshal(m, b)
}
func (m *SynonymOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynonymOptions.Marshal(b, m, deterministic)
}
func (m *SynonymOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynonymOptions.Merge(m, src)
}
func (m *SynonymOptions) XXX_Size() int {
	return xxx_messageInfo_SynonymOptions.Size(m)
}
func (m *SynonymOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SynonymOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SynonymOptions proto.InternalMessageInfo

func (m *SynonymOptions) GetSynonymSources() []string {
	if m != nil {
		return m.SynonymSources
	}
	return nil
}

func (m *SynonymOptions) GetSimilarityThreshold() float32 {
	if m != nil {
		return m.SimilarityThreshold
	}
	return 0
}

func (m *SynonymOptions) GetMaxSynonymsPerWord() int32 {
	if m != nil {
		return m.MaxSynonymsPerWord
	}
	return 0
}

func (m *SynonymOptions) GetIncludeHyponyms() bool {
	if m != nil {
		return m.IncludeHyponyms
	}
	return false
}

func (m *SynonymOptions) GetIncludeHypernyms() bool {
	if m != nil {
		return m.IncludeHypernyms
	}
	return false
}

func (m *SynonymOptions) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type ProcessQueryResponse struct {
	OriginalQuery        string              `protobuf:"bytes,1,opt,name=original_query,json=originalQuery,proto3" json:"original_query,omitempty"`
	ProcessedQuery       string              `protobuf:"bytes,2,opt,name=processed_query,json=processedQuery,proto3" json:"processed_query,omitempty"`
	ProcessingSteps      []*ProcessingStep   `protobuf:"bytes,3,rep,name=processing_steps,json=processingSteps,proto3" json:"processing_steps,omitempty"`
	Metadata             *ProcessingMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Alternatives         []*QueryAlternative `protobuf:"bytes,5,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProcessQueryResponse) Reset()         { *m = ProcessQueryResponse{} }
func (m *ProcessQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessQueryResponse) ProtoMessage()    {}
func (*ProcessQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{5}
}

func (m *ProcessQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessQueryResponse.Unmarshal(m, b)
}
func (m *ProcessQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessQueryResponse.Marshal(b, m, deterministic)
}
func (m *ProcessQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessQueryResponse.Merge(m, src)
}
func (m *ProcessQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessQueryResponse.Size(m)
}
func (m *ProcessQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessQueryResponse proto.InternalMessageInfo

func (m *ProcessQueryResponse) GetOriginalQuery() string {
	if m != nil {
		return m.OriginalQuery
	}
	return ""
}

func (m *ProcessQueryResponse) GetProcessedQuery() string {
	if m != nil {
		return m.ProcessedQuery
	}
	return ""
}

func (m *ProcessQueryResponse) GetProcessingSteps() []*ProcessingStep {
	if m != nil {
		return m.ProcessingSteps
	}
	return nil
}

func (m *ProcessQueryResponse) GetMetadata() *ProcessingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ProcessQueryResponse) GetAlternatives() []*QueryAlternative {
	if m != nil {
		return m.Alternatives
	}
	return nil
}

type ProcessingStep struct {
	StepName             string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	InputText            string                 `protobuf:"bytes,2,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	OutputText           string                 `protobuf:"bytes,3,opt,name=output_text,json=outputText,proto3" json:"output_text,omitempty"`
	ConfidenceScore      float32                `protobuf:"fixed32,4,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	StepMetadata         map[string]string      `protobuf:"bytes,5,rep,name=step_metadata,json=stepMetadata,proto3" json:"step_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProcessedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProcessingStep) Reset()         { *m = ProcessingStep{} }
func (m *ProcessingStep) String() string { return proto.CompactTextString(m) }
func (*ProcessingStep) ProtoMessage()    {}
func (*ProcessingStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{6}
}

func (m *ProcessingStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingStep.Unmarshal(m, b)
}
func (m *ProcessingStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingStep.Marshal(b, m, deterministic)
}
func (m *ProcessingStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingStep.Merge(m, src)
}
func (m *ProcessingStep) XXX_Size() int {
	return xxx_messageInfo_ProcessingStep.Size(m)
}
func (m *ProcessingStep) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingStep.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingStep proto.InternalMessageInfo

func (m *ProcessingStep) GetStepName() string {
	if m != nil {
		return m.StepName
	}
	return ""
}

func (m *ProcessingStep) GetInputText() string {
	if m != nil {
		return m.InputText
	}
	return ""
}

func (m *ProcessingStep) GetOutputText() string {
	if m != nil {
		return m.OutputText
	}
	return ""
}

func (m *ProcessingStep) GetConfidenceScore() float32 {
	if m != nil {
		return m.ConfidenceScore
	}
	return 0
}

func (m *ProcessingStep) GetStepMetadata() map[string]string {
	if m != nil {
		return m.StepMetadata
	}
	return nil
}

func (m *ProcessingStep) GetProcessedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ProcessedAt
	}
	return nil
}

type ProcessingMetadata struct {
	DetectedLanguage     string                 `protobuf:"bytes,1,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	ProcessingConfidence float32                `protobuf:"fixed32,2,opt,name=processing_confidence,json=processingConfidence,proto3" json:"processing_confidence,omitempty"`
	ProcessingTimeMs     int64                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	AppliedStrategies    []string               `protobuf:"bytes,4,rep,name=applied_strategies,json=appliedStrategies,proto3" json:"applied_strategies,omitempty"`
	DebugInfo            map[string]string      `protobuf:"bytes,5,rep,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProcessedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProcessingMetadata) Reset()         { *m = ProcessingMetadata{} }
func (m *ProcessingMetadata) String() string { return proto.CompactTextString(m) }
func (*ProcessingMetadata) ProtoMessage()    {}
func (*ProcessingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{7}
}

func (m *ProcessingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingMetadata.Unmarshal(m, b)
}
func (m *ProcessingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingMetadata.Marshal(b, m, deterministic)
}
func (m *ProcessingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingMetadata.Merge(m, src)
}
func (m *ProcessingMetadata) XXX_Size() int {
	return xxx_messageInfo_ProcessingMetadata.Size(m)
}
func (m *ProcessingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingMetadata proto.InternalMessageInfo

func (m *ProcessingMetadata) GetDetectedLanguage() string {
	if m != nil {
		return m.DetectedLanguage
	}
	return ""
}

func (m *ProcessingMetadata) GetProcessingConfidence() float32 {
	if m != nil {
		return m.ProcessingConfidence
	}
	return 0
}

func (m *ProcessingMetadata) GetProcessingTimeMs() int64 {
	if m != nil {
		return m.ProcessingTimeMs
	}
	return 0
}

func (m *ProcessingMetadata) GetAppliedStrategies() []string {
	if m != nil {
		return m.AppliedStrategies
	}
	return nil
}

func (m *ProcessingMetadata) GetDebugInfo() map[string]string {
	if m != nil {
		return m.DebugInfo
	}
	return nil
}

func (m *ProcessingMetadata) GetProcessedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ProcessedAt
	}
	return nil
}

type QueryAlternative struct {
	QueryText            string            `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	ConfidenceScore      float32           `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	GenerationMethod     string            `protobuf:"bytes,3,opt,name=generation_method,json=generationMethod,proto3" json:"generation_method,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryAlternative) Reset()         { *m = QueryAlternative{} }
func (m *QueryAlternative) String() string { return proto.CompactTextString(m) }
func (*QueryAlternative) ProtoMessage()    {}
func (*QueryAlternative) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{8}
}

func (m *QueryAlternative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAlternative.Unmarshal(m, b)
}
func (m *QueryAlternative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAlternative.Marshal(b, m, deterministic)
}
func (m *QueryAlternative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAlternative.Merge(m, src)
}
func (m *QueryAlternative) XXX_Size() int {
	return xxx_messageInfo_QueryAlternative.Size(m)
}
func (m *QueryAlternative) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAlternative.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAlternative proto.InternalMessageInfo

func (m *QueryAlternative) GetQueryText() string {
	if m != nil {
		return m.QueryText
	}
	return ""
}

func (m *QueryAlternative) GetConfidenceScore() float32 {
	if m != nil {
		return m.ConfidenceScore
	}
	return 0
}

func (m *QueryAlternative) GetGenerationMethod() string {
	if m != nil {
		return m.GenerationMethod
	}
	return ""
}

func (m *QueryAlternative) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type RewriteQueryRequest struct {
	Query                string            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Options              *RewritingOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Context              *v1.QueryContext  `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RewriteQueryRequest) Reset()         { *m = RewriteQueryRequest{} }
func (m *RewriteQueryRequest) String() string { return proto.CompactTextString(m) }
func (*RewriteQueryRequest) ProtoMessage()    {}
func (*RewriteQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{9}
}

func (m *RewriteQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewriteQueryRequest.Unmarshal(m, b)
}
func (m *RewriteQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewriteQueryRequest.Marshal(b, m, deterministic)
}
func (m *RewriteQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewriteQueryRequest.Merge(m, src)
}
func (m *RewriteQueryRequest) XXX_Size() int {
	return xxx_messageInfo_RewriteQueryRequest.Size(m)
}
func (m *RewriteQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RewriteQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RewriteQueryRequest proto.InternalMessageInfo

func (m *RewriteQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *RewriteQueryRequest) GetOptions() *RewritingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *RewriteQueryRequest) GetContext() *v1.QueryContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type RewriteQueryResponse struct {
	OriginalQuery        string             `protobuf:"bytes,1,opt,name=original_query,json=originalQuery,proto3" json:"original_query,omitempty"`
	RewrittenQueries     []*RewrittenQuery  `protobuf:"bytes,2,rep,name=rewritten_queries,json=rewrittenQueries,proto3" json:"rewritten_queries,omitempty"`
	Metadata             *RewritingMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RewriteQueryResponse) Reset()         { *m = RewriteQueryResponse{} }
func (m *RewriteQueryResponse) String() string { return proto.CompactTextString(m) }
func (*RewriteQueryResponse) ProtoMessage()    {}
func (*RewriteQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{10}
}

func (m *RewriteQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewriteQueryResponse.Unmarshal(m, b)
}
func (m *RewriteQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewriteQueryResponse.Marshal(b, m, deterministic)
}
func (m *RewriteQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewriteQueryResponse.Merge(m, src)
}
func (m *RewriteQueryResponse) XXX_Size() int {
	return xxx_messageInfo_RewriteQueryResponse.Size(m)
}
func (m *RewriteQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RewriteQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RewriteQueryResponse proto.InternalMessageInfo

func (m *RewriteQueryResponse) GetOriginalQuery() string {
	if m != nil {
		return m.OriginalQuery
	}
	return ""
}

func (m *RewriteQueryResponse) GetRewrittenQueries() []*RewrittenQuery {
	if m != nil {
		return m.RewrittenQueries
	}
	return nil
}

func (m *RewriteQueryResponse) GetMetadata() *RewritingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type RewrittenQuery struct {
	QueryText            string            `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	ConfidenceScore      float32           `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	RewriteType          string            `protobuf:"bytes,3,opt,name=rewrite_type,json=rewriteType,proto3" json:"rewrite_type,omitempty"`
	Changes              []*RewriteChange  `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RewrittenQuery) Reset()         { *m = RewrittenQuery{} }
func (m *RewrittenQuery) String() string { return proto.CompactTextString(m) }
func (*RewrittenQuery) ProtoMessage()    {}
func (*RewrittenQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{11}
}

func (m *RewrittenQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewrittenQuery.Unmarshal(m, b)
}
func (m *RewrittenQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewrittenQuery.Marshal(b, m, deterministic)
}
func (m *RewrittenQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewrittenQuery.Merge(m, src)
}
func (m *RewrittenQuery) XXX_Size() int {
	return xxx_messageInfo_RewrittenQuery.Size(m)
}
func (m *RewrittenQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RewrittenQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RewrittenQuery proto.InternalMessageInfo

func (m *RewrittenQuery) GetQueryText() string {
	if m != nil {
		return m.QueryText
	}
	return ""
}

func (m *RewrittenQuery) GetConfidenceScore() float32 {
	if m != nil {
		return m.ConfidenceScore
	}
	return 0
}

func (m *RewrittenQuery) GetRewriteType() string {
	if m != nil {
		return m.RewriteType
	}
	return ""
}

func (m *RewrittenQuery) GetChanges() []*RewriteChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *RewrittenQuery) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type RewriteChange struct {
	OriginalText         string   `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	RewrittenText        string   `protobuf:"bytes,2,opt,name=rewritten_text,json=rewrittenText,proto3" json:"rewritten_text,omitempty"`
	ChangeType           string   `protobuf:"bytes,3,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Confidence           float32  `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewriteChange) Reset()         { *m = RewriteChange{} }
func (m *RewriteChange) String() string { return proto.CompactTextString(m) }
func (*RewriteChange) ProtoMessage()    {}
func (*RewriteChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{12}
}

func (m *RewriteChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewriteChange.Unmarshal(m, b)
}
func (m *RewriteChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewriteChange.Marshal(b, m, deterministic)
}
func (m *RewriteChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewriteChange.Merge(m, src)
}
func (m *RewriteChange) XXX_Size() int {
	return xxx_messageInfo_RewriteChange.Size(m)
}
func (m *RewriteChange) XXX_DiscardUnknown() {
	xxx_messageInfo_RewriteChange.DiscardUnknown(m)
}

var xxx_messageInfo_RewriteChange proto.InternalMessageInfo

func (m *RewriteChange) GetOriginalText() string {
	if m != nil {
		return m.OriginalText
	}
	return ""
}

func (m *RewriteChange) GetRewrittenText() string {
	if m != nil {
		return m.RewrittenText
	}
	return ""
}

func (m *RewriteChange) GetChangeType() string {
	if m != nil {
		return m.ChangeType
	}
	return ""
}

func (m *RewriteChange) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *RewriteChange) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type RewritingMetadata struct {
	ModelUsed            string            `protobuf:"bytes,1,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	ProcessingTimeMs     int64             `protobuf:"varint,2,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	DetectedIssues       []string          `protobuf:"bytes,3,rep,name=detected_issues,json=detectedIssues,proto3" json:"detected_issues,omitempty"`
	DebugInfo            map[string]string `protobuf:"bytes,4,rep,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RewritingMetadata) Reset()         { *m = RewritingMetadata{} }
func (m *RewritingMetadata) String() string { return proto.CompactTextString(m) }
func (*RewritingMetadata) ProtoMessage()    {}
func (*RewritingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{13}
}

func (m *RewritingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewritingMetadata.Unmarshal(m, b)
}
func (m *RewritingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewritingMetadata.Marshal(b, m, deterministic)
}
func (m *RewritingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewritingMetadata.Merge(m, src)
}
func (m *RewritingMetadata) XXX_Size() int {
	return xxx_messageInfo_RewritingMetadata.Size(m)
}
func (m *RewritingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RewritingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RewritingMetadata proto.InternalMessageInfo

func (m *RewritingMetadata) GetModelUsed() string {
	if m != nil {
		return m.ModelUsed
	}
	return ""
}

func (m *RewritingMetadata) GetProcessingTimeMs() int64 {
	if m != nil {
		return m.ProcessingTimeMs
	}
	return 0
}

func (m *RewritingMetadata) GetDetectedIssues() []string {
	if m != nil {
		return m.DetectedIssues
	}
	return nil
}

func (m *RewritingMetadata) GetDebugInfo() map[string]string {
	if m != nil {
		return m.DebugInfo
	}
	return nil
}

type ExpandSynonymsRequest struct {
	Text                 string          `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Options              *SynonymOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	FocusWords           []string        `protobuf:"bytes,3,rep,name=focus_words,json=focusWords,proto3" json:"focus_words,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ExpandSynonymsRequest) Reset()         { *m = ExpandSynonymsRequest{} }
func (m *ExpandSynonymsRequest) String() string { return proto.CompactTextString(m) }
func (*ExpandSynonymsRequest) ProtoMessage()    {}
func (*ExpandSynonymsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{14}
}

func (m *ExpandSynonymsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandSynonymsRequest.Unmarshal(m, b)
}
func (m *ExpandSynonymsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandSynonymsRequest.Marshal(b, m, deterministic)
}
func (m *ExpandSynonymsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandSynonymsRequest.Merge(m, src)
}
func (m *ExpandSynonymsRequest) XXX_Size() int {
	return xxx_messageInfo_ExpandSynonymsRequest.Size(m)
}
func (m *ExpandSynonymsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandSynonymsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandSynonymsRequest proto.InternalMessageInfo

func (m *ExpandSynonymsRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ExpandSynonymsRequest) GetOptions() *SynonymOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ExpandSynonymsRequest) GetFocusWords() []string {
	if m != nil {
		return m.FocusWords
	}
	return nil
}

type ExpandSynonymsResponse struct {
	OriginalText         string           `protobuf:"bytes,1,opt,name=original_text,json=originalText,proto3" json:"original_text,omitempty"`
	ExpandedWords        []*ExpandedWord  `protobuf:"bytes,2,rep,name=expanded_words,json=expandedWords,proto3" json:"expanded_words,omitempty"`
	ExpandedQueries      []string         `protobuf:"bytes,3,rep,name=expanded_queries,json=expandedQueries,proto3" json:"expanded_queries,omitempty"`
	Metadata             *SynonymMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExpandSynonymsResponse) Reset()         { *m = ExpandSynonymsResponse{} }
func (m *ExpandSynonymsResponse) String() string { return proto.CompactTextString(m) }
func (*ExpandSynonymsResponse) ProtoMessage()    {}
func (*ExpandSynonymsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{15}
}

func (m *ExpandSynonymsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandSynonymsResponse.Unmarshal(m, b)
}
func (m *ExpandSynonymsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandSynonymsResponse.Marshal(b, m, deterministic)
}
func (m *ExpandSynonymsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandSynonymsResponse.Merge(m, src)
}
func (m *ExpandSynonymsResponse) XXX_Size() int {
	return xxx_messageInfo_ExpandSynonymsResponse.Size(m)
}
func (m *ExpandSynonymsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandSynonymsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandSynonymsResponse proto.InternalMessageInfo

func (m *ExpandSynonymsResponse) GetOriginalText() string {
	if m != nil {
		return m.OriginalText
	}
	return ""
}

func (m *ExpandSynonymsResponse) GetExpandedWords() []*ExpandedWord {
	if m != nil {
		return m.ExpandedWords
	}
	return nil
}

func (m *ExpandSynonymsResponse) GetExpandedQueries() []string {
	if m != nil {
		return m.ExpandedQueries
	}
	return nil
}

func (m *ExpandSynonymsResponse) GetMetadata() *SynonymMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ExpandedWord struct {
	OriginalWord         string            `protobuf:"bytes,1,opt,name=original_word,json=originalWord,proto3" json:"original_word,omitempty"`
	Synonyms             []*Synonym        `protobuf:"bytes,2,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	PartOfSpeech         string            `protobuf:"bytes,3,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	WordMetadata         map[string]string `protobuf:"bytes,4,rep,name=word_metadata,json=wordMetadata,proto3" json:"word_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExpandedWord) Reset()         { *m = ExpandedWord{} }
func (m *ExpandedWord) String() string { return proto.CompactTextString(m) }
func (*ExpandedWord) ProtoMessage()    {}
func (*ExpandedWord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{16}
}

func (m *ExpandedWord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandedWord.Unmarshal(m, b)
}
func (m *ExpandedWord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandedWord.Marshal(b, m, deterministic)
}
func (m *ExpandedWord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandedWord.Merge(m, src)
}
func (m *ExpandedWord) XXX_Size() int {
	return xxx_messageInfo_ExpandedWord.Size(m)
}
func (m *ExpandedWord) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandedWord.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandedWord proto.InternalMessageInfo

func (m *ExpandedWord) GetOriginalWord() string {
	if m != nil {
		return m.OriginalWord
	}
	return ""
}

func (m *ExpandedWord) GetSynonyms() []*Synonym {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *ExpandedWord) GetPartOfSpeech() string {
	if m != nil {
		return m.PartOfSpeech
	}
	return ""
}

func (m *ExpandedWord) GetWordMetadata() map[string]string {
	if m != nil {
		return m.WordMetadata
	}
	return nil
}

type Synonym struct {
	Word                 string            `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	SimilarityScore      float32           `protobuf:"fixed32,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Source               string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	RelationType         string            `protobuf:"bytes,4,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Synonym) Reset()         { *m = Synonym{} }
func (m *Synonym) String() string { return proto.CompactTextString(m) }
func (*Synonym) ProtoMessage()    {}
func (*Synonym) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{17}
}

func (m *Synonym) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Synonym.Unmarshal(m, b)
}
func (m *Synonym) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Synonym.Marshal(b, m, deterministic)
}
func (m *Synonym) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Synonym.Merge(m, src)
}
func (m *Synonym) XXX_Size() int {
	return xxx_messageInfo_Synonym.Size(m)
}
func (m *Synonym) XXX_DiscardUnknown() {
	xxx_messageInfo_Synonym.DiscardUnknown(m)
}

var xxx_messageInfo_Synonym proto.InternalMessageInfo

func (m *Synonym) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Synonym) GetSimilarityScore() float32 {
	if m != nil {
		return m.SimilarityScore
	}
	return 0
}

func (m *Synonym) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Synonym) GetRelationType() string {
	if m != nil {
		return m.RelationType
	}
	return ""
}

func (m *Synonym) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SynonymMetadata struct {
	SourcesUsed          []string          `protobuf:"bytes,1,rep,name=sources_used,json=sourcesUsed,proto3" json:"sources_used,omitempty"`
	TotalSynonymsFound   int32             `protobuf:"varint,2,opt,name=total_synonyms_found,json=totalSynonymsFound,proto3" json:"total_synonyms_found,omitempty"`
	ProcessingTimeMs     int64             `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	LanguageDetected     string            `protobuf:"bytes,4,opt,name=language_detected,json=languageDetected,proto3" json:"language_detected,omitempty"`
	DebugInfo            map[string]string `protobuf:"bytes,5,rep,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SynonymMetadata) Reset()         { *m = SynonymMetadata{} }
func (m *SynonymMetadata) String() string { return proto.CompactTextString(m) }
func (*SynonymMetadata) ProtoMessage()    {}
func (*SynonymMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{18}
}

func (m *SynonymMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynonymMetadata.Unmarshal(m, b)
}
func (m *SynonymMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynonymMetadata.Marshal(b, m, deterministic)
}
func (m *SynonymMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynonymMetadata.Merge(m, src)
}
func (m *SynonymMetadata) XXX_Size() int {
	return xxx_messageInfo_SynonymMetadata.Size(m)
}
func (m *SynonymMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SynonymMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SynonymMetadata proto.InternalMessageInfo

func (m *SynonymMetadata) GetSourcesUsed() []string {
	if m != nil {
		return m.SourcesUsed
	}
	return nil
}

func (m *SynonymMetadata) GetTotalSynonymsFound() int32 {
	if m != nil {
		return m.TotalSynonymsFound
	}
	return 0
}

func (m *SynonymMetadata) GetProcessingTimeMs() int64 {
	if m != nil {
		return m.ProcessingTimeMs
	}
	return 0
}

func (m *SynonymMetadata) GetLanguageDetected() string {
	if m != nil {
		return m.LanguageDetected
	}
	return ""
}

func (m *SynonymMetadata) GetDebugInfo() map[string]string {
	if m != nil {
		return m.DebugInfo
	}
	return nil
}

type ProcessBatchQueriesRequest struct {
	Queries              []string           `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Options              *ProcessingOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	BatchId              string             `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProcessBatchQueriesRequest) Reset()         { *m = ProcessBatchQueriesRequest{} }
func (m *ProcessBatchQueriesRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessBatchQueriesRequest) ProtoMessage()    {}
func (*ProcessBatchQueriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{19}
}

func (m *ProcessBatchQueriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessBatchQueriesRequest.Unmarshal(m, b)
}
func (m *ProcessBatchQueriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessBatchQueriesRequest.Marshal(b, m, deterministic)
}
func (m *ProcessBatchQueriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessBatchQueriesRequest.Merge(m, src)
}
func (m *ProcessBatchQueriesRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessBatchQueriesRequest.Size(m)
}
func (m *ProcessBatchQueriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessBatchQueriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessBatchQueriesRequest proto.InternalMessageInfo

func (m *ProcessBatchQueriesRequest) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *ProcessBatchQueriesRequest) GetOptions() *ProcessingOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ProcessBatchQueriesRequest) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

type ProcessBatchQueriesResponse struct {
	BatchId              string                   `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Results              []*BatchQueryResult      `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Metadata             *BatchProcessingMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProcessBatchQueriesResponse) Reset()         { *m = ProcessBatchQueriesResponse{} }
func (m *ProcessBatchQueriesResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessBatchQueriesResponse) ProtoMessage()    {}
func (*ProcessBatchQueriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{20}
}

func (m *ProcessBatchQueriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessBatchQueriesResponse.Unmarshal(m, b)
}
func (m *ProcessBatchQueriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessBatchQueriesResponse.Marshal(b, m, deterministic)
}
func (m *ProcessBatchQueriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessBatchQueriesResponse.Merge(m, src)
}
func (m *ProcessBatchQueriesResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessBatchQueriesResponse.Size(m)
}
func (m *ProcessBatchQueriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessBatchQueriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessBatchQueriesResponse proto.InternalMessageInfo

func (m *ProcessBatchQueriesResponse) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *ProcessBatchQueriesResponse) GetResults() []*BatchQueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ProcessBatchQueriesResponse) GetMetadata() *BatchProcessingMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type BatchQueryResult struct {
	Index                int32               `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	OriginalQuery        string              `protobuf:"bytes,2,opt,name=original_query,json=originalQuery,proto3" json:"original_query,omitempty"`
	ProcessedQuery       string              `protobuf:"bytes,3,opt,name=processed_query,json=processedQuery,proto3" json:"processed_query,omitempty"`
	Status               v1.ProcessingStatus `protobuf:"varint,4,opt,name=status,proto3,enum=api.common.v1.ProcessingStatus" json:"status,omitempty"`
	ErrorMessage         string              `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProcessingMetadata   *ProcessingMetadata `protobuf:"bytes,6,opt,name=processing_metadata,json=processingMetadata,proto3" json:"processing_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BatchQueryResult) Reset()         { *m = BatchQueryResult{} }
func (m *BatchQueryResult) String() string { return proto.CompactTextString(m) }
func (*BatchQueryResult) ProtoMessage()    {}
func (*BatchQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{21}
}

func (m *BatchQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchQueryResult.Unmarshal(m, b)
}
func (m *BatchQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchQueryResult.Marshal(b, m, deterministic)
}
func (m *BatchQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchQueryResult.Merge(m, src)
}
func (m *BatchQueryResult) XXX_Size() int {
	return xxx_messageInfo_BatchQueryResult.Size(m)
}
func (m *BatchQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_BatchQueryResult proto.InternalMessageInfo

func (m *BatchQueryResult) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BatchQueryResult) GetOriginalQuery() string {
	if m != nil {
		return m.OriginalQuery
	}
	return ""
}

func (m *BatchQueryResult) GetProcessedQuery() string {
	if m != nil {
		return m.ProcessedQuery
	}
	return ""
}

func (m *BatchQueryResult) GetStatus() v1.ProcessingStatus {
	if m != nil {
		return m.Status
	}
	return v1.ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (m *BatchQueryResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *BatchQueryResult) GetProcessingMetadata() *ProcessingMetadata {
	if m != nil {
		return m.ProcessingMetadata
	}
	return nil
}

type BatchProcessingMetadata struct {
	TotalQueries          int32                  `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	SuccessfulProcesses   int32                  `protobuf:"varint,2,opt,name=successful_processes,json=successfulProcesses,proto3" json:"successful_processes,omitempty"`
	FailedProcesses       int32                  `protobuf:"varint,3,opt,name=failed_processes,json=failedProcesses,proto3" json:"failed_processes,omitempty"`
	TotalProcessingTimeMs int64                  `protobuf:"varint,4,opt,name=total_processing_time_ms,json=totalProcessingTimeMs,proto3" json:"total_processing_time_ms,omitempty"`
	StartedAt             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *BatchProcessingMetadata) Reset()         { *m = BatchProcessingMetadata{} }
func (m *BatchProcessingMetadata) String() string { return proto.CompactTextString(m) }
func (*BatchProcessingMetadata) ProtoMessage()    {}
func (*BatchProcessingMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{22}
}

func (m *BatchProcessingMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchProcessingMetadata.Unmarshal(m, b)
}
func (m *BatchProcessingMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchProcessingMetadata.Marshal(b, m, deterministic)
}
func (m *BatchProcessingMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchProcessingMetadata.Merge(m, src)
}
func (m *BatchProcessingMetadata) XXX_Size() int {
	return xxx_messageInfo_BatchProcessingMetadata.Size(m)
}
func (m *BatchProcessingMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchProcessingMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BatchProcessingMetadata proto.InternalMessageInfo

func (m *BatchProcessingMetadata) GetTotalQueries() int32 {
	if m != nil {
		return m.TotalQueries
	}
	return 0
}

func (m *BatchProcessingMetadata) GetSuccessfulProcesses() int32 {
	if m != nil {
		return m.SuccessfulProcesses
	}
	return 0
}

func (m *BatchProcessingMetadata) GetFailedProcesses() int32 {
	if m != nil {
		return m.FailedProcesses
	}
	return 0
}

func (m *BatchProcessingMetadata) GetTotalProcessingTimeMs() int64 {
	if m != nil {
		return m.TotalProcessingTimeMs
	}
	return 0
}

func (m *BatchProcessingMetadata) GetStartedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *BatchProcessingMetadata) GetCompletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

type ProcessorConfigResponse struct {
	Config               *ProcessorConfig       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProcessorConfigResponse) Reset()         { *m = ProcessorConfigResponse{} }
func (m *ProcessorConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessorConfigResponse) ProtoMessage()    {}
func (*ProcessorConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{23}
}

func (m *ProcessorConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorConfigResponse.Unmarshal(m, b)
}
func (m *ProcessorConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorConfigResponse.Marshal(b, m, deterministic)
}
func (m *ProcessorConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorConfigResponse.Merge(m, src)
}
func (m *ProcessorConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessorConfigResponse.Size(m)
}
func (m *ProcessorConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorConfigResponse proto.InternalMessageInfo

func (m *ProcessorConfigResponse) GetConfig() *ProcessorConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ProcessorConfigResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ProcessorConfigResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type UpdateProcessorConfigRequest struct {
	Config               *ProcessorConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	UpdateFields         []string         `protobuf:"bytes,2,rep,name=update_fields,json=updateFields,proto3" json:"update_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateProcessorConfigRequest) Reset()         { *m = UpdateProcessorConfigRequest{} }
func (m *UpdateProcessorConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProcessorConfigRequest) ProtoMessage()    {}
func (*UpdateProcessorConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{24}
}

func (m *UpdateProcessorConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProcessorConfigRequest.Unmarshal(m, b)
}
func (m *UpdateProcessorConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProcessorConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProcessorConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProcessorConfigRequest.Merge(m, src)
}
func (m *UpdateProcessorConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProcessorConfigRequest.Size(m)
}
func (m *UpdateProcessorConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProcessorConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProcessorConfigRequest proto.InternalMessageInfo

func (m *UpdateProcessorConfigRequest) GetConfig() *ProcessorConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *UpdateProcessorConfigRequest) GetUpdateFields() []string {
	if m != nil {
		return m.UpdateFields
	}
	return nil
}

type ProcessorConfig struct {
	DefaultOptions       *DefaultProcessingOptions `protobuf:"bytes,1,opt,name=default_options,json=defaultOptions,proto3" json:"default_options,omitempty"`
	ModelConfig          *ModelConfig              `protobuf:"bytes,2,opt,name=model_config,json=modelConfig,proto3" json:"model_config,omitempty"`
	PerformanceConfig    *PerformanceConfig        `protobuf:"bytes,3,opt,name=performance_config,json=performanceConfig,proto3" json:"performance_config,omitempty"`
	CustomSettings       map[string]string         `protobuf:"bytes,4,rep,name=custom_settings,json=customSettings,proto3" json:"custom_settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ProcessorConfig) Reset()         { *m = ProcessorConfig{} }
func (m *ProcessorConfig) String() string { return proto.CompactTextString(m) }
func (*ProcessorConfig) ProtoMessage()    {}
func (*ProcessorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{25}
}

func (m *ProcessorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorConfig.Unmarshal(m, b)
}
func (m *ProcessorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorConfig.Marshal(b, m, deterministic)
}
func (m *ProcessorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorConfig.Merge(m, src)
}
func (m *ProcessorConfig) XXX_Size() int {
	return xxx_messageInfo_ProcessorConfig.Size(m)
}
func (m *ProcessorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorConfig proto.InternalMessageInfo

func (m *ProcessorConfig) GetDefaultOptions() *DefaultProcessingOptions {
	if m != nil {
		return m.DefaultOptions
	}
	return nil
}

func (m *ProcessorConfig) GetModelConfig() *ModelConfig {
	if m != nil {
		return m.ModelConfig
	}
	return nil
}

func (m *ProcessorConfig) GetPerformanceConfig() *PerformanceConfig {
	if m != nil {
		return m.PerformanceConfig
	}
	return nil
}

func (m *ProcessorConfig) GetCustomSettings() map[string]string {
	if m != nil {
		return m.CustomSettings
	}
	return nil
}

type DefaultProcessingOptions struct {
	ProcessingOptions    *ProcessingOptions `protobuf:"bytes,1,opt,name=processing_options,json=processingOptions,proto3" json:"processing_options,omitempty"`
	CleaningOptions      *CleaningOptions   `protobuf:"bytes,2,opt,name=cleaning_options,json=cleaningOptions,proto3" json:"cleaning_options,omitempty"`
	RewritingOptions     *RewritingOptions  `protobuf:"bytes,3,opt,name=rewriting_options,json=rewritingOptions,proto3" json:"rewriting_options,omitempty"`
	SynonymOptions       *SynonymOptions    `protobuf:"bytes,4,opt,name=synonym_options,json=synonymOptions,proto3" json:"synonym_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DefaultProcessingOptions) Reset()         { *m = DefaultProcessingOptions{} }
func (m *DefaultProcessingOptions) String() string { return proto.CompactTextString(m) }
func (*DefaultProcessingOptions) ProtoMessage()    {}
func (*DefaultProcessingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{26}
}

func (m *DefaultProcessingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultProcessingOptions.Unmarshal(m, b)
}
func (m *DefaultProcessingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultProcessingOptions.Marshal(b, m, deterministic)
}
func (m *DefaultProcessingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultProcessingOptions.Merge(m, src)
}
func (m *DefaultProcessingOptions) XXX_Size() int {
	return xxx_messageInfo_DefaultProcessingOptions.Size(m)
}
func (m *DefaultProcessingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultProcessingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultProcessingOptions proto.InternalMessageInfo

func (m *DefaultProcessingOptions) GetProcessingOptions() *ProcessingOptions {
	if m != nil {
		return m.ProcessingOptions
	}
	return nil
}

func (m *DefaultProcessingOptions) GetCleaningOptions() *CleaningOptions {
	if m != nil {
		return m.CleaningOptions
	}
	return nil
}

func (m *DefaultProcessingOptions) GetRewritingOptions() *RewritingOptions {
	if m != nil {
		return m.RewritingOptions
	}
	return nil
}

func (m *DefaultProcessingOptions) GetSynonymOptions() *SynonymOptions {
	if m != nil {
		return m.SynonymOptions
	}
	return nil
}

type ModelConfig struct {
	RewritingModel         string                 `protobuf:"bytes,1,opt,name=rewriting_model,json=rewritingModel,proto3" json:"rewriting_model,omitempty"`
	LanguageDetectionModel string                 `protobuf:"bytes,2,opt,name=language_detection_model,json=languageDetectionModel,proto3" json:"language_detection_model,omitempty"`
	SynonymSources         []*SynonymSourceConfig `protobuf:"bytes,3,rep,name=synonym_sources,json=synonymSources,proto3" json:"synonym_sources,omitempty"`
	ModelParameters        map[string]string      `protobuf:"bytes,4,rep,name=model_parameters,json=modelParameters,proto3" json:"model_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-"`
	XXX_unrecognized       []byte                 `json:"-"`
	XXX_sizecache          int32                  `json:"-"`
}

func (m *ModelConfig) Reset()         { *m = ModelConfig{} }
func (m *ModelConfig) String() string { return proto.CompactTextString(m) }
func (*ModelConfig) ProtoMessage()    {}
func (*ModelConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{27}
}

func (m *ModelConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelConfig.Unmarshal(m, b)
}
func (m *ModelConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelConfig.Marshal(b, m, deterministic)
}
func (m *ModelConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelConfig.Merge(m, src)
}
func (m *ModelConfig) XXX_Size() int {
	return xxx_messageInfo_ModelConfig.Size(m)
}
func (m *ModelConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ModelConfig proto.InternalMessageInfo

func (m *ModelConfig) GetRewritingModel() string {
	if m != nil {
		return m.RewritingModel
	}
	return ""
}

func (m *ModelConfig) GetLanguageDetectionModel() string {
	if m != nil {
		return m.LanguageDetectionModel
	}
	return ""
}

func (m *ModelConfig) GetSynonymSources() []*SynonymSourceConfig {
	if m != nil {
		return m.SynonymSources
	}
	return nil
}

func (m *ModelConfig) GetModelParameters() map[string]string {
	if m != nil {
		return m.ModelParameters
	}
	return nil
}

type SynonymSourceConfig struct {
	SourceName           string            `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType           string            `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	ConnectionString     string            `protobuf:"bytes,3,opt,name=connection_string,json=connectionString,proto3" json:"connection_string,omitempty"`
	Configuration        map[string]string `protobuf:"bytes,4,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Enabled              bool              `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SynonymSourceConfig) Reset()         { *m = SynonymSourceConfig{} }
func (m *SynonymSourceConfig) String() string { return proto.CompactTextString(m) }
func (*SynonymSourceConfig) ProtoMessage()    {}
func (*SynonymSourceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{28}
}

func (m *SynonymSourceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SynonymSourceConfig.Unmarshal(m, b)
}
func (m *SynonymSourceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SynonymSourceConfig.Marshal(b, m, deterministic)
}
func (m *SynonymSourceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SynonymSourceConfig.Merge(m, src)
}
func (m *SynonymSourceConfig) XXX_Size() int {
	return xxx_messageInfo_SynonymSourceConfig.Size(m)
}
func (m *SynonymSourceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SynonymSourceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SynonymSourceConfig proto.InternalMessageInfo

func (m *SynonymSourceConfig) GetSourceName() string {
	if m != nil {
		return m.SourceName
	}
	return ""
}

func (m *SynonymSourceConfig) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *SynonymSourceConfig) GetConnectionString() string {
	if m != nil {
		return m.ConnectionString
	}
	return ""
}

func (m *SynonymSourceConfig) GetConfiguration() map[string]string {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *SynonymSourceConfig) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type PerformanceConfig struct {
	MaxConcurrentRequests int32    `protobuf:"varint,1,opt,name=max_concurrent_requests,json=maxConcurrentRequests,proto3" json:"max_concurrent_requests,omitempty"`
	RequestTimeoutMs      int32    `protobuf:"varint,2,opt,name=request_timeout_ms,json=requestTimeoutMs,proto3" json:"request_timeout_ms,omitempty"`
	BatchSizeLimit        int32    `protobuf:"varint,3,opt,name=batch_size_limit,json=batchSizeLimit,proto3" json:"batch_size_limit,omitempty"`
	EnableCaching         bool     `protobuf:"varint,4,opt,name=enable_caching,json=enableCaching,proto3" json:"enable_caching,omitempty"`
	CacheTtlSeconds       int32    `protobuf:"varint,5,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *PerformanceConfig) Reset()         { *m = PerformanceConfig{} }
func (m *PerformanceConfig) String() string { return proto.CompactTextString(m) }
func (*PerformanceConfig) ProtoMessage()    {}
func (*PerformanceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c1fe1485dea17f3, []int{29}
}

func (m *PerformanceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerformanceConfig.Unmarshal(m, b)
}
func (m *PerformanceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerformanceConfig.Marshal(b, m, deterministic)
}
func (m *PerformanceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerformanceConfig.Merge(m, src)
}
func (m *PerformanceConfig) XXX_Size() int {
	return xxx_messageInfo_PerformanceConfig.Size(m)
}
func (m *PerformanceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PerformanceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PerformanceConfig proto.InternalMessageInfo

func (m *PerformanceConfig) GetMaxConcurrentRequests() int32 {
	if m != nil {
		return m.MaxConcurrentRequests
	}
	return 0
}

func (m *PerformanceConfig) GetRequestTimeoutMs() int32 {
	if m != nil {
		return m.RequestTimeoutMs
	}
	return 0
}

func (m *PerformanceConfig) GetBatchSizeLimit() int32 {
	if m != nil {
		return m.BatchSizeLimit
	}
	return 0
}

func (m *PerformanceConfig) GetEnableCaching() bool {
	if m != nil {
		return m.EnableCaching
	}
	return false
}

func (m *PerformanceConfig) GetCacheTtlSeconds() int32 {
	if m != nil {
		return m.CacheTtlSeconds
	}
	return 0
}

func init() {
	proto.RegisterType((*ProcessQueryRequest)(nil), "api.preprocessor.v1.ProcessQueryRequest")
	proto.RegisterType((*ProcessingOptions)(nil), "api.preprocessor.v1.ProcessingOptions")
	proto.RegisterType((*CleaningOptions)(nil), "api.preprocessor.v1.CleaningOptions")
	proto.RegisterType((*RewritingOptions)(nil), "api.preprocessor.v1.RewritingOptions")
	proto.RegisterType((*SynonymOptions)(nil), "api.preprocessor.v1.SynonymOptions")
	proto.RegisterType((*ProcessQueryResponse)(nil), "api.preprocessor.v1.ProcessQueryResponse")
	proto.RegisterType((*ProcessingStep)(nil), "api.preprocessor.v1.ProcessingStep")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.ProcessingStep.StepMetadataEntry")
	proto.RegisterType((*ProcessingMetadata)(nil), "api.preprocessor.v1.ProcessingMetadata")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.ProcessingMetadata.DebugInfoEntry")
	proto.RegisterType((*QueryAlternative)(nil), "api.preprocessor.v1.QueryAlternative")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.QueryAlternative.MetadataEntry")
	proto.RegisterType((*RewriteQueryRequest)(nil), "api.preprocessor.v1.RewriteQueryRequest")
	proto.RegisterType((*RewriteQueryResponse)(nil), "api.preprocessor.v1.RewriteQueryResponse")
	proto.RegisterType((*RewrittenQuery)(nil), "api.preprocessor.v1.RewrittenQuery")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.RewrittenQuery.MetadataEntry")
	proto.RegisterType((*RewriteChange)(nil), "api.preprocessor.v1.RewriteChange")
	proto.RegisterType((*RewritingMetadata)(nil), "api.preprocessor.v1.RewritingMetadata")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.RewritingMetadata.DebugInfoEntry")
	proto.RegisterType((*ExpandSynonymsRequest)(nil), "api.preprocessor.v1.ExpandSynonymsRequest")
	proto.RegisterType((*ExpandSynonymsResponse)(nil), "api.preprocessor.v1.ExpandSynonymsResponse")
	proto.RegisterType((*ExpandedWord)(nil), "api.preprocessor.v1.ExpandedWord")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.ExpandedWord.WordMetadataEntry")
	proto.RegisterType((*Synonym)(nil), "api.preprocessor.v1.Synonym")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.Synonym.MetadataEntry")
	proto.RegisterType((*SynonymMetadata)(nil), "api.preprocessor.v1.SynonymMetadata")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.SynonymMetadata.DebugInfoEntry")
	proto.RegisterType((*ProcessBatchQueriesRequest)(nil), "api.preprocessor.v1.ProcessBatchQueriesRequest")
	proto.RegisterType((*ProcessBatchQueriesResponse)(nil), "api.preprocessor.v1.ProcessBatchQueriesResponse")
	proto.RegisterType((*BatchQueryResult)(nil), "api.preprocessor.v1.BatchQueryResult")
	proto.RegisterType((*BatchProcessingMetadata)(nil), "api.preprocessor.v1.BatchProcessingMetadata")
	proto.RegisterType((*ProcessorConfigResponse)(nil), "api.preprocessor.v1.ProcessorConfigResponse")
	proto.RegisterType((*UpdateProcessorConfigRequest)(nil), "api.preprocessor.v1.UpdateProcessorConfigRequest")
	proto.RegisterType((*ProcessorConfig)(nil), "api.preprocessor.v1.ProcessorConfig")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.ProcessorConfig.CustomSettingsEntry")
	proto.RegisterType((*DefaultProcessingOptions)(nil), "api.preprocessor.v1.DefaultProcessingOptions")
	proto.RegisterType((*ModelConfig)(nil), "api.preprocessor.v1.ModelConfig")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.ModelConfig.ModelParametersEntry")
	proto.RegisterType((*SynonymSourceConfig)(nil), "api.preprocessor.v1.SynonymSourceConfig")
	proto.RegisterMapType((map[string]string)(nil), "api.preprocessor.v1.SynonymSourceConfig.ConfigurationEntry")
	proto.RegisterType((*PerformanceConfig)(nil), "api.preprocessor.v1.PerformanceConfig")
}

func init() {
	proto.RegisterFile("v1/preprocessor_svc.proto", fileDescriptor_6c1fe1485dea17f3)
}

var fileDescriptor_6c1fe1485dea17f3 = []byte{
	// 2969 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x5a, 0x4b, 0x73, 0x1b, 0xc7,
	0x11, 0x16, 0x96, 0x04, 0x49, 0x34, 0x40, 0x3c, 0x86, 0x0f, 0xc1, 0x90, 0x6c, 0xc9, 0xb0, 0x1d,
	0xd3, 0x92, 0x05, 0x9a, 0x52, 0x6c, 0x2b, 0xb6, 0x5c, 0xb6, 0x48, 0x49, 0x91, 0x2a, 0xa6, 0x45,
	0x2f, 0xa9, 0xd8, 0xe5, 0xaa, 0xd4, 0x66, 0xb4, 0x3b, 0x00, 0xb6, 0xbc, 0x2f, 0xef, 0xce, 0x42,
	0xa4, 0x4f, 0x71, 0x6e, 0xce, 0x25, 0x55, 0x89, 0x2b, 0xb9, 0xc4, 0xe7, 0x1c, 0xf2, 0xae, 0xca,
	0x3f, 0x70, 0x55, 0x72, 0xcc, 0xc1, 0x7f, 0xc1, 0x97, 0xdc, 0x5d, 0x39, 0xe8, 0x94, 0x9a, 0xd7,
	0x3e, 0x80, 0x25, 0x0c, 0x5a, 0xd2, 0x85, 0xc5, 0xf9, 0xba, 0x7b, 0xb6, 0xa7, 0xbb, 0xa7, 0xa7,
	0x7b, 0x06, 0xf0, 0xd4, 0x68, 0x6b, 0x33, 0x08, 0x49, 0x10, 0xfa, 0x26, 0x89, 0x22, 0x3f, 0x34,
	0xa2, 0x91, 0xd9, 0x0b, 0x42, 0x9f, 0xfa, 0x68, 0x05, 0x07, 0x76, 0x2f, 0x4b, 0xeb, 0x8d, 0xb6,
	0x3a, 0x67, 0x07, 0xbe, 0x3f, 0x70, 0xc8, 0x26, 0x0e, 0xec, 0x4d, 0xec, 0x79, 0x3e, 0xc5, 0xd4,
	0xf6, 0xbd, 0x48, 0x88, 0x74, 0xce, 0x48, 0x2a, 0x1f, 0xdd, 0x8f, 0xfb, 0x9b, 0xc4, 0x0d, 0xe8,
	0x91, 0x24, 0x9e, 0x1b, 0x27, 0x52, 0xdb, 0x25, 0x11, 0xc5, 0x6e, 0x20, 0x19, 0x3a, 0x6c, 0x52,
	0xd3, 0x77, 0x5d, 0xdf, 0xdb, 0x1c, 0x6d, 0xc9, 0xff, 0x8a, 0x69, 0x24, 0x0c, 0xfd, 0x50, 0x7d,
	0xf5, 0xf4, 0x08, 0x3b, 0xb6, 0x85, 0x29, 0xd9, 0x54, 0xff, 0x08, 0x42, 0xf7, 0x2f, 0x25, 0x58,
	0xd9, 0x13, 0xda, 0xbf, 0x1f, 0x93, 0xf0, 0x48, 0x27, 0x9f, 0xc4, 0x24, 0xa2, 0xe8, 0x69, 0x28,
	0x7f, 0xc2, 0xc6, 0xed, 0xd2, 0xf9, 0xd2, 0x46, 0x65, 0x7b, 0xf1, 0xe1, 0xf6, 0x7c, 0xa8, 0x35,
	0x4b, 0xba, 0x40, 0xd1, 0x3b, 0xb0, 0xe8, 0x07, 0x7c, 0x59, 0x6d, 0xed, 0x7c, 0x69, 0xa3, 0x7a,
	0xf9, 0x07, 0xbd, 0x02, 0x53, 0xf4, 0xe4, 0xcc, 0xb6, 0x37, 0xb8, 0x2b, 0xb8, 0x75, 0x25, 0x86,
	0x5e, 0x85, 0x45, 0xd3, 0xf7, 0x28, 0x39, 0xa4, 0xed, 0x39, 0x3e, 0xc3, 0x19, 0x3e, 0x83, 0x5c,
	0xd1, 0x68, 0xab, 0xc7, 0xd5, 0xd9, 0x11, 0x2c, 0xba, 0xe2, 0xed, 0xfe, 0x63, 0x1e, 0x5a, 0x13,
	0xb3, 0xa2, 0x17, 0xa1, 0x41, 0x3c, 0x7c, 0xdf, 0x21, 0x86, 0xe9, 0x10, 0xec, 0xd9, 0xde, 0x80,
	0xeb, 0xbd, 0xa4, 0xd7, 0x05, 0xbc, 0x23, 0x51, 0xf4, 0x12, 0x34, 0x25, 0x63, 0x48, 0x1e, 0x84,
	0x36, 0x65, 0x9c, 0x1a, 0xe7, 0x94, 0x13, 0xe8, 0x0a, 0x46, 0x57, 0xa1, 0x2d, 0x59, 0xa3, 0x23,
	0xcf, 0xf7, 0x8e, 0x5c, 0x83, 0x1c, 0x06, 0xd8, 0x8b, 0x6c, 0xdf, 0xe3, 0x1a, 0x2f, 0xe9, 0xeb,
	0x82, 0xbe, 0x2f, 0xc8, 0x37, 0x15, 0x15, 0xbd, 0x06, 0xa7, 0x95, 0x64, 0x40, 0x1c, 0xc7, 0x30,
	0xfd, 0x30, 0x24, 0x26, 0xd3, 0xb4, 0x3d, 0xcf, 0x05, 0xd7, 0xa4, 0x20, 0xa3, 0xee, 0x24, 0x44,
	0xf4, 0x06, 0x3c, 0x25, 0xe5, 0x1c, 0xec, 0x0d, 0x62, 0x3c, 0x20, 0x86, 0x45, 0xa8, 0x94, 0x2c,
	0x73, 0x49, 0x39, 0xf1, 0xbb, 0x92, 0x7e, 0x43, 0x91, 0x99, 0x05, 0x28, 0x0e, 0x07, 0x84, 0x26,
	0xb2, 0xed, 0x05, 0xe6, 0x39, 0xbd, 0x2e, 0x60, 0x25, 0x81, 0xee, 0x42, 0x53, 0xd9, 0xc8, 0x50,
	0x2e, 0x5c, 0xe4, 0x0e, 0x78, 0xbe, 0xd0, 0x85, 0xca, 0x74, 0xca, 0x81, 0x0d, 0x33, 0x0f, 0x20,
	0x1d, 0x5a, 0x89, 0x2d, 0x93, 0x19, 0x97, 0xf8, 0x8c, 0x2f, 0x14, 0xce, 0x98, 0x98, 0x58, 0x4d,
	0xd9, 0x0c, 0xc7, 0x10, 0xf4, 0x2e, 0x34, 0x94, 0xd1, 0xd5, 0x8c, 0x15, 0x3e, 0xe3, 0x73, 0x85,
	0x33, 0x4a, 0x0f, 0xa8, 0xf9, 0xea, 0x51, 0x6e, 0xdc, 0xfd, 0x42, 0x83, 0xc6, 0xd8, 0x32, 0xd0,
	0x2b, 0xb0, 0x1a, 0x12, 0xd7, 0x1f, 0x71, 0x1f, 0x99, 0x36, 0x76, 0x0c, 0x73, 0x88, 0xc3, 0x48,
	0x86, 0x0d, 0x12, 0xb4, 0x7d, 0x41, 0xda, 0x61, 0x14, 0xb4, 0x05, 0xab, 0x9e, 0x1f, 0xba, 0xd8,
	0xb1, 0x3f, 0x25, 0xc6, 0x83, 0xa1, 0x4d, 0x49, 0x14, 0x60, 0x93, 0xc8, 0xf0, 0x59, 0x49, 0x68,
	0x1f, 0x24, 0x24, 0xf4, 0x2c, 0xd4, 0xfa, 0xf6, 0xa1, 0x41, 0x3c, 0xd3, 0xb7, 0x58, 0xa4, 0x89,
	0xb0, 0xa9, 0xf6, 0xed, 0xc3, 0x9b, 0x12, 0x42, 0x17, 0x99, 0xf5, 0xb8, 0x1e, 0x56, 0x1c, 0x38,
	0xb6, 0x89, 0x29, 0x89, 0x64, 0x94, 0x34, 0x05, 0xe1, 0x46, 0x82, 0xa3, 0xa7, 0x01, 0x22, 0xea,
	0x07, 0xc6, 0x03, 0x3f, 0xb4, 0xa2, 0x76, 0xf9, 0xfc, 0xdc, 0x46, 0x45, 0xaf, 0x30, 0xe4, 0x03,
	0x06, 0xa0, 0x4b, 0x80, 0x94, 0x16, 0x3c, 0xe5, 0x18, 0x7d, 0x3f, 0x74, 0x65, 0x18, 0xb4, 0x72,
	0x94, 0x5b, 0x7e, 0xe8, 0x76, 0x3f, 0xd7, 0xa0, 0x39, 0xee, 0x0b, 0xb6, 0x41, 0x84, 0x37, 0x88,
	0x11, 0xd1, 0x10, 0x53, 0x32, 0x90, 0x29, 0x40, 0x6f, 0x48, 0x7c, 0x5f, 0xc2, 0x68, 0x1b, 0x56,
	0x4d, 0xdf, 0xeb, 0xdb, 0x16, 0xf1, 0x4c, 0x62, 0xd0, 0x61, 0x48, 0xa2, 0xa1, 0xef, 0x58, 0xdc,
	0x20, 0xda, 0x76, 0xe3, 0xe1, 0x76, 0x0d, 0xe0, 0xe9, 0x53, 0xa7, 0x7e, 0xf1, 0xf6, 0xa5, 0x53,
	0xa7, 0x4e, 0x9d, 0xd2, 0x57, 0x52, 0xe6, 0x03, 0xc5, 0x8b, 0x7e, 0x08, 0x4d, 0x17, 0x1f, 0x1a,
	0xd8, 0xa1, 0x24, 0xf4, 0x30, 0xb5, 0x47, 0x24, 0xe2, 0x56, 0x2a, 0x6f, 0x57, 0x1e, 0x6e, 0x2f,
	0x74, 0xe6, 0xdb, 0xb0, 0x51, 0xd2, 0x1b, 0x2e, 0x3e, 0xbc, 0x9e, 0xe1, 0x60, 0xc1, 0x1e, 0x84,
	0x24, 0x22, 0xe1, 0x88, 0x18, 0xb6, 0x47, 0x89, 0x47, 0xa5, 0xc9, 0xea, 0x0a, 0xbe, 0xc3, 0x51,
	0xc6, 0x68, 0xf9, 0x2e, 0xb6, 0x3d, 0xe3, 0x63, 0x72, 0x94, 0xb5, 0x5a, 0x5d, 0xc0, 0x3f, 0x91,
	0x68, 0xf7, 0x6f, 0x1a, 0xd4, 0xf3, 0x51, 0xc4, 0x64, 0x55, 0x0c, 0x46, 0x7e, 0x1c, 0x9a, 0x84,
	0x05, 0x07, 0x97, 0x95, 0xf0, 0xbe, 0x40, 0x99, 0x1d, 0x22, 0xdb, 0xb5, 0x1d, 0x1c, 0xda, 0xf4,
	0x68, 0x06, 0x3b, 0xa4, 0xcc, 0xa9, 0x1d, 0xae, 0xc1, 0x1a, 0xb3, 0x83, 0x9c, 0x39, 0x32, 0x02,
	0x12, 0x72, 0x2f, 0xe7, 0x8d, 0xb1, 0xba, 0x51, 0xd2, 0x91, 0x8b, 0x0f, 0xa5, 0xa6, 0xd1, 0x1e,
	0x09, 0x99, 0xe7, 0x99, 0xd3, 0x6c, 0xcf, 0x74, 0x62, 0x8b, 0x18, 0xc3, 0xa3, 0x80, 0x93, 0xa4,
	0x41, 0x1a, 0x12, 0xbf, 0x2d, 0x61, 0x16, 0x6f, 0x19, 0x56, 0x12, 0x72, 0x5e, 0x91, 0x5b, 0x9a,
	0x29, 0xaf, 0xc0, 0x51, 0x07, 0x96, 0xc6, 0xb2, 0x49, 0x32, 0xee, 0xfe, 0x4b, 0x83, 0xd5, 0xfc,
	0xc1, 0x11, 0x05, 0xbe, 0x17, 0x11, 0xf4, 0x02, 0xd4, 0xfd, 0xd0, 0x1e, 0xd8, 0x1e, 0x76, 0x8c,
	0xcc, 0x11, 0xa2, 0x2f, 0x2b, 0x94, 0xb3, 0x0b, 0x1f, 0x72, 0x71, 0x62, 0x49, 0x3e, 0x4d, 0x24,
	0xac, 0x04, 0x16, 0x8c, 0xef, 0x41, 0x33, 0x48, 0x12, 0xbe, 0x11, 0x51, 0x12, 0xb0, 0x10, 0x99,
	0x3b, 0x36, 0x19, 0xa4, 0xa7, 0xc3, 0x3e, 0x25, 0x81, 0xde, 0x08, 0x72, 0xe3, 0x08, 0xed, 0xc0,
	0x92, 0x4b, 0x28, 0xb6, 0x30, 0xc5, 0xdc, 0x48, 0xd5, 0xcb, 0x2f, 0x7e, 0xc7, 0x3c, 0xbb, 0x92,
	0x5d, 0x4f, 0x04, 0xd1, 0x1d, 0xa8, 0xe5, 0x62, 0xb6, 0xcc, 0x15, 0x2a, 0xce, 0x77, 0x7c, 0x19,
	0x99, 0xf8, 0xd5, 0x73, 0xa2, 0xdd, 0x6f, 0x35, 0xa8, 0xe7, 0x75, 0x46, 0x67, 0xa0, 0xc2, 0xd6,
	0x69, 0x78, 0xd8, 0x25, 0xd2, 0x7a, 0x4b, 0x0c, 0x78, 0x0f, 0xbb, 0x84, 0x25, 0x01, 0xdb, 0x0b,
	0x62, 0x6a, 0xf0, 0xb3, 0x53, 0xd8, 0xac, 0xc2, 0x91, 0x03, 0x72, 0x48, 0xd1, 0x39, 0xa8, 0xfa,
	0x31, 0x4d, 0xe8, 0x73, 0x9c, 0x0e, 0x02, 0xe2, 0x0c, 0x2f, 0x41, 0x33, 0xb3, 0x6d, 0x23, 0xd3,
	0x0f, 0x09, 0xb7, 0x83, 0xa6, 0x37, 0x52, 0x7c, 0x9f, 0xc1, 0xe8, 0x23, 0x58, 0xe6, 0x7a, 0x24,
	0xf6, 0x12, 0xcb, 0x7c, 0x75, 0x06, 0xbb, 0xf7, 0xd8, 0x1f, 0x65, 0xb8, 0x9b, 0x1e, 0x0d, 0x8f,
	0xf4, 0x5a, 0x94, 0x81, 0xd0, 0x5b, 0x50, 0x4b, 0xfd, 0x8f, 0x29, 0x8f, 0xaf, 0xea, 0xe5, 0x4e,
	0x4f, 0x54, 0x40, 0x3d, 0x55, 0x01, 0xf5, 0x0e, 0x54, 0x05, 0xa4, 0x57, 0x13, 0xfe, 0xeb, 0xb4,
	0xf3, 0x36, 0xb4, 0x26, 0xbe, 0x80, 0x9a, 0x30, 0xf7, 0x31, 0x51, 0xf1, 0xc6, 0xfe, 0x45, 0xab,
	0x50, 0x1e, 0x61, 0x27, 0x26, 0xd2, 0x4e, 0x62, 0xf0, 0x86, 0x76, 0xb5, 0xd4, 0xfd, 0xe3, 0x1c,
	0xa0, 0x49, 0x17, 0xb3, 0xfd, 0x21, 0xce, 0x5c, 0x62, 0xa5, 0x27, 0xa9, 0x98, 0xb0, 0xa9, 0x08,
	0xc9, 0x59, 0x7a, 0x05, 0xd6, 0x32, 0xa1, 0x99, 0x5a, 0x4f, 0x6c, 0x7d, 0x7d, 0x35, 0x25, 0xee,
	0x24, 0x34, 0xf4, 0x32, 0xa0, 0x8c, 0x10, 0x2b, 0xf0, 0x0c, 0x57, 0x24, 0xbd, 0x39, 0x3d, 0x13,
	0xe9, 0x6c, 0xdd, 0xbb, 0x3c, 0xa7, 0xe3, 0x20, 0x70, 0x6c, 0x62, 0xa9, 0x7c, 0x6c, 0xf3, 0x03,
	0x82, 0x25, 0xa2, 0x96, 0xa4, 0xec, 0x27, 0x04, 0x74, 0x0f, 0xc0, 0x22, 0xf7, 0xe3, 0x81, 0x61,
	0x7b, 0x7d, 0x5f, 0xba, 0xeb, 0xb5, 0x19, 0xc3, 0xbb, 0x77, 0x83, 0x49, 0xde, 0xf1, 0xfa, 0xbe,
	0xf0, 0x57, 0xc5, 0x52, 0xe3, 0x47, 0x75, 0xd6, 0x35, 0xa8, 0xe7, 0xe7, 0x3e, 0x91, 0xa7, 0x7e,
	0xaf, 0x41, 0x73, 0x7c, 0x0f, 0xb1, 0x5d, 0xc0, 0x93, 0x86, 0x88, 0x72, 0x31, 0x4f, 0x85, 0x23,
	0xc7, 0x06, 0xb9, 0x56, 0x1c, 0xe4, 0x17, 0xa1, 0x35, 0x20, 0x1e, 0x09, 0xc5, 0x91, 0xe9, 0x12,
	0x3a, 0xf4, 0x2d, 0xb9, 0x6d, 0x9a, 0x29, 0x61, 0x97, 0xe3, 0xe8, 0x6e, 0x2e, 0x79, 0x30, 0xeb,
	0x5e, 0x99, 0x69, 0xcf, 0xf7, 0xf2, 0x5b, 0x21, 0x99, 0xa4, 0xf3, 0x26, 0x2c, 0x7f, 0xff, 0x18,
	0xfe, 0x73, 0x09, 0x56, 0xc4, 0x09, 0x4e, 0x4e, 0x52, 0xbc, 0xbf, 0x3d, 0x5e, 0xbc, 0xcf, 0x58,
	0xa7, 0x3d, 0x6a, 0xed, 0xfe, 0x75, 0x09, 0x56, 0xf3, 0xea, 0x9e, 0xec, 0xc8, 0xd8, 0x53, 0x95,
	0x26, 0x25, 0x1e, 0xe7, 0x63, 0x5b, 0x41, 0x9b, 0x72, 0x14, 0xe8, 0x8a, 0x5b, 0x7c, 0xae, 0x19,
	0x66, 0xc7, 0x36, 0x3f, 0xba, 0x53, 0x77, 0xce, 0x4d, 0xe9, 0x63, 0x12, 0x53, 0x4c, 0x1e, 0x05,
	0xdd, 0x7f, 0x6b, 0x50, 0xcf, 0x7f, 0xe8, 0x31, 0x06, 0xe7, 0xb3, 0x50, 0x53, 0xe5, 0x18, 0x3d,
	0x0a, 0x88, 0x8c, 0xcb, 0xaa, 0xc4, 0x0e, 0x8e, 0x02, 0x82, 0xae, 0xc1, 0xa2, 0x39, 0xc4, 0xde,
	0x40, 0xa6, 0x85, 0xea, 0xe5, 0xee, 0x94, 0x25, 0x90, 0x1d, 0xce, 0xaa, 0x2b, 0x11, 0xb4, 0x9b,
	0xb1, 0x80, 0x48, 0x17, 0x5b, 0x33, 0x98, 0xf2, 0xc9, 0x84, 0xf3, 0x3f, 0x4b, 0xb0, 0x9c, 0x53,
	0x13, 0x3d, 0x07, 0x49, 0x08, 0x64, 0x6d, 0x59, 0x53, 0x20, 0x37, 0xe7, 0x0b, 0x50, 0x4f, 0xc3,
	0x22, 0x73, 0x28, 0x2e, 0x27, 0xa8, 0x3a, 0x18, 0xc5, 0xa2, 0xb3, 0x96, 0x04, 0x01, 0x71, 0x43,
	0xae, 0xc3, 0x42, 0x48, 0x70, 0x24, 0xbb, 0xb4, 0x8a, 0x2e, 0x47, 0xe8, 0x19, 0x80, 0x4c, 0x6a,
	0x2f, 0x73, 0x47, 0x65, 0x90, 0xee, 0x97, 0x1a, 0xb4, 0x26, 0x02, 0x84, 0xc5, 0x80, 0xeb, 0x5b,
	0xc4, 0x31, 0xe2, 0x88, 0x58, 0x2a, 0x06, 0x38, 0x72, 0x2f, 0x22, 0xd6, 0x31, 0xa7, 0x80, 0x76,
	0xcc, 0x29, 0xc0, 0xea, 0x58, 0x75, 0x2a, 0xd9, 0x51, 0x14, 0x13, 0x51, 0x02, 0xb1, 0x3a, 0x56,
	0xc2, 0x77, 0x38, 0x8a, 0x0e, 0x72, 0xf9, 0x7f, 0x7e, 0xca, 0x71, 0x3d, 0xa1, 0xf1, 0xf1, 0xe9,
	0xff, 0x11, 0xf3, 0xf7, 0x17, 0x25, 0x58, 0xe3, 0xcd, 0xb1, 0xa5, 0xea, 0x56, 0x95, 0xa7, 0xce,
	0xc0, 0x7c, 0xea, 0xd5, 0x34, 0x4d, 0x71, 0x10, 0xbd, 0x35, 0x9e, 0xa5, 0x66, 0xea, 0xfd, 0x92,
	0x1c, 0x75, 0x0e, 0xaa, 0x7d, 0xdf, 0x8c, 0x23, 0xd9, 0x2c, 0x09, 0x73, 0x01, 0x87, 0x78, 0xb7,
	0xd4, 0xfd, 0xb6, 0x04, 0xeb, 0xe3, 0x6a, 0xc9, 0x7c, 0x34, 0x53, 0xd8, 0xdd, 0x86, 0x3a, 0xbf,
	0x10, 0xb0, 0x88, 0x25, 0xbf, 0x21, 0x52, 0xd1, 0xb3, 0x85, 0x6a, 0xde, 0x94, 0xac, 0xec, 0xdb,
	0xfa, 0x32, 0xc9, 0x8c, 0x78, 0xcf, 0x95, 0xcc, 0xa4, 0xd2, 0x9a, 0xd0, 0xb7, 0xa1, 0x70, 0x95,
	0xb0, 0xde, 0x99, 0x28, 0x5e, 0x9f, 0x9f, 0x66, 0x95, 0x82, 0x74, 0xf5, 0x57, 0x0d, 0x6a, 0x59,
	0x65, 0x72, 0x8b, 0xe5, 0x2d, 0xc7, 0xd8, 0x62, 0x39, 0xd3, 0x55, 0x58, 0x52, 0xbd, 0x89, 0x5c,
	0xe6, 0xd9, 0x69, 0xdf, 0xd5, 0x13, 0x6e, 0xf4, 0x3c, 0xd4, 0x03, 0x1c, 0x52, 0xc3, 0xef, 0xb3,
	0x4e, 0x9b, 0x98, 0x43, 0xb9, 0xf3, 0x6a, 0x0c, 0xbd, 0xdb, 0xdf, 0xe7, 0x18, 0xfa, 0x10, 0x96,
	0xd9, 0xb7, 0x8d, 0x99, 0x0e, 0xd7, 0xac, 0xfa, 0x3d, 0xf6, 0x67, 0xac, 0xce, 0x7c, 0x90, 0x81,
	0x58, 0xa1, 0x38, 0xc1, 0x72, 0xa2, 0xf0, 0xfd, 0x95, 0x06, 0x8b, 0x72, 0x59, 0x08, 0xc1, 0x7c,
	0xc6, 0x44, 0xfc, 0x7f, 0xe6, 0xbd, 0x4c, 0xfb, 0x97, 0xcb, 0xe6, 0x29, 0x2e, 0xb2, 0xf9, 0x3a,
	0x2c, 0x88, 0x56, 0x52, 0xda, 0x40, 0x8e, 0x98, 0x0b, 0x42, 0xe2, 0x88, 0x02, 0x84, 0x27, 0x27,
	0x91, 0x80, 0x6a, 0x0a, 0xe4, 0xe9, 0xe9, 0xd6, 0x44, 0xa6, 0xbe, 0x30, 0xcd, 0x05, 0x4f, 0x26,
	0x45, 0x7f, 0xad, 0x41, 0x63, 0x2c, 0xb6, 0xd8, 0x19, 0x25, 0x1b, 0x64, 0x95, 0xeb, 0x58, 0xe8,
	0x56, 0x25, 0xc6, 0xb3, 0xdd, 0x2b, 0xb0, 0x4a, 0x7d, 0x8a, 0x9d, 0xb4, 0xc1, 0xed, 0xfb, 0xb1,
	0x27, 0x5a, 0xe4, 0xb2, 0x8e, 0x38, 0x4d, 0xed, 0xc2, 0x5b, 0x8c, 0x72, 0xc2, 0x2a, 0xf9, 0x22,
	0xb4, 0xc6, 0xae, 0xcc, 0x88, 0x25, 0x8d, 0xd8, 0x74, 0x72, 0x77, 0x65, 0xc4, 0x42, 0x7a, 0x41,
	0x8d, 0x7c, 0x65, 0x96, 0x5d, 0xf4, 0xc4, 0x32, 0xe4, 0x97, 0x25, 0xe8, 0xc8, 0x7a, 0x7c, 0x1b,
	0x53, 0x73, 0x28, 0x77, 0xbb, 0x4a, 0x93, 0x5d, 0x58, 0x54, 0x69, 0x81, 0xdb, 0x76, 0x7b, 0xe9,
	0xe1, 0x76, 0xf9, 0x37, 0x25, 0x6d, 0xa9, 0xa4, 0x2b, 0xc2, 0x63, 0xb8, 0x90, 0x7d, 0x0a, 0x96,
	0xee, 0xb3, 0x8f, 0x1b, 0xb6, 0x2a, 0x7f, 0x17, 0xf9, 0xf8, 0x8e, 0xd5, 0xfd, 0xaa, 0x04, 0x67,
	0x0a, 0xf5, 0x93, 0xf9, 0x32, 0x2b, 0x5a, 0xca, 0x89, 0xb2, 0x5a, 0x33, 0x24, 0x51, 0xec, 0x50,
	0x95, 0x37, 0x8a, 0x6b, 0xcd, 0x64, 0x5a, 0x56, 0x14, 0xc6, 0x0e, 0xd5, 0x95, 0x14, 0xba, 0x3d,
	0x51, 0xa2, 0xbd, 0x7c, 0xfc, 0x0c, 0xd3, 0x7a, 0xf6, 0xee, 0xdf, 0x35, 0x68, 0x8e, 0x7f, 0x87,
	0x39, 0xc5, 0xf6, 0x2c, 0x72, 0xc8, 0xf5, 0x2e, 0xeb, 0x62, 0x50, 0x50, 0x90, 0x6a, 0x33, 0xde,
	0x61, 0xcc, 0x15, 0xde, 0x61, 0xbc, 0x0e, 0x0b, 0x11, 0xc5, 0x34, 0x16, 0xd7, 0x32, 0xf5, 0xcb,
	0xe7, 0xc6, 0xea, 0xe5, 0x6c, 0xef, 0xcc, 0xd8, 0x74, 0xc9, 0xce, 0x32, 0x03, 0xbf, 0xc7, 0x37,
	0x5c, 0x12, 0x45, 0xac, 0x15, 0x2d, 0x8b, 0xcc, 0xc0, 0xc1, 0x5d, 0x81, 0xa1, 0x0f, 0x61, 0x25,
	0xb3, 0x57, 0x12, 0x6b, 0x2d, 0x9c, 0xec, 0x72, 0x23, 0xb3, 0xdf, 0x14, 0xd6, 0xfd, 0x8f, 0x06,
	0xa7, 0x8f, 0x31, 0x2c, 0x53, 0x4d, 0xec, 0xe9, 0x34, 0x36, 0x99, 0x05, 0x6b, 0x1c, 0x54, 0xe7,
	0xd5, 0x16, 0xac, 0x46, 0xb1, 0xc9, 0x44, 0xfb, 0xb1, 0x63, 0x28, 0xab, 0x44, 0x72, 0xe3, 0xaf,
	0xa4, 0xb4, 0x3d, 0x45, 0x62, 0xf9, 0xb4, 0x8f, 0x6d, 0x87, 0x58, 0x19, 0x76, 0x7e, 0x0b, 0xa6,
	0x37, 0x04, 0x9e, 0xb2, 0xbe, 0x0e, 0x6d, 0xa1, 0x42, 0x41, 0xaa, 0x98, 0xe7, 0xa9, 0x62, 0x8d,
	0xd3, 0xf7, 0xc6, 0xf3, 0xc5, 0x8f, 0x00, 0x22, 0x8a, 0x43, 0x2a, 0xba, 0xd9, 0xf2, 0x77, 0x76,
	0xb3, 0x15, 0xc9, 0x7d, 0x9d, 0x95, 0x25, 0x35, 0xd3, 0x77, 0x03, 0x87, 0xd0, 0x99, 0x5b, 0xe1,
	0x84, 0xff, 0x3a, 0x65, 0x2d, 0xdb, 0xe9, 0x3d, 0xe5, 0x09, 0x7e, 0x2b, 0x30, 0x48, 0xb6, 0xd1,
	0x35, 0x58, 0xe0, 0x65, 0xa5, 0x78, 0xbc, 0x38, 0xee, 0x68, 0x1f, 0x97, 0x96, 0x32, 0xa8, 0x0d,
	0x8b, 0x23, 0x12, 0xf2, 0xe7, 0x09, 0x11, 0xac, 0x6a, 0xc8, 0x56, 0x1b, 0x07, 0x16, 0x96, 0x0a,
	0xcf, 0x7d, 0xf7, 0x6a, 0x25, 0xf7, 0x75, 0xda, 0xfd, 0xac, 0x04, 0x67, 0xef, 0xf1, 0xd1, 0x84,
	0xd2, 0x22, 0x37, 0x3d, 0x9a, 0xce, 0xcf, 0xc1, 0xb2, 0xf8, 0x96, 0xd1, 0xb7, 0x89, 0x23, 0x4b,
	0xa8, 0x8a, 0x5e, 0x13, 0xe0, 0x2d, 0x8e, 0x75, 0xff, 0x34, 0x07, 0x8d, 0xb1, 0x09, 0xd0, 0x4f,
	0x59, 0x41, 0xdc, 0xc7, 0xb1, 0x43, 0x93, 0x07, 0x02, 0xf1, 0xfd, 0x4b, 0x85, 0xdf, 0xbf, 0x21,
	0x78, 0x27, 0xb3, 0x5f, 0x5d, 0xce, 0xa2, 0x2e, 0x7d, 0x77, 0xa0, 0x26, 0xaa, 0x76, 0xb9, 0x28,
	0x91, 0x4b, 0xcf, 0x17, 0x4e, 0xba, 0xcb, 0x18, 0xe5, 0x82, 0xaa, 0x6e, 0x3a, 0x40, 0xf7, 0x00,
	0x05, 0x24, 0xec, 0xfb, 0xa1, 0x8b, 0x59, 0x83, 0x27, 0xa7, 0x9a, 0xd6, 0x5f, 0xee, 0xa5, 0xec,
	0x72, 0xc2, 0x56, 0x30, 0x0e, 0x21, 0x0c, 0x0d, 0x33, 0x8e, 0xa8, 0xef, 0x1a, 0x11, 0xa1, 0xac,
	0x72, 0x57, 0x0d, 0xdf, 0xd5, 0x59, 0x6c, 0xde, 0xdb, 0xe1, 0xb2, 0xfb, 0x52, 0x54, 0x9c, 0x60,
	0x75, 0x33, 0x07, 0x76, 0xae, 0xc3, 0x4a, 0x01, 0xdb, 0x89, 0xce, 0xb2, 0x6f, 0x34, 0x68, 0x1f,
	0x67, 0x6e, 0x6e, 0x99, 0x74, 0xab, 0xe6, 0x3d, 0x37, 0xeb, 0x81, 0xd5, 0x0a, 0x26, 0xa6, 0x2d,
	0x7a, 0xd3, 0xd2, 0x1e, 0xfb, 0x9b, 0xd6, 0xdc, 0x63, 0x7f, 0xd3, 0x9a, 0xff, 0xfe, 0x6f, 0x5a,
	0xff, 0xd5, 0xa0, 0x9a, 0x09, 0x40, 0x76, 0x14, 0xa5, 0x1a, 0xf3, 0x60, 0x94, 0xee, 0xaa, 0x27,
	0x30, 0x67, 0x47, 0x57, 0xa1, 0x3d, 0xf9, 0xba, 0x28, 0x25, 0x84, 0x33, 0xd7, 0x9d, 0xf1, 0xd7,
	0x45, 0x21, 0xf9, 0xfe, 0xe4, 0x83, 0x88, 0xb8, 0x87, 0xdf, 0x98, 0xb6, 0x00, 0xf1, 0x4a, 0x22,
	0xa3, 0x7a, 0xfc, 0xe9, 0xe4, 0xe7, 0xd0, 0x14, 0xdb, 0x2d, 0xc0, 0x21, 0x76, 0x09, 0x25, 0x61,
	0x34, 0xb5, 0x69, 0xcd, 0xac, 0x58, 0xfc, 0xbf, 0x97, 0xc8, 0x89, 0x80, 0x6e, 0xb8, 0x79, 0xb4,
	0xb3, 0x0d, 0xab, 0x45, 0x8c, 0x27, 0x0a, 0xe9, 0xaf, 0x34, 0x58, 0x29, 0x58, 0x0d, 0x6b, 0x31,
	0x85, 0x21, 0xb2, 0x17, 0xf5, 0x20, 0x20, 0x7e, 0x55, 0x9f, 0x32, 0xf0, 0xaa, 0x5e, 0xcb, 0x32,
	0xf0, 0x9a, 0xfe, 0x22, 0xb4, 0x4c, 0xdf, 0xf3, 0xa4, 0x13, 0x22, 0x1a, 0xaa, 0x57, 0xc2, 0x8a,
	0xde, 0x4c, 0x09, 0xfb, 0x1c, 0x47, 0x18, 0x96, 0x45, 0x2a, 0x89, 0xc5, 0x95, 0xa4, 0xb4, 0xd4,
	0x9b, 0xb3, 0x5a, 0xbf, 0xb7, 0x93, 0x95, 0x16, 0xf6, 0xca, 0xcf, 0xc8, 0xce, 0x10, 0xf1, 0xc0,
	0x6c, 0xc9, 0x37, 0x21, 0x35, 0xec, 0xbc, 0x03, 0x68, 0x52, 0xfc, 0x44, 0x56, 0xfc, 0x5f, 0x09,
	0x5a, 0x13, 0x79, 0x0e, 0xbd, 0x06, 0xa7, 0x5d, 0x7c, 0xc8, 0x72, 0xa4, 0x19, 0x87, 0x21, 0xf1,
	0xa8, 0x11, 0x8a, 0x93, 0x45, 0xd5, 0x13, 0x6b, 0x2e, 0x3e, 0xdc, 0x49, 0xa8, 0xf2, 0xd8, 0x89,
	0x58, 0x7f, 0x20, 0x19, 0xf9, 0x89, 0xef, 0xc7, 0x54, 0xdd, 0x9f, 0x94, 0xd9, 0xde, 0xe3, 0x94,
	0x03, 0x41, 0xd8, 0x8d, 0xd0, 0x06, 0x34, 0x45, 0x81, 0x1a, 0xd9, 0x9f, 0x12, 0xc3, 0xb1, 0x5d,
	0x9b, 0xca, 0x9a, 0xa2, 0xce, 0xf1, 0x7d, 0xfb, 0x53, 0xf2, 0x2e, 0x43, 0x59, 0xe5, 0xa7, 0x7e,
	0x49, 0x80, 0xcd, 0x21, 0x73, 0x87, 0x78, 0x48, 0x5b, 0x96, 0x3f, 0x24, 0x10, 0x20, 0xba, 0x00,
	0x2d, 0x46, 0x27, 0x06, 0xa5, 0x8e, 0x11, 0x11, 0xd3, 0xf7, 0x2c, 0xf1, 0x8c, 0x56, 0xd6, 0x1b,
	0x9c, 0x70, 0x40, 0x9d, 0x7d, 0x01, 0x5f, 0xfe, 0xc3, 0x22, 0xd4, 0xf6, 0x32, 0xee, 0x41, 0x9f,
	0x95, 0x18, 0x90, 0x3e, 0x9d, 0xa1, 0x8d, 0x69, 0xa9, 0x2f, 0x7b, 0xb3, 0xdb, 0x79, 0x69, 0x06,
	0x4e, 0x51, 0x4d, 0x74, 0xcf, 0xfe, 0xf2, 0xeb, 0x6f, 0x7e, 0xab, 0xad, 0x77, 0x5b, 0x9b, 0xfc,
	0xf7, 0x2b, 0x9c, 0xe3, 0x12, 0x2f, 0x52, 0xdf, 0x28, 0x5d, 0xe0, 0x3a, 0x64, 0xef, 0x62, 0x8f,
	0xd1, 0xa1, 0xe0, 0x76, 0xf9, 0x18, 0x1d, 0x8a, 0x2e, 0x76, 0xf3, 0x3a, 0xc8, 0x4b, 0xcb, 0x54,
	0x87, 0xcf, 0x4b, 0x50, 0xcf, 0xdf, 0xc0, 0xa0, 0x0b, 0x53, 0x1a, 0xfe, 0xb1, 0xdb, 0xa3, 0xce,
	0xc5, 0x99, 0x78, 0xa5, 0x26, 0xcf, 0x70, 0x4d, 0xda, 0xdd, 0x15, 0xfe, 0xd3, 0x18, 0xce, 0x73,
	0x49, 0x35, 0xa3, 0x4c, 0x97, 0xdf, 0xa5, 0xbf, 0x83, 0xc9, 0xb6, 0x38, 0x68, 0x73, 0x9a, 0xc1,
	0x0b, 0x9a, 0xb5, 0xce, 0x2b, 0xb3, 0x0b, 0x4c, 0x73, 0x14, 0x0f, 0x4b, 0xa6, 0x98, 0x07, 0xe8,
	0xc7, 0x84, 0x8e, 0xd7, 0x3f, 0xeb, 0x13, 0xe5, 0xdb, 0x4d, 0x37, 0xa0, 0x47, 0x9d, 0x97, 0x67,
	0x2a, 0xbf, 0xd4, 0x97, 0x11, 0xff, 0x72, 0x0d, 0x81, 0xf8, 0x2d, 0x11, 0x9f, 0xf9, 0xd7, 0x25,
	0x58, 0x2b, 0xac, 0xf8, 0x50, 0xf1, 0xc5, 0xf0, 0xb4, 0xea, 0xf0, 0x84, 0xea, 0xac, 0x71, 0x75,
	0x1a, 0x9d, 0x8c, 0x3a, 0xcc, 0x02, 0x3f, 0x83, 0xea, 0x6d, 0x82, 0x1d, 0x3a, 0xdc, 0x19, 0x12,
	0xf3, 0xe3, 0x63, 0x97, 0xde, 0x1d, 0xeb, 0xa9, 0x32, 0x32, 0xc5, 0x0b, 0x1e, 0x72, 0x86, 0xed,
	0x2b, 0x50, 0xf4, 0x2b, 0xae, 0xbd, 0xd2, 0x47, 0x9d, 0x10, 0x0f, 0xf8, 0x8f, 0xb8, 0xb2, 0xa4,
	0xcd, 0xd1, 0xd6, 0x9b, 0xa3, 0xad, 0xfb, 0x0b, 0xfc, 0xe3, 0x57, 0xfe, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0x15, 0x73, 0xb0, 0xb0, 0x1c, 0x26, 0x00, 0x00,
}
