// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/common.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 处理状态
type ProcessingStatus int32

const (
	ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED ProcessingStatus = 0
	ProcessingStatus_PROCESSING_STATUS_PENDING     ProcessingStatus = 1
	ProcessingStatus_PROCESSING_STATUS_PROCESSING  ProcessingStatus = 2
	ProcessingStatus_PROCESSING_STATUS_COMPLETED   ProcessingStatus = 3
	ProcessingStatus_PROCESSING_STATUS_FAILED      ProcessingStatus = 4
	ProcessingStatus_PROCESSING_STATUS_CANCELLED   ProcessingStatus = 5
)

var ProcessingStatus_name = map[int32]string{
	0: "PROCESSING_STATUS_UNSPECIFIED",
	1: "PROCESSING_STATUS_PENDING",
	2: "PROCESSING_STATUS_PROCESSING",
	3: "PROCESSING_STATUS_COMPLETED",
	4: "PROCESSING_STATUS_FAILED",
	5: "PROCESSING_STATUS_CANCELLED",
}

var ProcessingStatus_value = map[string]int32{
	"PROCESSING_STATUS_UNSPECIFIED": 0,
	"PROCESSING_STATUS_PENDING":     1,
	"PROCESSING_STATUS_PROCESSING":  2,
	"PROCESSING_STATUS_COMPLETED":   3,
	"PROCESSING_STATUS_FAILED":      4,
	"PROCESSING_STATUS_CANCELLED":   5,
}

func (x ProcessingStatus) String() string {
	return proto.EnumName(ProcessingStatus_name, int32(x))
}

func (ProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{0}
}

// 通用元数据信息
type Metadata struct {
	Data                 map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// 分页请求参数
type PaginationRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy               string   `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDesc             bool     `protobuf:"varint,4,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationRequest) Reset()         { *m = PaginationRequest{} }
func (m *PaginationRequest) String() string { return proto.CompactTextString(m) }
func (*PaginationRequest) ProtoMessage()    {}
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{1}
}

func (m *PaginationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationRequest.Unmarshal(m, b)
}
func (m *PaginationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationRequest.Marshal(b, m, deterministic)
}
func (m *PaginationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationRequest.Merge(m, src)
}
func (m *PaginationRequest) XXX_Size() int {
	return xxx_messageInfo_PaginationRequest.Size(m)
}
func (m *PaginationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationRequest proto.InternalMessageInfo

func (m *PaginationRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *PaginationRequest) GetSortDesc() bool {
	if m != nil {
		return m.SortDesc
	}
	return false
}

// 分页响应信息
type PaginationResponse struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages           int32    `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationResponse) Reset()         { *m = PaginationResponse{} }
func (m *PaginationResponse) String() string { return proto.CompactTextString(m) }
func (*PaginationResponse) ProtoMessage()    {}
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{2}
}

func (m *PaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationResponse.Unmarshal(m, b)
}
func (m *PaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationResponse.Marshal(b, m, deterministic)
}
func (m *PaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationResponse.Merge(m, src)
}
func (m *PaginationResponse) XXX_Size() int {
	return xxx_messageInfo_PaginationResponse.Size(m)
}
func (m *PaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationResponse proto.InternalMessageInfo

func (m *PaginationResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaginationResponse) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

// 过滤条件
type Filter struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{3}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Filter) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Filter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// 排序条件
type Sort struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Desc                 bool     `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{4}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Sort) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

// 健康检查请求
type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{5}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

// 健康检查响应
type HealthCheckResponse struct {
	Status               string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service              string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version              string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details              map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{6}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthCheckResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *HealthCheckResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *HealthCheckResponse) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

// 文档基础信息
type DocumentInfo struct {
	DocumentId           string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FileType             string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize             int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	TotalChunks          int32                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Metadata             *Metadata              `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DocumentInfo) Reset()         { *m = DocumentInfo{} }
func (m *DocumentInfo) String() string { return proto.CompactTextString(m) }
func (*DocumentInfo) ProtoMessage()    {}
func (*DocumentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{7}
}

func (m *DocumentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentInfo.Unmarshal(m, b)
}
func (m *DocumentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentInfo.Marshal(b, m, deterministic)
}
func (m *DocumentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentInfo.Merge(m, src)
}
func (m *DocumentInfo) XXX_Size() int {
	return xxx_messageInfo_DocumentInfo.Size(m)
}
func (m *DocumentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentInfo proto.InternalMessageInfo

func (m *DocumentInfo) GetDocumentId() string {
	if m != nil {
		return m.DocumentId
	}
	return ""
}

func (m *DocumentInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DocumentInfo) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *DocumentInfo) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *DocumentInfo) GetTotalChunks() int32 {
	if m != nil {
		return m.TotalChunks
	}
	return 0
}

func (m *DocumentInfo) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DocumentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DocumentInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// 文档片段信息
type ChunkInfo struct {
	ChunkId              string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocumentId           string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content              string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	StartPosition        int32                  `protobuf:"varint,4,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition          int32                  `protobuf:"varint,5,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	ChunkIndex           int32                  `protobuf:"varint,6,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkType            string                 `protobuf:"bytes,7,opt,name=chunk_type,json=chunkType,proto3" json:"chunk_type,omitempty"`
	TokenCount           int32                  `protobuf:"varint,8,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	Embedding            []float32              `protobuf:"fixed32,9,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChunkInfo) Reset()         { *m = ChunkInfo{} }
func (m *ChunkInfo) String() string { return proto.CompactTextString(m) }
func (*ChunkInfo) ProtoMessage()    {}
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{8}
}

func (m *ChunkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkInfo.Unmarshal(m, b)
}
func (m *ChunkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkInfo.Marshal(b, m, deterministic)
}
func (m *ChunkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkInfo.Merge(m, src)
}
func (m *ChunkInfo) XXX_Size() int {
	return xxx_messageInfo_ChunkInfo.Size(m)
}
func (m *ChunkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkInfo proto.InternalMessageInfo

func (m *ChunkInfo) GetChunkId() string {
	if m != nil {
		return m.ChunkId
	}
	return ""
}

func (m *ChunkInfo) GetDocumentId() string {
	if m != nil {
		return m.DocumentId
	}
	return ""
}

func (m *ChunkInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ChunkInfo) GetStartPosition() int32 {
	if m != nil {
		return m.StartPosition
	}
	return 0
}

func (m *ChunkInfo) GetEndPosition() int32 {
	if m != nil {
		return m.EndPosition
	}
	return 0
}

func (m *ChunkInfo) GetChunkIndex() int32 {
	if m != nil {
		return m.ChunkIndex
	}
	return 0
}

func (m *ChunkInfo) GetChunkType() string {
	if m != nil {
		return m.ChunkType
	}
	return ""
}

func (m *ChunkInfo) GetTokenCount() int32 {
	if m != nil {
		return m.TokenCount
	}
	return 0
}

func (m *ChunkInfo) GetEmbedding() []float32 {
	if m != nil {
		return m.Embedding
	}
	return nil
}

func (m *ChunkInfo) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ChunkInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// 相似度结果
type SimilarityResult struct {
	ChunkId              string     `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocumentId           string     `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Score                float32    `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Chunk                *ChunkInfo `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SimilarityResult) Reset()         { *m = SimilarityResult{} }
func (m *SimilarityResult) String() string { return proto.CompactTextString(m) }
func (*SimilarityResult) ProtoMessage()    {}
func (*SimilarityResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{9}
}

func (m *SimilarityResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimilarityResult.Unmarshal(m, b)
}
func (m *SimilarityResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimilarityResult.Marshal(b, m, deterministic)
}
func (m *SimilarityResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarityResult.Merge(m, src)
}
func (m *SimilarityResult) XXX_Size() int {
	return xxx_messageInfo_SimilarityResult.Size(m)
}
func (m *SimilarityResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarityResult.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarityResult proto.InternalMessageInfo

func (m *SimilarityResult) GetChunkId() string {
	if m != nil {
		return m.ChunkId
	}
	return ""
}

func (m *SimilarityResult) GetDocumentId() string {
	if m != nil {
		return m.DocumentId
	}
	return ""
}

func (m *SimilarityResult) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *SimilarityResult) GetChunk() *ChunkInfo {
	if m != nil {
		return m.Chunk
	}
	return nil
}

// 查询上下文
type QueryContext struct {
	Query                string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SessionId            string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId               string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Parameters           map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QueryContext) Reset()         { *m = QueryContext{} }
func (m *QueryContext) String() string { return proto.CompactTextString(m) }
func (*QueryContext) ProtoMessage()    {}
func (*QueryContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{10}
}

func (m *QueryContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryContext.Unmarshal(m, b)
}
func (m *QueryContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryContext.Marshal(b, m, deterministic)
}
func (m *QueryContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContext.Merge(m, src)
}
func (m *QueryContext) XXX_Size() int {
	return xxx_messageInfo_QueryContext.Size(m)
}
func (m *QueryContext) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContext.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContext proto.InternalMessageInfo

func (m *QueryContext) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryContext) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *QueryContext) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *QueryContext) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *QueryContext) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// 任务状态信息
type TaskStatus struct {
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status               ProcessingStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=api.common.v1.ProcessingStatus" json:"status,omitempty"`
	Progress             float32                `protobuf:"fixed32,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TaskStatus) Reset()         { *m = TaskStatus{} }
func (m *TaskStatus) String() string { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()    {}
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_372283428b44e521, []int{11}
}

func (m *TaskStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatus.Unmarshal(m, b)
}
func (m *TaskStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatus.Marshal(b, m, deterministic)
}
func (m *TaskStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatus.Merge(m, src)
}
func (m *TaskStatus) XXX_Size() int {
	return xxx_messageInfo_TaskStatus.Size(m)
}
func (m *TaskStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatus proto.InternalMessageInfo

func (m *TaskStatus) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskStatus) GetStatus() ProcessingStatus {
	if m != nil {
		return m.Status
	}
	return ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED
}

func (m *TaskStatus) GetProgress() float32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *TaskStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TaskStatus) GetStartedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *TaskStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TaskStatus) GetCompletedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.common.v1.ProcessingStatus", ProcessingStatus_name, ProcessingStatus_value)
	proto.RegisterType((*Metadata)(nil), "api.common.v1.Metadata")
	proto.RegisterMapType((map[string]string)(nil), "api.common.v1.Metadata.DataEntry")
	proto.RegisterType((*PaginationRequest)(nil), "api.common.v1.PaginationRequest")
	proto.RegisterType((*PaginationResponse)(nil), "api.common.v1.PaginationResponse")
	proto.RegisterType((*Filter)(nil), "api.common.v1.Filter")
	proto.RegisterType((*Sort)(nil), "api.common.v1.Sort")
	proto.RegisterType((*HealthCheckRequest)(nil), "api.common.v1.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "api.common.v1.HealthCheckResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.common.v1.HealthCheckResponse.DetailsEntry")
	proto.RegisterType((*DocumentInfo)(nil), "api.common.v1.DocumentInfo")
	proto.RegisterType((*ChunkInfo)(nil), "api.common.v1.ChunkInfo")
	proto.RegisterType((*SimilarityResult)(nil), "api.common.v1.SimilarityResult")
	proto.RegisterType((*QueryContext)(nil), "api.common.v1.QueryContext")
	proto.RegisterMapType((map[string]string)(nil), "api.common.v1.QueryContext.ParametersEntry")
	proto.RegisterType((*TaskStatus)(nil), "api.common.v1.TaskStatus")
}

func init() {
	proto.RegisterFile("v1/common.proto", fileDescriptor_372283428b44e521)
}

var fileDescriptor_372283428b44e521 = []byte{
	// 1238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0xa9, 0x27, 0xaf, 0x9c, 0x44, 0x9d, 0x1a, 0x31, 0x23, 0xc7, 0xb0, 0x22, 0x34, 0x81,
	0xda, 0xa0, 0x12, 0x9c, 0xa0, 0xc8, 0xa3, 0x08, 0x0a, 0xeb, 0x91, 0x94, 0x68, 0xe2, 0xa8, 0x23,
	0x67, 0xd3, 0x8d, 0x30, 0x26, 0xc7, 0x0a, 0x21, 0x8a, 0x64, 0x38, 0x23, 0x21, 0x0a, 0xba, 0xe8,
	0xaa, 0xcb, 0x7e, 0x44, 0x81, 0xae, 0xba, 0xeb, 0xc7, 0x74, 0xd1, 0x4d, 0x7f, 0xa1, 0x6b, 0xaf,
	0x8a, 0x79, 0x88, 0x96, 0x25, 0x1b, 0x8e, 0xb3, 0x12, 0xef, 0xbd, 0x67, 0x86, 0x97, 0xe7, 0xdc,
	0x39, 0x23, 0xb8, 0x31, 0xdb, 0x6b, 0xb9, 0xd1, 0x64, 0x12, 0x85, 0xcd, 0x38, 0x89, 0x78, 0x84,
	0xae, 0x91, 0xd8, 0x6f, 0xea, 0xcc, 0x6c, 0xaf, 0xba, 0x3b, 0x8a, 0xa2, 0x51, 0x40, 0x5b, 0xb2,
	0x78, 0x34, 0x3d, 0x6e, 0x71, 0x7f, 0x42, 0x19, 0x27, 0x93, 0x58, 0xe1, 0xab, 0x5b, 0x33, 0x12,
	0xf8, 0x1e, 0xe1, 0xb4, 0xb5, 0x78, 0x50, 0x85, 0xfa, 0x7f, 0x06, 0x94, 0x5e, 0x51, 0x4e, 0x3c,
	0xc2, 0x09, 0xfa, 0x06, 0x72, 0xe2, 0xd7, 0x36, 0x6a, 0xd9, 0x46, 0xf9, 0xc1, 0x9d, 0xe6, 0x99,
	0x97, 0x34, 0x17, 0xb0, 0x66, 0x97, 0x70, 0xd2, 0x0b, 0x79, 0x32, 0xc7, 0x12, 0x8e, 0x9e, 0x00,
	0xb8, 0x09, 0x25, 0x9c, 0x7a, 0x43, 0xc2, 0x6d, 0xb3, 0x66, 0x34, 0xca, 0x0f, 0xaa, 0x4d, 0xd5,
	0x52, 0x73, 0xd1, 0x52, 0xf3, 0x70, 0xd1, 0x12, 0xb6, 0x34, 0x7a, 0x9f, 0x8b, 0xa5, 0xd3, 0xd8,
	0x5b, 0x2c, 0xcd, 0x5e, 0xbe, 0x54, 0xa3, 0xf7, 0x79, 0xf5, 0x11, 0x58, 0x69, 0x23, 0xa8, 0x02,
	0xd9, 0x31, 0x9d, 0xdb, 0x46, 0xcd, 0x68, 0x58, 0x58, 0x3c, 0xa2, 0x4d, 0xc8, 0xcf, 0x48, 0x30,
	0xa5, 0xb2, 0x1f, 0x0b, 0xab, 0xe0, 0xa9, 0xf9, 0xd8, 0xa8, 0xff, 0x66, 0xc0, 0x67, 0x7d, 0x32,
	0xf2, 0x43, 0xc2, 0xfd, 0x28, 0xc4, 0xf4, 0xdd, 0x94, 0x32, 0x8e, 0xb6, 0x21, 0x17, 0x93, 0x11,
	0x95, 0x5b, 0xe4, 0xdb, 0xc5, 0x93, 0x76, 0xae, 0x6a, 0x36, 0x0c, 0x2c, 0x93, 0xe8, 0x1e, 0x58,
	0xe2, 0x77, 0xc8, 0xfc, 0x0f, 0x6a, 0xc3, 0x7c, 0xdb, 0x3a, 0x69, 0x17, 0xaa, 0x39, 0xdb, 0x6b,
	0x18, 0xb8, 0x24, 0x6a, 0x03, 0xff, 0x03, 0x45, 0x5b, 0x50, 0x64, 0x51, 0xc2, 0x87, 0x47, 0x73,
	0xf9, 0x2d, 0x16, 0x2e, 0x88, 0xb0, 0x3d, 0x47, 0xdb, 0x60, 0xc9, 0x82, 0x47, 0x99, 0x6b, 0xe7,
	0x6a, 0x46, 0xa3, 0x84, 0x4b, 0x22, 0xd1, 0xa5, 0xcc, 0xad, 0xff, 0x0c, 0x68, 0xb9, 0x1f, 0x16,
	0x47, 0x21, 0xa3, 0x08, 0x2d, 0x37, 0xa4, 0xfb, 0xd8, 0x5e, 0xeb, 0x63, 0xe9, 0xe5, 0x9b, 0x90,
	0xe7, 0x11, 0x27, 0x81, 0x7c, 0x75, 0x16, 0xab, 0x00, 0xed, 0x42, 0x59, 0x3e, 0x0c, 0x05, 0x8e,
	0xc9, 0x77, 0xe7, 0x31, 0xc8, 0x54, 0x5f, 0x64, 0xea, 0xbf, 0x1a, 0x50, 0x78, 0xee, 0x07, 0x9c,
	0x26, 0x68, 0x07, 0xf2, 0xc7, 0x3e, 0x0d, 0x3c, 0xc5, 0xa3, 0x24, 0x21, 0x31, 0x2b, 0x06, 0x56,
	0x59, 0xd4, 0x83, 0x52, 0x14, 0xd3, 0x84, 0xf0, 0x28, 0x51, 0xac, 0xb6, 0xbf, 0x3c, 0x69, 0xdf,
	0x4b, 0xbe, 0xc0, 0x26, 0x7d, 0x87, 0xcd, 0x90, 0x62, 0x73, 0xc4, 0x71, 0x76, 0xc4, 0x29, 0x36,
	0x03, 0x8e, 0xb3, 0x01, 0xa7, 0x38, 0x17, 0xf8, 0x63, 0x8a, 0x4d, 0x3f, 0xc4, 0xe9, 0x52, 0x74,
	0x13, 0x0a, 0x52, 0x0c, 0x66, 0x67, 0x6b, 0x59, 0xc1, 0x91, 0x8a, 0xea, 0x4f, 0x20, 0x37, 0x88,
	0x12, 0x7e, 0x59, 0x17, 0x08, 0x72, 0x92, 0x45, 0x53, 0xb2, 0x28, 0x9f, 0xeb, 0x9b, 0x80, 0xbe,
	0xa7, 0x24, 0xe0, 0x6f, 0x3b, 0x6f, 0xa9, 0x3b, 0xd6, 0x92, 0xd6, 0x7f, 0x37, 0xe1, 0xf3, 0x33,
	0x69, 0xcd, 0xec, 0x4d, 0x28, 0x30, 0x4e, 0xf8, 0x94, 0xe9, 0x79, 0xd1, 0x11, 0xb2, 0xa1, 0xc8,
	0x68, 0x32, 0xf3, 0xdd, 0xc5, 0xd0, 0x2c, 0x42, 0x51, 0x99, 0xd1, 0x84, 0xf9, 0x51, 0xa8, 0x75,
	0x5d, 0x84, 0xe8, 0x31, 0x58, 0xe9, 0x59, 0x93, 0xe4, 0x5e, 0x32, 0xbf, 0x29, 0x18, 0x39, 0x50,
	0xf4, 0x28, 0x27, 0x7e, 0xc0, 0xec, 0xbc, 0x3c, 0x6f, 0xad, 0x95, 0xf3, 0x76, 0x4e, 0xeb, 0xcd,
	0xae, 0x5a, 0xa1, 0x4e, 0xdf, 0x62, 0x7d, 0xf5, 0x29, 0x6c, 0x2c, 0x17, 0xae, 0x74, 0x1a, 0xfe,
	0x35, 0x61, 0xa3, 0x1b, 0xb9, 0xd3, 0x09, 0x0d, 0xb9, 0x13, 0x1e, 0x47, 0xa8, 0x01, 0x65, 0x4f,
	0xc7, 0x43, 0x7f, 0x4d, 0x04, 0x58, 0xd4, 0x1c, 0x4f, 0x08, 0xc5, 0x7d, 0x1e, 0xe8, 0x4d, 0x97,
	0x84, 0x92, 0x59, 0x31, 0xac, 0xc7, 0x7e, 0x40, 0x87, 0x7c, 0x1e, 0x53, 0x4d, 0x5b, 0x49, 0x24,
	0x0e, 0xe7, 0xf1, 0x69, 0x51, 0x4e, 0x72, 0x4e, 0x0e, 0xac, 0x2c, 0xca, 0x49, 0xbe, 0x03, 0x1b,
	0x6a, 0x66, 0xdd, 0xb7, 0xd3, 0x70, 0x2c, 0xf8, 0x11, 0x43, 0xab, 0xe6, 0xb8, 0x23, 0x53, 0xe8,
	0x21, 0x94, 0x26, 0xda, 0x8f, 0xec, 0x82, 0xa4, 0x7d, 0xeb, 0x02, 0xbb, 0xc2, 0x29, 0x70, 0xc5,
	0xa8, 0x8a, 0x9f, 0x6e, 0x54, 0xa5, 0x2b, 0x18, 0x55, 0xfd, 0xaf, 0x2c, 0x58, 0xb2, 0x6b, 0x49,
	0x6f, 0x1d, 0x4a, 0xf2, 0xab, 0xce, 0xe1, 0xb6, 0x28, 0x0b, 0x8e, 0xb7, 0x2a, 0x81, 0x79, 0xb1,
	0x04, 0x36, 0x14, 0xdd, 0x28, 0xe4, 0x34, 0xe4, 0x8b, 0xc1, 0xd4, 0x21, 0xba, 0x0b, 0xd7, 0x19,
	0x27, 0x09, 0x1f, 0xc6, 0x11, 0xf3, 0x85, 0xb1, 0xe8, 0xa3, 0x7f, 0x4d, 0x66, 0xfb, 0x3a, 0x29,
	0xa8, 0xa6, 0xa1, 0x77, 0x0a, 0xd2, 0x54, 0xd3, 0xd0, 0x4b, 0x21, 0xbb, 0x50, 0xd6, 0x1d, 0x87,
	0x1e, 0x7d, 0x2f, 0xd9, 0xce, 0x63, 0x50, 0xbd, 0x8a, 0x0c, 0xda, 0x01, 0x15, 0x29, 0xa5, 0x8b,
	0xb2, 0x0f, 0x4b, 0x66, 0xa4, 0xd4, 0xd2, 0x81, 0xc6, 0x34, 0x1c, 0xba, 0xd1, 0x34, 0x54, 0xdc,
	0x49, 0x07, 0x1a, 0xd3, 0xb0, 0x23, 0x32, 0xe8, 0x36, 0x58, 0x74, 0x72, 0x44, 0x3d, 0xcf, 0x0f,
	0x47, 0xb6, 0x55, 0xcb, 0x36, 0x4c, 0x7c, 0x9a, 0x58, 0x11, 0x0d, 0x3e, 0x5d, 0xb4, 0xf2, 0x55,
	0x44, 0xfb, 0xc3, 0x80, 0xca, 0xc0, 0x9f, 0xf8, 0x01, 0x49, 0x7c, 0x3e, 0xc7, 0x94, 0x4d, 0x03,
	0x8e, 0x6e, 0xad, 0x6a, 0x77, 0x2a, 0xd9, 0xee, 0x39, 0x92, 0x9d, 0x51, 0xea, 0x2e, 0xe4, 0x99,
	0x1b, 0x25, 0xea, 0x24, 0x98, 0xed, 0x1b, 0x27, 0xed, 0x0d, 0x80, 0x9d, 0x4c, 0xe6, 0x97, 0xef,
	0xbe, 0xce, 0x64, 0x32, 0x19, 0xac, 0xaa, 0xa8, 0x09, 0x79, 0xb9, 0xa5, 0xf6, 0x12, 0x7b, 0x65,
	0xa8, 0xd3, 0x39, 0xc2, 0x0a, 0x56, 0xff, 0xd3, 0x84, 0x8d, 0x1f, 0xa7, 0x34, 0x99, 0x77, 0x84,
	0xee, 0xef, 0xa5, 0x7b, 0xbe, 0x13, 0xf1, 0x9a, 0x7b, 0xca, 0xac, 0xd0, 0x8a, 0x51, 0x26, 0xac,
	0xeb, 0xb4, 0x4d, 0x4b, 0x67, 0x1c, 0x4f, 0x5c, 0x60, 0x53, 0x46, 0x13, 0x51, 0xd3, 0x17, 0x98,
	0x08, 0x1d, 0x0f, 0xfd, 0x00, 0x10, 0x93, 0x84, 0x4c, 0x28, 0xa7, 0x89, 0xb8, 0x45, 0x84, 0x61,
	0xdd, 0x5f, 0x69, 0x6e, 0xb9, 0x8f, 0x66, 0x3f, 0x45, 0x2b, 0xb3, 0x5a, 0x5a, 0x7e, 0xd6, 0x34,
	0xf3, 0x57, 0x30, 0xcd, 0xea, 0x33, 0xb8, 0xb1, 0xb2, 0xf1, 0x95, 0xcc, 0xee, 0x1f, 0x13, 0xe0,
	0x90, 0xb0, 0xf1, 0x40, 0x19, 0xfe, 0x16, 0x14, 0x39, 0x61, 0x4b, 0x72, 0x16, 0x44, 0xe8, 0x78,
	0xe8, 0x51, 0x7a, 0x43, 0x88, 0x2d, 0xae, 0x3f, 0xd8, 0x5d, 0xf9, 0xd2, 0x7e, 0x12, 0xb9, 0x82,
	0xb3, 0x70, 0xa4, 0x76, 0x4a, 0xaf, 0x90, 0xfb, 0x50, 0x8a, 0x93, 0x68, 0x94, 0x50, 0xc6, 0x2e,
	0x12, 0x3a, 0x05, 0x88, 0xc3, 0x3b, 0xa1, 0x8c, 0x89, 0x4b, 0x3e, 0xa7, 0xa6, 0x49, 0x87, 0x62,
	0x70, 0xe5, 0x31, 0x55, 0x83, 0xfb, 0x11, 0x0c, 0x69, 0xf4, 0xda, 0xcc, 0x17, 0xae, 0x30, 0xf3,
	0xe8, 0x19, 0x6c, 0xb8, 0xd1, 0x24, 0x0e, 0xe8, 0x47, 0x1b, 0x64, 0x39, 0xc5, 0xef, 0xf3, 0xaf,
	0xfe, 0x36, 0xa0, 0xb2, 0x4a, 0x0c, 0xba, 0x03, 0x3b, 0x7d, 0xfc, 0xba, 0xd3, 0x1b, 0x0c, 0x9c,
	0x83, 0x17, 0xc3, 0xc1, 0xe1, 0xfe, 0xe1, 0x9b, 0xc1, 0xf0, 0xcd, 0xc1, 0xa0, 0xdf, 0xeb, 0x38,
	0xcf, 0x9d, 0x5e, 0xb7, 0x92, 0x41, 0x3b, 0x70, 0x6b, 0x1d, 0xd2, 0xef, 0x1d, 0x74, 0x9d, 0x83,
	0x17, 0x15, 0x03, 0xd5, 0xe0, 0xf6, 0x39, 0xe5, 0x34, 0x53, 0x31, 0xd1, 0x2e, 0x6c, 0xaf, 0x23,
	0x3a, 0xaf, 0x5f, 0xf5, 0x5f, 0xf6, 0x0e, 0x7b, 0xdd, 0x4a, 0x16, 0xdd, 0x06, 0x7b, 0x1d, 0xf0,
	0x7c, 0xdf, 0x79, 0xd9, 0xeb, 0x56, 0x72, 0x17, 0x2c, 0xdf, 0x3f, 0xe8, 0xf4, 0x5e, 0x0a, 0x40,
	0xbe, 0x7d, 0xf3, 0xa7, 0xcd, 0x84, 0x8c, 0x5a, 0x24, 0xf6, 0xf5, 0x9f, 0xf0, 0xd6, 0x6c, 0xef,
	0xdb, 0xd9, 0xde, 0x51, 0x41, 0x32, 0xf2, 0xf0, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x90,
	0xcf, 0x21, 0x9e, 0x0b, 0x00, 0x00,
}
